"""Build the reviewed catalogue. Original class and skill indexes stay stable."""
import json
from pathlib import Path
catalog={}
def add(ci,entries):
 catalog[str(ci)]=[]
 for name,effect,kw in entries:
  d=dict(n=name,effect=effect,cd=8,mp=16,pow=0,col=0xffdb86,radius=5,range=12,duration=4)
  d.update(kw);catalog[str(ci)].append(d)
def k(n,e,**kw):return n,e,kw
add(0,[k('Corte Giratório','area',pow=1.8,radius=5,cd=6),k('Investida','move',range=8,cd=5,mp=12),k('Grito de Guerra','buff',duration=8,amount=.5,cd=16),k('Lâmina Rúnica','line',pow=4.2,range=8,evolution=True,mp=25),k('Golpe Pesado','target',pow=3.2,range=4),k('Provocação','taunt',radius=7),k('Varredura','push',radius=5),k('Fôlego','heal',scope='self',amount=.3,cd=16)])
add(1,[k('Passo Sombrio','move',range=8,cd=4,mp=10),k('Furtividade','stealth',duration=5,cd=14),k('Lâmina Envenenada','venom',duration=8,cd=7),k('Mil Cortes','pulses',pow=3.6,pulses=6,radius=4.5,ground=False,evolution=True),k('Execução','execute',pow=2.4,range=3),k('Cortina de Fumaça','blind',radius=5,duration=5),k('Adaga','bolt',pow=2.5,cd=5),k('Evasão','evade',duration=.7,cd=10)])
add(2,[k('Golpe de Escudo','cone',pow=2.2,range=4.5,cd=4),k('Impacto','push',radius=6,cd=7),k('Muralha','guard',scope='self',amount=.7,duration=5,cd=14),k('Fortaleza Viva','guard',scope='group',amount=.5,duration=5,evolution=True,cd=16),k('Provocar','taunt',radius=8),k('Aparo','block',duration=2),k('Passo Pesado','move',range=5),k('Abalo','interrupt',radius=5)])
add(4,[k('Chuva de Flechas','pulses',pow=3.5,pulses=5,radius=4,ground=True),k('Salto Evasivo','move',range=7,back=True,cd=5,mp=8),k('Flecha Perfurante','line',pow=3.2,range=14,cd=4),k('Flecha Estelar','fan',pow=6,evolution=True,mp=25),k('Tiro Preciso','target',pow=3.6,range=16,cd=10),k('Flecha Enredante','slow',single=True,duration=4),k('Armadilha','trap',duration=12,radius=2),k('Disparo Rápido','bolt',pow=1.8,cd=2,mp=8)])
add(5,[k('Luz Curativa','heal',scope='group',amount=.5,growth=.02,cd=9,mp=20,radius=8),k('Julgamento','area',pow=1.8,cd=6,radius=6,radiusGrowth=.4),k('Bênção','guard',scope='group',amount=.3,selfAmount=.6,duration=5,cd=14,mp=18,radius=8),k('Purificação','cleanse',radius=8,cd=12),k('Égide Sagrada','ward',scope='group',amount=.2,growth=.02,radius=8,duration=6,cd=14,mp=22),k('Sol Nascente','healzone',amount=.7,radius=6,duration=3,cd=14,mp=35,evolution=True),k('Passo da Luz','move',range=6,cd=7,mp=12),k('Correntes Sagradas','slow',radius=4,duration=3,cd=10,mp=18)])
add(6,[k('Lobo Espiritual','summon',kind='wolf',count=1,mp=25,cd=14),k('Elo Arcano','order',scope='summons',cd=6),k('Pacto','heal',scope='summons',amount=.45,cd=12),k('Matilha Espiritual','summon',kind='wolf',count=3,mp=40,cd=16,evolution=True),k('Recolher','recall',scope='summons'),k('Frenesi','allybuff',scope='summons',amount=.6,duration=8),k('Abrigo','ward',scope='summons',amount=.3,duration=6),k('Sentinela','summon',kind='sentinel',count=1,cd=14)])
add(7,[k('Soldado Esquelético','summon',kind='skel',count=2,cd=12,mp=22),k('Praga','pulses',pow=1.4,pulses=5,radius=5.5,ground=True,cd=7),k('Pacto Sombrio','allybuff',scope='dead',amount=.6,duration=8,cd=12),k('Erguer Eco','echo',cd=14,mp=24),k('Ordem Fúnebre','order',scope='dead'),k('Pacto dos Mortos','heal',scope='dead',amount=.35,cd=14),k('Domínio dos Ecos','area',pow=3.8,radius=7,evolution=True),k('Mortalha','ward',scope='dead',amount=.3,duration=6)])
add(8,[k('Bola de Fogo','bolt',pow=3.2,cd=3,mp=10),k('Chuva de Meteoros','pulses',pow=5,pulses=5,radius=5,ground=True,cd=10,mp=30),k('Explosão Ígnea','area',pow=2.3,radius=6,cd=7),k('Sol Negro','pulses',pow=3.4,pulses=5,radius=4,ground=True,evolution=True,cd=11,mp=35),k('Combustão','burn',pow=2,duration=4),k('Jato de Chamas','line',pow=2.8,range=10),k('Passo de Cinzas','move',range=6),k('Muralha de Fogo','barrier',radius=1.5,duration=5)])
add(9,[k('Lança de Gelo','line',pow=2.6,range=12,cd=3),k('Nova de Gelo','slow',radius=6,ground=False,duration=4),k('Maremoto','push',radius=5,cd=6),k('Era do Gelo','pulses',pow=3,pulses=4,radius=6,ground=True,evolution=True,cd=11),k('Prisão Glacial','root',single=True,duration=2),k('Armadura de Gelo','ward',scope='self',amount=.3,duration=6),k('Estilhaço','target',pow=3,range=14),k('Deslizar','move',range=7)])
add(10,[k('Estaca de Pedra','line',pow=2.4,range=8,cd=4),k('Tremor Sísmico','area',pow=2.2,radius=6,cd=7),k('Pele de Pedra','guard',scope='self',amount=.65,duration=5,cd=14),k('Colosso de Pedra','summon',kind='golem',count=1,evolution=True,cd=16,mp=40),k('Muralha de Rocha','barrier',radius=1.7,duration=6),k('Areia Movediça','slowzone',radius=4,duration=6),k('Arremesso de Rocha','bolt',pow=3,cd=6),k('Erupção','push',radius=4,ground=True)])
add(11,[k('Corrente de Raios','chain',pow=2,cd=5),k('Rajada de Vento','push',radius=5,cd=4),k('Tempestade de Raios','pulses',pow=3.8,pulses=5,radius=5,ground=True,cd=10,mp=28),k('Fúria dos Céus','pulses',pow=3.4,pulses=3,radius=3,ground=True,evolution=True),k('Paralisia','interrupt',single=True),k('Passo Relâmpago','move',range=7),k('Aceleração','speed',amount=.4,duration=6),k('Campo Estático','slowzone',radius=4,duration=5)])
add(12,[k('Âncora Temporal','anchor',cd=16,mp=20),k('Dilatação','dilate',cd=14,mp=24,radius=5),k('Reprise','reprise',cd=12,mp=25),k('Recompor','rewindheal',cd=16),k('Acelerar','speed',amount=.4,duration=6),k('Suspender','interrupt',single=True),k('Salto Temporal','move',range=7),k('Pulso Temporal','area',pow=2.4,radius=5)])
add(13,[k('Passagem Vinculada','passage',cd=12,mp=20),k('Corte Espacial','line',pow=2.5,range=10,cd=7),k('Ascensão de Fenda','gate',cd=20,mp=0),k('Convergência','pull',radius=5,ground=True),k('Ruptura','area',pow=2.8,radius=5,ground=True),k('Dobra','move',range=8),k('Fronteira','barrier',radius=1.5,duration=5),k('Exílio Breve','push',single=True,range=10)])
add(14,[k('Elo Protetor','link',duration=20,cd=4,mp=14),k('Interposição','interpose',cd=10,mp=20),k('Juramento','guard',scope='group',amount=.4,radius=8,duration=6,cd=18),k('Âncora Protetora','anchorward',duration=20),k('Escudo do Vínculo','ward',scope='ally',amount=.35,duration=6),k('Desafio','taunt',radius=8),k('Repulsão','push',radius=5),k('Reunir','recall',scope='oneSummon')])
add(15,[k('Forma Feral','form',form='feral',cd=3,mp=10),k('Forma Alada','form',form='alada',cd=3,mp=10),k('Forma Blindada','form',form='blindada',cd=3,mp=10),k('Forma Ágil','form',form='agil',cd=3,mp=10),k('Salto Bestial','move',range=8),k('Rugido','push',radius=6),k('Adaptação','guard',scope='self',amount=.4,duration=5),k('Regenerar','heal',scope='self',amount=.35,cd=14)])
add(16,[k('Sentinela Rúnica','device',kind='turret',cd=10,mp=22),k('Armadilha Rúnica','device',kind='trap',cd=10,mp=18),k('Emissor','device',kind='emitter',cd=12,mp=24),k('Reparar','repair',amount=.5),k('Desmontar','dismantle',mp=0,cd=1),k('Sobrecarga','detonate',pow=3,radius=5),k('Projetar','relocate',range=8),k('Pulso Rúnico','area',pow=2.3,radius=5)])
add(17,[k('Aparo Espectral','parry',duration=1,cd=6,mp=10),k('Passo de Flanco','move',range=6,cd=5),k('Resposta Fantasma','counter',pow=4,range=4,cd=3),k('Estocada','target',pow=3,range=4),k('Corte Espectral','line',pow=2.5,range=8),k('Desarmar','weaken',single=True,amount=.3,duration=5),k('Recuar','move',back=True,range=6),k('Desafio Espectral','taunt',radius=6)])
add(18,[k('Correnteza Elétrica','move',range=8,energy=1,cd=4),k('Descarga','chain',pow=2.5,energy=2,cd=6),k('Corpo de Tempestade','speed',amount=.5,duration=6,energy=1),k('Arco Voltaico','target',pow=3,energy=1),k('Campo de Repulsão','push',radius=6,energy=1),k('Pulso Estático','slow',radius=5,energy=1),k('Barreira Elétrica','ward',scope='self',amount=.3,duration=6,energy=2),k('Trovoada','area',pow=3.5,radius=6,ground=True,energy=3)])
add(19,[k('Presságio','foresight',duration=8),k('Selo Preventivo','seal',radius=4,duration=8),k('Desvio do Destino','move',range=6),k('Enfraquecer','weaken',single=True,amount=.3,duration=5),k('Revelação','reveal',range=30,duration=8),k('Vislumbre','survey',range=20),k('Sinal','order',scope='allies'),k('Ruína Anunciada','pulses',pow=3,pulses=1,radius=4,ground=True,delay=1.5)])
add(20,[k('Boca do Vazio','capture',duration=3,cd=6),k('Devolver','release',pow=3,cd=3),k('Consumir','consume',mp=0,cd=4),k('Carapaça Vazia','ward',scope='self',amount=.3,duration=6),k('Passo Vazio','move',range=6),k('Sucção','pull',radius=5,ground=True),k('Rasgo','cone',pow=2.6,range=5),k('Silêncio','interrupt',single=True)])
for ci,skills in catalog.items():
 assert len(skills)==8
 for si,d in enumerate(skills):
  d['sourceClass']=int(ci);d['skillId']=ci+':'+str(si);d['kit111']=True
  d['rare103']=int(ci)>=12 or int(ci)==7 and si>=3
  d['t']='kit111';d['mp']=0 if 'energy' in d else d['mp']
Path('tools/class-catalog111.json').write_text(json.dumps(catalog,ensure_ascii=False,indent=2),encoding='utf-8')
