// One shortcut for 2–3 equipped techniques. No extra slots or separate cooldown pool.
const COMBO_EFFECTS261=new Set(['area','target','line','cone','bolt','fan','chain','pulses','burn','slow','root','interrupt','push','pull','blind','weaken','guard','ward','heal','allybuff','cleanse','buff','speed','reveal','conditional260']);
function comboCompatible261(s){return !!(s&&!s.empty&&s.kit111&&COMBO_EFFECTS261.has(s.effect)&&s.skillId!=='4:2')}
function comboParts261(){return (run.combo261||[]).map(id=>(player.skills||[]).find(s=>s.skillId===id&&!s.empty)).filter(Boolean)}
function comboSkill261(){const parts=comboParts261();return {n:'Combinação',combo261:true,t:'combo261',parts261:parts,mp:0,pow:0,cd:Math.max(1,...parts.map(s=>s.cd)),cdT:Math.max(0,...parts.map(s=>s.cdT||0)),cdMax:Math.max(1,...parts.map(s=>s.cdMax||skillCooldown(s)))}}
function comboValidity261(){const ids=run.combo261||[],parts=comboParts261();if(ids.length<2||ids.length>3||new Set(ids).size!==ids.length)return 'Escolha 2 ou 3 técnicas.';if(parts.length!==ids.length||!parts.every(comboCompatible261))return 'Reequipe as técnicas da combinação.';return ''}
function comboDescription261(){return comboParts261().map(s=>s.n).join(' + ')+'<br><b>Custo total:</b> '+resourceText260(comboSkill261())+'<br>Compartilha a recarga de cada técnica.'}
function comboConfigure261(id){if(L.mode!=='world'||!inCity(player.x,player.z))return false;const ids=run.combo261||[];if(!id)run.combo261=[];else if(ids.includes(id))run.combo261=ids.filter(x=>x!==id);else{const s=player.skills.find(s=>s.skillId===id);if(ids.length>=3||!comboCompatible261(s))return false;run.combo261=[...ids,id]}saveRun();buildSteal();return true}
function comboView261(){view=comboView261;let h=characterTabs('skills')+characterBack118('Combinação')+'<div class="sysline">Escolha 2 ou 3 técnicas equipadas para lançar juntas na tecla '+keyLabel(keyOf('combo261'))+' ou no botão COMBO. Soma os custos; cada técnica entra em recarga. Se faltar um recurso ou alvo necessário, nada é gasto.<br>Movimentos, flecha carregada, invocações e técnicas com reservas especiais continuam nos próprios botões.</div>';const selected=run.combo261||[],city=L.mode==='world'&&inCity(player.x,player.z);for(const s of player.skills.filter(comboCompatible261)){h+=row(s.n,briefSkill260(s)+'<br>'+resourceText260(s),btn(selected.includes(s.skillId)?'Retirar':'Adicionar','comboset261',s.skillId,city&&(selected.includes(s.skillId)||selected.length<3)))}h+=row('Combinação atual',selected.length?comboDescription261():'Nenhuma técnica selecionada.',btn('Limpar','comboset261','',city&&selected.length>0));openModal('PERSONAGEM',h,'combo261')}
function comboButton261(box){if(!(run.combo261||[]).length)return;const b=document.createElement('div');b.className='b';b.id='stCombo261';b.style.borderColor='#e7ca6d';b.innerHTML='<div class="cd"></div><span class="k">'+(touch?'◆':keyLabel(keyOf('combo261')))+'</span><span class="nm">COMBO</span>';b.title=tipText155(comboDescription261());bindBtn(b,useCombo261);box.appendChild(b)}
function useCombo261(){if(!player||player.dead||paused||CM154.charge)return false;const invalid=comboValidity261();if(invalid){toast(invalid);return false}const sk=comboSkill261(),parts=sk.parts261;if(parts.some(s=>s.cdT>0))return false;for(const s of parts){const error=kitCheck111(s);if(error){toast(s.n+': '+error);return false}}const receipt=paySkill258(sk);if(!receipt)return false;
 for(const s of parts)s.cdT=s.cdMax=skillCooldown(s);player.lastSpellAt=time;
 for(const s of parts){faceTarget(s.range||12);const actual=cm154Mod(s);kitRun111(actual);cm154After(actual);castFluid139(s)}
 player.atkT=.001;finishSkill258(sk,receipt);sfx('skill');return true}
