// Investigations require only movement, basic combat and interaction, never a rare skill.
const TRIALS113={
 7:{choice:'Ecos',hint:'Há algo familiar no que ainda ressoa, mesmo sem você reconhecer a voz.',title:'Vozes que permanecem',task:'Recolha os três fragmentos de memória e elimine as ameaças. Um eco acompanha você.',mode:'collect',count:2,verbs:['RECOLHER MEMÓRIA I','RECOLHER MEMÓRIA II','RECOLHER MEMÓRIA III'],lines:['Você recolheu os três fragmentos antes que se apagassem.','Desta vez, mais uma memória conseguiu atravessar.','Os fragmentos estavam separados. Você os reuniu.']},
 12:{choice:'Instante',hint:'Por um momento, parece que alguma coisa aconteceu duas vezes.',title:'O instante repetido',task:'Interaja no centro durante três pulsos diferentes. Cada pulso fica aberto por 2s a cada 4s. Elimine as ameaças.',mode:'pulse',count:2,verbs:['SUSTENTAR O INSTANTE'],lines:['O mesmo instante se repetiu. Você encontrou três aberturas.','Você esperou o pulso mudar antes de tocar de novo.','A repetição cessou depois da terceira abertura.']},
 13:{choice:'Distância',hint:'O outro lado parece perto demais. Talvez seja só uma impressão.',title:'As bordas soltas',task:'Costure as três bordas na ordem I → II → III e elimine as ameaças.',mode:'sequence',count:2,verbs:['COSTURAR BORDA I','COSTURAR BORDA II','COSTURAR BORDA III'],lines:['As bordas se fecharam na ordem em que você as tocou.','Você encontrou a sequência entre as três bordas.','A passagem deixou de se desfazer quando a última borda cedeu.']},
 14:{choice:'Presença',hint:'Você sente que não está sozinho. Algo ali parece esperar.',title:'Quem ficou para trás',task:'Mantenha o Peregrino vivo por pelo menos 12s e elimine as três ameaças. Aproxime-se dos inimigos para interceptá-los.',mode:'protect',count:3,verbs:[],lines:['O Peregrino atravessou vivo. Você ficou entre ele e as ameaças.','A presença indefesa saiu da fissura depois da luta.','Desta vez, ninguém ficou preso daquele lado.']},
 15:{choice:'Mudança',hint:'A sensação escapa sempre que você tenta reconhecê-la.',title:'A distância muda',task:'Ocupe os círculos na sequência: perto → longe → perto. Permaneça 1,5s em cada um e elimine as ameaças.',mode:'adapt',count:2,verbs:['PERTO I','LONGE','PERTO II'],lines:['Você mudou de distância conforme os círculos se alteravam.','O lugar seguro mudou. Você mudou com ele.','Perto, longe, perto de novo. Você acompanhou as mudanças.']},
 16:{choice:'Fragmentos',hint:'Coisas dispersas parecem fazer parte de algo que você ainda não enxerga.',title:'O mecanismo partido',task:'Repare três peças. Interaja e permaneça a até 2m da peça por 2s; afastar-se interrompe o reparo. Elimine as ameaças.',mode:'repair',count:3,verbs:['REPARAR PEÇA I','REPARAR PEÇA II','REPARAR PEÇA III'],lines:['Você recompôs as três peças no meio da perturbação.','O mecanismo voltou a responder depois do último reparo.','Cada peça exigiu que você parasse por um instante.']},
 17:{choice:'Reflexo',hint:'Algo acompanha seus movimentos, um pouco além do que seus olhos alcançam.',title:'O reflexo armado',task:'Enfrente uma manifestação resistente. Depois da vitória, recolha a resposta deixada no centro.',mode:'duel',count:1,verbs:['RECOLHER RESPOSTA'],lines:['O reflexo caiu. A resposta ficou onde ele estava.','Você enfrentou a manifestação até ela perder a forma.','A lâmina do reflexo parou. Você recolheu o que restou.']},
 18:{choice:'Impulso',hint:'Uma inquietação passa por você. Ficar parado parece estranho.',title:'O caminho da corrente',task:'Atravesse os três condutores andando e percorra pelo menos 12m dentro da área. Elimine as ameaças. Saltos não preenchem o percurso.',mode:'route',count:2,verbs:['CONDUTOR I','CONDUTOR II','CONDUTOR III'],lines:['A corrente acompanhou o caminho que você percorreu.','Você ligou os três pontos com o próprio movimento.','O percurso ficou completo quando você passou pelo último condutor.']},
 19:{choice:'Sinais',hint:'Em meio ao ruído, um detalhe prende sua atenção.',title:'O sinal entre os ruídos',task:'Observe qual vestígio tem luz firme e interaja com ele. Os outros oscilam; uma escolha errada pode atrair uma ameaça adicional. Elimine as ameaças.',mode:'read',count:1,verbs:['LER VESTÍGIO I','LER VESTÍGIO II','LER VESTÍGIO III'],lines:['Você encontrou o sinal que permanecia firme.','Entre os vestígios, aquele sinal não oscilava.','O sinal certo continuou aceso até você alcançá-lo.']},
 20:{choice:'Silêncio',hint:'Há um ponto onde tudo parece distante, até o som dos seus passos.',title:'O vazio nas bordas',task:'Sele três vazamentos. Interaja e fique próximo por 2s, sem inimigos a até 2,5m do selo. A aproximação de uma ameaça interrompe. Elimine os hostis.',mode:'seal',count:2,verbs:['SELAR VAZAMENTO I','SELAR VAZAMENTO II','SELAR VAZAMENTO III'],lines:['Os três vazamentos cessaram depois que você os selou.','Você abriu espaço na luta para conter cada vazamento.','A última borda parou de consumir o que havia perto dela.']}
};
function trialJournal113(){const a=awakening103(),records=(a.journal113||[]).slice(-6).reverse();if(!records.length)return '';let h='<div class="sec">O QUE VOCÊ TESTEMUNHOU</div>';for(const r of records){const spec=TRIALS113[r.ci];if(spec)h+=row(spec.title,spec.lines[r.variant%3]+(a.total>=3?' · '+CLASSES[r.ci].n:''),'Investigação '+r.number)}return h}
function trialChapter113(total){return total===1?'Você sentiu a passagem responder à sua ação. Ainda não há uma explicação.':total===2?'Isso aconteceu de novo. Você reconhece a sensação, mesmo que a fissura se manifeste de outra forma.':total===3?'A mudança permanece depois que a fissura fecha. Você pode desenvolver os caminhos que experimentou. O Narrador reconhece a mudança, mas não sabe de onde ela vem.':''}
function trialLayout113(p,mode){for(let turn=0;turn<16;turn++){const rot=turn*Math.PI/8,spots=Array.from({length:3},(_,i)=>{const a=rot+i*Math.PI*2/3,r=mode==='adapt'?(i===1?6:2.5):4.5;return {x:p.x+Math.sin(a)*r,z:p.z+Math.cos(a)*r}}),foes=Array.from({length:3},(_,i)=>{const a=rot+(i+.5)*Math.PI*2/3;return {x:p.x+Math.sin(a)*6.5,z:p.z+Math.cos(a)*6.5}});if([...spots,...foes,{x:p.x,z:p.z}].every(q=>freeAt(q.x,q.z,.65)&&los(p.x,p.z,q.x,q.z)))return {spots,foes}}return null}
function inspectFissure103(){const a=awakening103(),p=a.pending;if(!p||L.mode!=='world'||player.dead||Math.hypot(player.x-p.x,player.z-p.z)>5||AR103.trial)return;let h='<div class="guide93"><strong>A PASSAGEM AINDA RESPONDE</strong><p>'+(['Algo permaneceu depois do fechamento. Você percebe várias formas de se aproximar.','A sensação voltou. Você pode repetir a experiência ou tentar outra resposta.','Você reconhece a fissura. Ela ainda pode responder de formas diferentes.'][Math.min(2,a.total)] )+'</p><p>Alguma dessas sensações chama sua atenção. De qual você se aproxima?</p></div>';for(const c of RARE103.filter(c=>c.ready)){const s=TRIALS113[c.id];h+=row(s.choice,s.hint,btn('Aproximar-se','awtrial',c.id))}openModal('FISSURA PERSISTENTE',h)}
function startTrial103(ci){const a=awakening103(),p=a.pending,s=TRIALS113[ci];if(!p||!s||L.mode!=='world'||player.dead||Math.hypot(player.x-p.x,player.z-p.z)>5||AR103.trial)return false;const layout=trialLayout113(p,s.mode);if(!layout){toast('As bordas estão obstruídas. A fissura permanece para outra aproximação.');return false}closeModal();const t={v113:true,region:L,pendingId:p.id,ci,x:p.x,z:p.z,t:0,step:0,done:[],nodes:[],walk:0,lastBeat:-1,safe:(a.total+ci)%3,variant:(a.points[ci]||0)%3,targets:[],ringAt:0};AR103.trial=t;for(const q of layout.foes.slice(0,s.count))t.targets.push(spawnKind(kindsFor(p.rank)[0].k,q.x,q.z,p.rank,{aggro:true,noExpLoot:true,aw103:true}));if(ci===17){const e=t.targets[0];e.hp*=1.8;e.maxhp=e.hp}if(ci===7||ci===14){t.helper=spawnShadow({n:ci===7?'Vestígio Guardião':'Peregrino da Fissura'},p.x,p.z);t.helper.awTrial=true;if(ci===14){Object.assign(t.helper,{guardianTrial108:true,shadow:false,short:'Peregrino'});t.helper.hp=t.helper.maxhp=Math.max(player.maxhp,t.targets.reduce((n,e)=>n+e.dmg,0)*8)}}const center=['pulse','duel'].includes(s.mode);for(let i=0;i<s.verbs.length;i++){const q=center?p:layout.spots[i],node={type:'trial113',x:q.x,z:q.z,r:2,label:'F · '+s.verbs[i],hidden:false,trial113:t,index113:i,use:()=>trialInteract113(t,i)};t.nodes.push(node);L.inter.push(node)}fxRing(p.x,p.z,0xc2a2ff,8,1);toast('<b>[FISSURA]</b> '+s.title+'. '+s.task+' Permaneça no círculo de 8m. Sair ou morrer interrompe a tentativa, mas permite tentar de novo.',6000);return true}
function trialInteract113(t,i){if(AR103.trial!==t||t.region!==L||player.dead||paused)return false;const n=t.nodes[i],s=TRIALS113[t.ci];if(!n||t.done.includes(i)||Math.hypot(player.x-n.x,player.z-n.z)>=2||!los(player.x,player.z,n.x,n.z))return false;
 if(s.mode==='pulse'){if(t.step>=3)return false;const beat=Math.floor(t.t/4);if(t.t%4>=2||beat===t.lastBeat){toast('Espere o próximo pulso claro.');return false}t.lastBeat=beat;t.step++;}
 else if(s.mode==='sequence'){if(i!==t.step){toast('Comece pela borda '+['I','II','III'][t.step]+'.');return false}t.done.push(i);t.step++;}
 else if(s.mode==='repair'||s.mode==='seal'){t.channel={i,progress:0};return true}
 else if(s.mode==='duel'){if(t.targets.some(e=>!e.dead)){toast('O reflexo ainda está armado.');return false}t.done.push(i);t.step=1}
 else if(s.mode==='read'){if(i!==t.safe){toast('Este vestígio oscila. Procure a luz firme.');if(!t.mistake){t.mistake=true;const p=awakening103().pending,q=t.nodes[t.safe];t.targets.push(spawnKind(kindsFor(p.rank)[0].k,q.x,q.z,p.rank,{aggro:true,noExpLoot:true,aw103:true}))}return false}t.done.push(i);t.step=1}
 else if(s.mode==='route'||s.mode==='adapt'){toast(s.task);return false}
 else{t.done.push(i);t.step=t.done.length}fxRing(n.x,n.z,0x8ef0bf,1.5,.6);return true}
function trialReady113(t){const s=TRIALS113[t.ci];if(!s||t.t<12||t.targets.some(e=>!e.dead)||player.dead||L!==t.region||Math.hypot(player.x-t.x,player.z-t.z)>8)return false;if(s.mode==='protect')return !!t.helper&&!t.helper.dead;if(s.mode==='route')return t.done.length===3&&t.walk>=12;if(s.mode==='duel'||s.mode==='read')return t.step>=1;return t.step>=3}
function trialWalk113(d){const t=AR103.trial;if(t?.v113&&t.ci===18&&t.region===L&&!player.dead&&Math.hypot(player.x-t.x,player.z-t.z)<=8){t.walk+=Math.max(0,d);for(const n of t.nodes)if(!t.done.includes(n.index113)&&Math.hypot(player.x-n.x,player.z-n.z)<1.6&&los(player.x,player.z,n.x,n.z))t.done.push(n.index113);t.step=t.done.length}}
function trialUpdate113(t,dt){if(player.dead||L!==t.region||L.mode!=='world'||Math.hypot(player.x-t.x,player.z-t.z)>8||t.ci===14&&t.helper?.dead){finishTrial103(false);return}t.t+=dt;const s=TRIALS113[t.ci];if(s.mode==='adapt'&&t.step<3){const n=t.nodes[t.step];if(Math.hypot(player.x-n.x,player.z-n.z)<1.6&&los(player.x,player.z,n.x,n.z)){t.hold=(t.hold||0)+dt;if(t.hold>=1.5){t.done.push(t.step++);t.hold=0}}else t.hold=0}if(t.channel){const ch=t.channel,n=t.nodes[ch.i],blocked=Math.hypot(player.x-n.x,player.z-n.z)>=2||!los(player.x,player.z,n.x,n.z)||s.mode==='seal'&&enemies.some(e=>!e.dead&&Math.hypot(e.x-n.x,e.z-n.z)<2.5);if(blocked){t.channel=null;toast('Concentração interrompida. Interaja para tentar novamente.')}else{ch.progress+=dt;if(ch.progress>=2){t.done.push(ch.i);t.step=t.done.length;t.channel=null}}}
 for(const n of t.nodes){n.hidden=t.done.includes(n.index113)||(s.mode==='pulse'&&t.step>=3);n.label='F · '+s.verbs[n.index113]+(s.mode==='read'?(n.index113===t.safe?' · LUZ FIRME':' · OSCILANDO'):s.mode==='pulse'?(t.t%4<2?' · PULSO ABERTO':' · AGUARDE'):'')}
 if(t.t>=t.ringAt){t.ringAt=t.t+.7;fxRing(t.x,t.z,0xc2a2ff,8,.8);for(const n of t.nodes)if(!n.hidden){const active=s.mode==='read'?n.index113===t.safe:s.mode==='sequence'||s.mode==='adapt'?n.index113===t.step:s.mode==='pulse'?t.t%4<2:true;fxRing(n.x,n.z,active?0x8ef0bf:0x806090,1.2,.8)}}if(trialReady113(t))finishTrial103(true)}
function trialHud113(t){const s=TRIALS113[t.ci],hostiles=t.targets.filter(e=>!e.dead).length,progress=s.mode==='protect'?'Peregrino '+Math.ceil(Math.max(0,t.helper.hp)/t.helper.maxhp*100)+'%':s.mode==='route'?t.done.length+'/3 condutores · '+Math.min(12,Math.floor(t.walk))+'/12m':s.mode==='pulse'?t.step+'/3 pulsos · '+(t.t%4<2?'ABERTO':'AGUARDE'):s.mode==='read'?['I','II','III'][t.safe]+' · luz firme':s.mode==='duel'?(hostiles?'Vença o reflexo':'Recolha a resposta'):t.step+'/3 etapas';return ' · '+s.title+' · '+progress+' · '+hostiles+' ameaças'+(t.t<12?' · '+Math.ceil(12-t.t)+'s':'')+(t.channel?' · concentração '+Math.floor(t.channel.progress/2*100)+'%':'')}
function finishTrial103(success){const t=AR103.trial;if(!t)return false;if(success&&t.v113&&!trialReady113(t))return false;const a=awakening103();if(success&&t.v113&&(!a.pending||a.pending.id!==t.pendingId))success=false;for(const e of t.targets){e.dead=true;e.gone=true;if(e.m)scene.remove(e.m.root)}if(t.helper){t.helper.dead=true;scene.remove(t.helper.m.root)}if(t.region)t.region.inter=t.region.inter.filter(n=>n.trial113!==t);AR103.trial=null;AR103.zone=null;if(!success){toast('A tentativa foi interrompida. Seu progresso anterior permanece e esta fissura pode ser investigada novamente.');return false}if(!a.pending)return false;a.pending=null;a.total++;a.points[t.ci]=(a.points[t.ci]||0)+1;if(t.v113){a.journal113=Array.isArray(a.journal113)?a.journal113:[];a.journal113.push({ci:t.ci,variant:t.variant,number:a.total});a.journal113=a.journal113.slice(-30);const spec=TRIALS113[t.ci];logNews('<b>[NARRADOR]</b> '+spec.lines[t.variant],'dialogue');const chapter=trialChapter113(a.total);if(chapter)logNews('<b>[A FISSURA]</b> '+chapter,'story')}narratorEvent105(a.total===3?'awakening':'trial');store.set('pds2_profile',profile);saveRun();toast((a.total<3?'<b>[FISSURA]</b> Investigação concluída. Você guardou esta experiência.':'<b>[DESPERTAR]</b> Caminho de '+CLASSES[t.ci].n+' desenvolvido.')+(a.total===3?' Volte à cidade: Personagem → Despertar.':''),6000);return true}
