// Optional choices are independent of automatic class and rank passives.
function passiveSlots263(){return ResourceBalance263.slots.filter(n=>Math.max(Number(profile?.maxLevel111)||0,Number(run?.level)||1)>=n).length}
function selectedPassives263(){const valid=new Set(ResourceBalance263.passives.map(p=>p.id));return [...new Set(Array.isArray(profile?.optionalPassives263)?profile.optionalPassives263:[])].filter(id=>valid.has(id)).slice(0,passiveSlots263())}
function hasPassive263(id){return selectedPassives263().includes(id)}
function passiveCost263(kind,cost){return cost>0&&hasPassive263(kind+'_saver')?Math.max(1,Math.ceil(Math.round(cost*.9*1e8)/1e8)):cost}
function vigorRate263(){return ResourceBalance263.vigorRate*(hasPassive263('vigor_flow')?1.15:1)}
function resourceWait263(kind){return kind==='vigor'?(hasPassive263('vigor_focus')?1:ResourceBalance263.vigorWait):(hasPassive263('fury_hold')?9:ResourceBalance263.furyWait)}
function passiveGuard263(actor,damage){return actor===player&&actor.hp>actor.maxhp*.8&&hasPassive263('ready_guard')?damage*.92:damage}
function passiveDamage263(enemy,damage,options){return options.fromPlayer&&options.skillHit&&!options.pet&&!options.passive&&enemy.hp<=enemy.maxhp*.35&&hasPassive263('opportunist')?damage*1.08:damage}
function togglePassive263(id){if(!canRedistribute())return false;const def=ResourceBalance263.passives.find(p=>p.id===id);if(!def)return false;const ids=selectedPassives263(),i=ids.indexOf(id);if(i>=0)ids.splice(i,1);else{if(ids.length>=passiveSlots263()){toast('Todos os espaços estão ocupados. Retire uma passiva primeiro.');return false}ids.push(id)}profile.optionalPassives263=ids;saveRun();return true}
function passiveRows263(){const chosen=selectedPassives263(),slots=passiveSlots263(),can=canRedistribute();let h='<div class="sec">PASSIVAS À ESCOLHA · '+chosen.length+'/'+slots+'</div><div class="sysline">Um espaço nos níveis 10, 30 e 60. O maior nível alcançado mantém os espaços. Escolha até três; troque gratuitamente na cidade. Trocar não restaura recursos.<br>Descontos arredondam o custo para cima; técnicas gratuitas continuam gratuitas.</div>';for(const p of ResourceBalance263.passives){const active=chosen.includes(p.id);h+=row(p.n,p.d,can&&(active||chosen.length<slots)?btn(active?'Retirar':'Equipar','passive263',p.id):'<b>'+(active?'Ativa':slots===0?'Nível 10':can?'Sem espaço':'Troque na cidade')+'</b>')}return h}
