// Local trust and recovery. Existing global karma remains a legacy benefit/penalty.
function regionState116(c){profile.regions116=profile.regions116||{};let r=profile.regions116[c.id];if(!r){r=profile.regions116[c.id]={name:c.name,trust:0,damage:(profile.abandon||{})[c.id]?20:0,history:[]};if(r.damage)r.history.push('A região ainda enfrenta prejuízos de uma invasão anterior.')}return r}
function regionDiscount116(r){return r.trust>=80?15:r.trust>=50?10:r.trust>=20?5:0}
function regionStanding116(r){return r.trust>=80?'Referência local':r.trust>=50?'Pessoa de confiança':r.trust>=20?'Bem recebido':'Ainda se conhecendo'}
function regionEvent116(c,trust,damage,reason){const r=regionState116(c);r.trust=clamp(r.trust+trust,0,100);r.damage=clamp(r.damage+damage,0,20);r.history.push(reason);r.history=r.history.slice(-8);if(!r.damage)delete (profile.abandon||{})[c.id];store.set('pds2_profile',profile);logNews('<b>['+safeText(c.name)+']</b> '+safeText(reason),'story');return r}
function regionPortal116(g){if(!g||g.regional116||!Number.isFinite(g.x)||!Number.isFinite(g.z))return false;g.regional116=true;const c=nearestCity(g.x,g.z).c;regionEvent116(c,2,-2,'Um portal da região foi fechado por você. Confiança +2; a pressão sobre o abastecimento diminuiu.');return true}
function regionLine116(c){const r=regionState116(c);if(r.damage)return pick(['Ainda estamos repondo o que perdemos na invasão.','As entregas estão curtas por aqui. Toda ajuda faz diferença.','A cidade continua aberta. A recuperação é que vai levar tempo.']);if(r.trust>=50)return pick(['Seu nome já é conhecido por aqui. Obrigado por voltar.','A guarnição separou suprimentos para quem nos ajuda.','Quando falam dos últimos dias, alguém sempre lembra da sua ajuda.']);if(r.trust>=20)return pick(['Lembro do que você fez pela região.','É bom ver um rosto que já ajudou por aqui.','O pessoal anda falando bem de você.']);return ''}
function regionSummary116(c){const r=regionState116(c),d=regionDiscount116(r);return row('Sua relação com '+safeText(c.name),regionStanding116(r)+' · confiança '+r.trust+'/100.<br>'+(d?'Desconto local de '+d+'% em armas, armaduras e poções comuns.':'A partir de 20 de confiança, as lojas oferecem 5% de desconto.')+(r.damage?'<br>Abastecimento afetado: acréscimo local de '+r.damage+'%.':''),btn('Ver região','region116',0))}
function regionCost116(){return {gold:500*(Math.max(0,profile.rank||0)+1),cry:8}}
function regionAid116(){if(L.mode!=='world'||player.dead||!inCity(player.x,player.z)||L.inv||L.siege)return false;const c=nearestCity(player.x,player.z).c,r=regionState116(c),k=regionCost116();if(cityFallen(c)||r.damage<=0||run.gold<k.gold||run.res.cry.reduce((a,b)=>a+b,0)<k.cry)return false;run.gold-=k.gold;let need=k.cry;for(let i=0;i<run.res.cry.length&&need;i++){const n=Math.min(need,run.res.cry[i]);run.res.cry[i]-=n;need-=n}regionEvent116(c,3,-5,'Você entregou materiais para a recuperação. Confiança +3; acréscimo de abastecimento reduzido em até 5 pontos.');saveRun();return true}
function regionSupply116(){if(L.mode!=='world'||player.dead||!inCity(player.x,player.z)||L.inv||L.siege)return false;const c=nearestCity(player.x,player.z).c,r=regionState116(c);if(cityFallen(c)||r.trust<50||r.damage||r.supplyDay===todayKey())return false;r.supplyDay=todayKey();run.pots=(run.pots||0)+2;store.set('pds2_profile',profile);saveRun();toast('<b>['+safeText(c.name)+']</b> A guarnição entregou duas poções.');return true}
function regionView116(){if(L.mode!=='world'){toast('Consulte as regiões ao voltar ao mundo.');return}view=regionView116;const c=nearestCity(player.x,player.z).c,r=regionState116(c),k=regionCost116(),local=inCity(player.x,player.z)&&!cityFallen(c)&&!L.inv&&!L.siege;let h='<div class="guide93"><strong>'+safeText(c.name)+'</strong><p>'+regionStanding116(r)+' · confiança '+r.trust+'/100.</p><p>Cada cidade lembra da ajuda recebida em sua região. A reputação da Ordem continua separada.</p></div>';h+=row('Comércio local','Desconto por confiança: '+regionDiscount116(r)+'%.<br>Acréscimo por abastecimento: '+r.damage+'%. Aplicados às armas, armaduras e poções comuns; outros descontos existentes continuam valendo.','');h+=row('Apoio da guarnição','Duas poções por dia nesta cidade. Requer 50 de confiança e abastecimento recuperado.',btn(r.supplyDay===todayKey()?'Recebido hoje':'Receber suprimentos','supply116',0,local&&r.trust>=50&&!r.damage&&r.supplyDay!==todayKey()));if(r.damage)h+=row('Ajudar na recuperação',fmt(k.gold)+' ouro e '+k.cry+' cristais de qualquer rank. Reduz o acréscimo em 5 pontos e concede 3 de confiança.',btn('Entregar materiais','aid116',0,local&&run.gold>=k.gold&&run.res.cry.reduce((a,b)=>a+b,0)>=k.cry));h+='<div class="sec">MEMÓRIA DA REGIÃO</div>';h+=r.history.length?r.history.slice().reverse().map(x=>row(safeText(x),'','')).join(''):'<div class="sysline">Sua história por aqui ainda está começando.</div>';h+='<div class="sysline">Fechar portais da região: +2 de confiança e menos 2 pontos de escassez. Participar de uma defesa vitoriosa: +12 e abastecimento recuperado. Vencer um cerco: +15. Evoluir a cidade: +5. Reconstruir: +20. Descontos aos 20/50/80 pontos: 5%/10%/15%. Recuperação e suprimentos exigem estar na cidade, fora de uma invasão ou cerco.</div>';openModal('REGIÃO',h)}
function regionInvasion116(I,won){if(I.regionalDone116)return;I.regionalDone116=true;if(won)regionEvent116(I.c,I.helped116?12:0,-20,I.helped116?'Você participou da defesa vitoriosa. Confiança +12; abastecimento recuperado.':'Os defensores venceram a invasão. O abastecimento foi recuperado.');else regionEvent116(I.c,0,20,'A invasão prejudicou o abastecimento. Os preços locais têm acréscimo de até 20% durante a recuperação. Sua confiança não diminuiu.');}
