/* v308 (Ian): 200 criaturas no Bestiário.
   Cada uma das 61 espécies ganha duas versões:
   - FENDIDA (_f): tocada pela Fenda — cristais brotando do corpo, olhos brilhando, mais forte. Nas Fendas e perto de portais.
   - ABISSAL (_a): atravessou a Fenda e voltou — corpo escurecido de vazio, fragmentos orbitando, aura roxa. Rara: Fendas vermelhas, corrompidas e de rank alto.
   Lobo, Aranha, Gigante e Yeti usam os modelos feitos no Blender (v307) como versão Fendida.
   Os 13 chefes entram no Bestiário com lore própria. */
(function(){
const T=THREE,BASES=Object.keys(KINDS).filter(k=>!KINDS[k].fendido&&!/_f$|_a$/.test(k));
const BLENDER={lobo:'lobofendido',aranha:'tecela',gigante:'colosso',yeti:'yeticorrompido'};
const fem=n=>{const w=n.split(' ')[0];return /a$/.test(w)&&!/^(Lula|Alpaca)$/.test(w)?true:/^(Lula|Alpaca|Gosma|Abelha|Aranha|Vespa|Caveira|Máscara)/.test(w)};
const nameF=n=>n+(fem(n)?' Fendida':' Fendido'),nameA=n=>n+' Abissal';
const low=s=>s?s.charAt(0).toLowerCase()+s.slice(1):s;
function loreF(k,n){const L=(Bestiary294.LORE[k]||['Criatura pouco estudada.','Desconhecido.','Desconhecido.']);return [n+': '+low(L[0]).replace(/\.$/,'')+', mas cristais de mana romperam a pele e os olhos agora brilham com a luz da Fenda.','Além do que comia antes ('+low(L[1]).replace(/\.$/,'')+'), precisa engolir mana das fendas abertas para não se despedaçar.',L[2].replace(/\.$/,'')+'. A Fenda deixou a criatura mais agressiva: ataca qualquer coisa que carregue mana, inclusive caçadores.']}
function loreA(k,n){const L=(Bestiary294.LORE[k]||['Criatura pouco estudada.','Desconhecido.','Desconhecido.']);return [n+': '+low(L[0]).replace(/\.$/,'')+' — mas esta atravessou a Fenda e voltou do outro lado. O corpo é de vazio e fragmentos de cristal orbitam em volta.','Não come mais. Consome a luz e o calor do lugar onde está; as plantas murcham por onde passa.','Não pertence mais a este mundo: obedece a um chamado que vem do outro lado da Fenda e só aparece onde ela é mais funda.']}
for(const k of BASES){const B=KINDS[k];if(!B)continue;
 const fk=k+'_f',ak=k+'_a';
 if(BLENDER[k]&&KINDS[BLENDER[k]]){KINDS[fk]={...KINDS[BLENDER[k]],baseKind:k,variant:'f',fendido:true};Bestiary294.LORE[fk]=Bestiary294.LORE[BLENDER[k]]}
 else{KINDS[fk]={...B,n:nameF(B.n),hp:Math.round(B.hp*1.6),dmg:Math.round(B.dmg*1.35),xp:Math.round((B.xp||10)*1.8),rk:Math.max(1,B.rk??0),bio:undefined,baseKind:k,variant:'f',fendido:true};Bestiary294.LORE[fk]=loreF(k,KINDS[fk].n)}
 KINDS[ak]={...B,n:nameA(B.n),hp:Math.round(B.hp*2.4),dmg:Math.round(B.dmg*1.7),xp:Math.round((B.xp||10)*3),rk:Math.max(3,B.rk??0),bio:undefined,baseKind:k,variant:'a',fendido:true,scale:(B.scale||1)*1.15};Bestiary294.LORE[ak]=loreA(k,KINDS[ak].n)}
/* as 4 do Blender (lobofendido etc.) viram aliases das versões _f: saem do Bestiário como espécie separada */
for(const k in BLENDER){const id=BLENDER[k];if(KINDS[id])KINDS[id].alias308=k+'_f'}
/* ---------- visual ---------- */
const MUT=(window.Fendidos307&&Fendidos307.MUT)||{campos:['',0x9b5cff,0x66f0ff]};
function bones(root){const out=[];root.traverse(o=>{if(o.isBone&&/spine|back|torso|body|chest|abdomen|neck|head/i.test(o.name))out.push(o)});return out}
function crystalMat(col){if(window.Crystal310)return Crystal310.mat(col);return new T.MeshToonMaterial({name:'FendaCristal',color:col,emissive:col,emissiveIntensity:.9})}
function dressF(e,col){const root=e.m.root,b=new T.Box3().setFromObject(root),H=Math.max(.4,b.max.y-b.min.y);const bs=bones(root);const m=crystalMat(col);const n=5+Math.floor(Math.random()*3);
 for(let i=0;i<n;i++){const c=new T.Mesh(new T.ConeGeometry(H*.06,H*.22,5),m);if(bs.length){const bone=bs[i%bs.length];const s=bone.getWorldScale(new T.Vector3()).x||1;c.scale.setScalar(1/s);c.position.set((Math.random()-.5)*.3*H/s,H*.08/s,(Math.random()-.5)*.3*H/s);c.rotation.set((Math.random()-.5),(Math.random()-.5),(Math.random()-.5));bone.add(c)}else{c.position.set((Math.random()-.5)*H*.4,H*(.75+Math.random()*.2),(Math.random()-.5)*H*.4);c.rotation.set((Math.random()-.5)*.8,0,(Math.random()-.5)*.8);(e.m.body||root).add(c)}}
 try{e.m.root.traverse(o=>{if(o.isMesh&&o.material&&o.material.name!=='FendaCristal'&&o.material.color){o.material=o.material.clone();o.material.color.lerp(new T.Color(0x3a2466),.3)}})}catch(_){}}
function dressA(e,col){const root=e.m.root,b=new T.Box3().setFromObject(root),H=Math.max(.4,b.max.y-b.min.y);
 e.m.root.traverse(o=>{if(o.isMesh&&o.material&&o.material.color){if(o.material.name==='FendaCristal')return;o.material=o.material.clone();o.material.color.lerp(new T.Color(0x0e0818),.78);if(o.material.emissive)o.material.emissive.setHex(0x12061e)}});
 const orb=new T.Group();orb.position.y=H*.6;const m=crystalMat(col);for(let i=0;i<4;i++){const s=new T.Mesh(new T.OctahedronGeometry(H*.08,0),m);const a=i/4*Math.PI*2;s.position.set(Math.cos(a)*H*.55,0,Math.sin(a)*H*.55);orb.add(s)}root.add(orb);e.orb308=orb;
 const ring=new T.Mesh(new T.RingGeometry(H*.45,H*.55,32),(window.Shaders312?Shaders312.energy(col,.8):new T.MeshBasicMaterial({color:col,transparent:true,opacity:.6,depthWrite:false})));ring.rotation.x=-Math.PI/2;ring.position.y=.08;root.add(ring);
 try{const l=new T.PointLight(col,1.4,8,1.8);l.position.y=H*.7;root.add(l)}catch(_){}}
function dress(e){const K=KINDS[e.kind];if(!K||!K.variant||e.dress308)return;e.dress308=1;let bio='campos';try{bio=biomeAt(e.x,e.z)}catch(_){}const M=MUT[bio]||MUT.campos;
 if(K.variant==='f'){if(!BLENDER[K.baseKind])dressF(e,M[1]);else{try{Fendidos307.mutate(e)}catch(_){}}if(M[0]&&!BLENDER[K.baseKind])e.name=K.n+' '+M[0]}
 else dressA(e,0x8a3cff)}
setInterval(()=>{try{for(const e of enemies){if(e.orb308&&!e.dead){e.orb308.rotation.y+=.04}if(!e.dress308&&KINDS[e.kind]?.variant)dress(e)}}catch(_){}},50);
/* ---------- onde aparecem: troca a espécie pela versão dela ---------- */
if(window.Fendidos307){/* desliga a troca aleatória da v307 (agora é pela mesma espécie) */}
const sk0=spawnKind;spawnKind=function(k,x,z,gr,extra){try{if(!(extra&&(extra.noFendido||extra.boss||extra.rival))&&KINDS[k]&&!KINDS[k].variant&&!KINDS[k].fendido){const inDun=typeof L!=='undefined'&&L.mode==='dungeon';const g=inDun?L.gate:null;const deep=g&&(g.red||g.corrupt299||(g.rank||0)>=4);let near=false;if(!inDun&&typeof gates!=='undefined')near=gates.some(q=>!q.dead&&Math.hypot(q.x-x,q.z-z)<60);
 const r=Math.random();let v=null;if(inDun){if(deep&&r<.05)v='_a';else if(r<.14)v='_f'}else if(near&&r<.08)v='_f';
 if(v){const id=(v==='_f'&&BLENDER[k]&&MON.list[BLENDER[k]])?k+'_f':k+v;if(KINDS[id]&&(!KINDS[id].mon||MON.list[KINDS[id].mon])){const e=sk0.call(this,id,x,z,gr,{...(extra||{}),noFendido:true});return e}}}}catch(_){}return sk0.call(this,k,x,z,gr,{...(extra||{}),noFendido:true})};
/* ---------- chefes no Bestiário ---------- */
const BOSSLORE={'Cavaleiro Carmesim':['Cavaleiro que jurou proteger uma cidade que já não existe; a armadura vermelha nunca enferruja.','Não come. Vive do juramento que fez.','Guarda o salão de uma Fenda como se fosse o portão do seu antigo reino; o golpe dele faz o chão tremer.'],'Lich Ancestral':['Mago que trocou a própria morte por mil anos de estudo.','Alimenta-se das almas presas no grimório que carrega.','Ergue os mortos da masmorra para ganhar tempo enquanto conjura.'],'Berserker Rubro':['Guerreiro que se perdeu na própria fúria até virar parte da Fenda.','Sangue e batalha.','Fica mais forte a cada golpe que recebe; nunca recua.'],'General Esqueleto':['Comandante de um exército que morreu numa única noite.','Nada; é a disciplina que o mantém de pé.','Dá ordens aos esqueletos e muda a formação no meio da luta.'],'O Rei Oco':['Um rei sem corpo, só a coroa e o manto flutuando sobre o trono vazio.','Consome a lealdade de quem se ajoelha diante dele.','Quem olha para dentro do manto vê o próprio medo.'],'Rei Demônio Vharok':['Soberano das profundezas, coroado de chifres e brasas.','Medo, fogo e reinos inteiros.','Abre fendas menores ao redor e chama os seus para a batalha.'],'Dragão do Caos Kaelthys':['Dragão que nasceu dentro da própria Fenda; cada escama tem uma cor diferente.','Engole portais inteiros.','Muda de elemento no meio da luta: fogo, gelo, raio e vazio.'],'Rainha Aranha Nhyssa':['Rainha das aranhas, com uma coroa de ovos de cristal.','A mana de tudo que fica preso nas suas teias gigantes.','Cobre a arena de teias e manda as filhas atacarem primeiro.'],'Colosso de Gelo Ymrak':['Colosso feito de uma geleira que ganhou vontade própria.','O calor de tudo que se aproxima.','Congela o chão e prende os pés de quem luta contra ele.'],'Arconte da Destruição':['Um dos quatro Arcontes, pedaços do Arquiteto que ganharam forma.','A existência das coisas ao redor.','Tudo que toca vira pó; é o primeiro dos Soberanos.'],'Arconte do Gelo Eterno':['Arconte que guarda o inverno que nunca termina.','O tempo: perto dele tudo fica mais lento.','Congela o próprio ar; quem para de se mover vira estátua.'],'Arconte das Pragas':['Arconte que espalha doença por onde passa.','A vida que apodrece.','Cada praga que ele lança cria monstros novos no caminho.'],'Arconte das Feras':['Arconte que comanda todas as feras selvagens.','A caça.','Chama matilhas inteiras e luta ao lado delas, como um líder.']};
const bossNames=Object.keys(BOSSLORE);
function bossSeen(){profile.bossSeen308=profile.bossSeen308||{};return profile.bossSeen308}
const kill308=killEnemy;killEnemy=function(e){const eligible=e&&!e.dead&&e.isBoss&&!e.noExpLoot&&!e.ally&&!e.statue;const r=kill308.apply(this,arguments);if(eligible&&e.dead){const nm=(e.name||'').replace(/^\[[^\]]*\]\s*/,'');const key=bossNames.find(b=>nm.includes(b));if(key){const S=bossSeen(),old=S[key]?.kills||0;S[key]={seen:1,kills:old+1};store.set('pds2_profile',profile);if(!old)Bestiary294.corner('CHEFE DERROTADO','<b>'+key+'</b> · '+Object.values(S).filter(s=>s.kills>0).length+' de '+bossNames.length+' chefes','#ff6a5a')}}return r};
/* Bestiário: total e seção de chefes; esconde as espécies que são aliases */
const bv0=bestView;bestView=function(){bv0();try{const mb=document.getElementById('mb');if(!mb)return;const S=bossSeen();let h='<div class="sec">CHEFES · '+Object.values(S).filter(s=>s.kills>0).length+' DE '+bossNames.length+'</div>';for(const b of bossNames){const s=S[b];h+=s&&s.kills>0?row('<b>'+b+'</b>','Vencido '+(s.kills||0)+'×<br><b>Descrição:</b> '+BOSSLORE[b][0]+(s.kills>=1?'<br><b>Alimentação:</b> '+BOSSLORE[b][1]+'<br><b>Comportamento:</b> '+BOSSLORE[b][2]:'<br><span style="color:var(--dim)">🔒 Vença para conhecer mais.</span>'),''):row('<span style="color:var(--dim)">??? · chefe não descoberto</span>','','')}mb.insertAdjacentHTML('beforeend',h)}catch(_){}};
window.Variants308={BASES,total:()=>Object.keys(KINDS).filter(k=>!KINDS[k].alias308).length+bossNames.length,bossNames};
})();
