const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8');
function extract(n){const m=new RegExp('function\\s+'+n+'\\s*\\([^)]*\\)').exec(src);assert(m,n);let b=src.indexOf('{',m.index),d=0,q=null,e=false;for(let i=b;i<src.length;i++){let c=src[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;if(c==='}'&&!--d)return src.slice(m.index,i+1)}}




let saves=0;const c={time:20,player:{x:0,z:0,dead:false,maxhp:100},run:{loot:{},gold:0,res:{cry:Array(10).fill(0)}},profile:{},bossE:null,enemies:[],allies:[],L:{mode:'dungeon',gate:{rank:1,seed:42},rooms:[{wx:0,wz:0},{wx:10,wz:0},{wx:20,wz:0}]},toast(){},saveRun(){saves++},closeModal(){},fxRing(){},floater(){},fmt:String,freeAt:()=>true,scene:{remove(){}},spawnKind(k,x,z,gr,o){const e={...o,x,z,hp:100,maxhp:100,dmg:10,m:{root:{}},gold:10,xp:10};c.enemies.push(e);return e},hazard(){return {}},animChibi(){},moveEnt(e,x,z){e.x+=x;e.z+=z},los:()=>true};vm.createContext(c);vm.runInContext(src.slice(src.indexOf('const EXP_TYPES='),src.indexOf('function useLamp()')),c);vm.runInContext(src.slice(src.indexOf('const GEAR_RUNES='),src.indexOf('function lootRune')),c);for(const n of ['mulberry32','lootRune','rankPortalCount','recordRankPortal'])vm.runInContext(extract(n),c);c.store={set(){}};
const types=new Set();for(let seed=1;seed<200;seed++)types.add(c.expeditionType({seed}));assert.equal(types.size,4);for(const key of ['secret','inverse','time','giant','custom','double'])assert.equal(c.expeditionType({seed:1,[key]:true}),null);assert.equal(c.expeditionType({seed:1,expType:'standard'}),null);
const gate={seed:4,rank:1,expType:'rupture'},s=c.expState(gate);assert.strictEqual(c.expState(gate),s);assert.equal(s.foci.length,3);assert.deepEqual(JSON.parse(JSON.stringify(s)),JSON.parse(JSON.stringify(c.expState({seed:4,expType:'rupture'}))));
function setup(type){c.L={mode:'dungeon',gate:{rank:1,seed:12,expType:type},rooms:[{wx:0,wz:0},{wx:10,wz:0},{wx:20,wz:0}],bossDead:false};const s=c.expState(c.L.gate);c.L.expedition={s,nodes:[],timer:99,challenge:null,patrolRooms:[1,2],patrol:0};c.enemies=[];c.player.x=c.player.z=0;c.bossE=null;return s}
function node(kind,index,room=1){const n={kind,index,room,x:0,z:0,r:3,grp:{visible:true,rotation:{}}};c.L.expedition.nodes.push(n);return n}
let st=setup('rupture');st.foci[0]={kind:1,status:'active',room:1};node('focus',0);assert(c.expAction('focus',0,'purify'));assert.equal(c.enemies.length,3);assert(!c.expAction('focus',0,'purify'));c.expeditionUpdate(6);assert.equal(c.L.expedition.challenge.t,6);c.player.x=8;c.expeditionUpdate(1);assert.equal(c.L.expedition.challenge.t,0);c.player.x=0;c.enemies.forEach(e=>e.dead=true);c.expeditionUpdate(12);assert.equal(st.foci[0].status,'purified');assert.equal(c.run.loot['Essência de Duplicação'].n,3);assert.equal(c.lootRune('Essência de Duplicação'),'reprise');assert(!c.expAction('focus',0,'purify'));c.expBossReward();const total=Object.values(c.run.loot).reduce((n,m)=>n+m.n,0);c.expBossReward();assert.equal(Object.values(c.run.loot).reduce((n,m)=>n+m.n,0),total);
st=setup('rupture');st.foci=[{kind:0,status:'active',room:1}];assert.equal(c.expeditionDamage({room:1},100),60);c.bossE={expShield:40};assert.equal(c.expeditionDamage(c.bossE,30),0);assert.equal(c.bossE.expShield,10);assert.equal(c.expeditionDamage(c.bossE,30),20);
st=setup('extract');node('deposit',2);node('beacon',0);assert(c.expAction('deposit',2,'collect'));assert(c.expAction('deposit',2,'collect'));assert.equal(c.expCargoWeight(st),6);assert(!c.expAction('deposit',2,'collect'));assert(!c.recordRankPortal(1));assert(c.expAction('beacon',0,'send'));c.expeditionUpdate(12);assert(c.L.expedition.challenge);c.enemies.forEach(e=>e.dead=true);c.expeditionUpdate(.1);assert.equal(st.sent,6);assert.equal(st.cargo.length,0);assert.equal(c.run.loot['Coração de Cristal'].n,2);assert(c.L.bossDead);assert(c.recordRankPortal(1));assert(!c.recordRankPortal(1));st.cargo=['ore','heart'];const secured=c.run.loot['Coração de Cristal'].n;c.expAbandon();assert.equal(st.cargo.length,0);assert.equal(c.run.loot['Coração de Cristal'].n,secured);
st=setup('extract');node('beacon',0);st.cargo=['heart','ore','core'];st.instability=8;assert(c.expAction('beacon',0,'stabilize'));assert.deepEqual(Array.from(st.cargo),['heart','core']);assert.equal(st.instability,5);assert(c.expAction('beacon',0,'drop:heart'));assert.equal(c.expCargoWeight(st),2);c.player.x=20;assert(!c.expAction('beacon',0,'send'));c.player.x=0;c.L.special={};assert(!c.expAction('beacon',0,'send'));
st=setup('hunt');node('nest',0);node('bait',0);node('trap',0);c.enemies=[{room:1}];assert(!c.expAction('nest',0,'nest'));c.enemies[0].dead=true;assert(c.expAction('nest',0,'nest'));assert(c.expAction('bait',0,'bait'));assert(!c.expAction('bait',0,'bait'));assert(c.expAction('trap',0,'trap'));c.bossE={x:0,z:0,hp:100,maxhp:100,m:{root:{position:{set(){}}}}};assert(c.expAction('trap',0,'lure'));assert(!st.bait);assert(c.expHuntMove(c.bossE,.1));assert(st.trapSpent[0]);assert.equal(c.L.expedition.trapHold,3);assert(!c.expAction('trap',0,'trap'));
c.L.grid={W:5,H:5,CS:1,ox:0,oz:0,cells:new Uint8Array([1,1,0,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1])};const route=c.expPath({x:.5,z:.5},{x:4.5,z:.5});assert(route.length>4);assert(route.every(p=>c.L.grid.cells[Math.floor(p.z)*5+Math.floor(p.x)]===1));assert.deepEqual(route[route.length-1],{x:4.5,z:.5});
console.log('PASS 3 expedition types and classic portals, seeded state, focus purification/distance/unique reward, ward shield, extraction capacity/deposits/defense/delivery/rank clear/loss separation, stabilization, hunts/nests/bait/traps, grid path around walls');
vm.runInContext(extract('applyGearRuneHit'),c);c.gearRuneCount=k=>k==='reprise'?2:0;c.player.runeHits=0;const echoTarget={hp:1000,x:0,z:0};for(let i=0;i<3;i++)c.applyGearRuneHit(echoTarget,100);assert(!echoTarget.basicDots);c.applyGearRuneHit(echoTarget,100);assert.equal(echoTarget.basicDots.reprise.d,40);assert.equal(echoTarget.basicDots.reprise.t,1);for(let i=0;i<4;i++)c.applyGearRuneHit(echoTarget,50);assert.equal(echoTarget.basicDots.reprise.d,40);echoTarget.dead=true;c.applyGearRuneHit(echoTarget,100);assert.equal(c.player.runeHits,8);console.log('PASS rune echo triggers every fourth living-target basic hit, scales per piece and retains strongest pending impact');
