const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync('game.html','utf8');let checks=0;const test=(n,fn)=>{fn();checks++;console.log('PASS '+n)};
function extract(name,src=html){const start=src.indexOf('function '+name+'(');assert(start>=0,name);const open=src.indexOf('){',start)+1;let depth=0,q='',esc=false;for(let i=open;i<src.length;i++){const c=src[i];if(q){if(esc)esc=false;else if(c==='\\')esc=true;else if(c===q)q='';continue}if(c==='\''||c==='"'||c==='`'){q=c;continue}if(c==='{')depth++;else if(c==='}'&&--depth===0)return src.slice(start,i+1)}throw Error(name)}
const noop=()=>{},ctx={console,Math:Object.create(Math),window:{},profile:{cls:0},run:{level:55,equip:{},skl:{}},L:{gate:null},time:20};vm.createContext(ctx);const code=s=>vm.runInContext(s,ctx);const load=n=>code(extract(n));
code(html.match(/^const RAR=.*$/m)[0]);code(html.match(/^const RARW=.*$/m)[0]);code(html.match(/^const AFX=.*$/m)[0]);
Object.assign(ctx,{EQUIP_LABEL:{w:'Arma',a:'Armadura',h:'Elmo',g:'Luvas',b:'Botas'},TIERN:['F'],WEAPON_LOOT_KINDS:['sword'],EQUIP_SLOTS:['w','a','h','g','b'],equipmentBaseValueBalance:(t,s,r)=>100+r,pick:a=>a[0],unl:()=>false,wpick:a=>a.at(-1),SETS:[],CURSES:[]});load('rollAff2');load('makeItem');load('rollItem');
test('8 rarities, Primeva last, dedicated normal/boss weight',()=>assert.deepEqual(code('[RAR.length,RAR[7].n,RARW.length,RARWB.length,RARW[7]>0,RARWB[7]>0]').join('|'),'8|Primeva|8|8|true|true'));
test('all 40 slot/rarity combinations generate valid items',()=>{for(const slot of ctx.EQUIP_SLOTS)for(let r=0;r<8;r++){const i=ctx.makeItem(slot,0,r);assert.equal(i.rar,r);assert.equal(i.aff.length,r===7?3:r>=4?2:r>=2?1:0);assert(Number.isFinite(i.value))}});
test('Primeva is reachable through real loot path',()=>{assert.equal(ctx.rollItem(0,true).rar,7);assert.equal(ctx.rollItem(0,false,2).rar,7)});
Object.assign(ctx,{player:{hp:50,maxhp:100,maxmp:100,maxsh:20,resourceRest258:false},hasT:()=>false,hasPassive263:()=>false,hasAff:()=>false,Mana258:{regeneration:()=>10},pManaRegen281:()=>.25});load('naturalRegen');
test('mana regeneration readout matches +25% bonus',()=>assert.equal(ctx.naturalRegen().mp,12.5));
test('no-cure suppresses safe-zone and passive natural healing',()=>{ctx.hasAff=()=>true;ctx.hasT=()=>true;assert.equal(ctx.naturalRegen(ctx.player,true).hp,0);ctx.hasAff=()=>false;ctx.hasT=()=>false});
const kit=fs.readFileSync('tools/kit111-runtime.js','utf8');Object.assign(ctx,{MAGIC_CLS:[3,5,6,7,8,9,10,11,12,13,14,16,18,19,20,22],CLASSES:Array.from({length:25},()=>({sk:[],n:'Class'})),hurtEnemy:(e,d,x,z,o)=>o});ctx.CLASSES[8].elem='fogo';code(extract('skillHitOptions318',kit));code(extract('kitHit111',kit));
test('kit area damage keeps source element and damage type',()=>{const o=ctx.kitHit111({},100,{sourceClass:8});assert.equal(o.elem300,'fogo');assert.equal(o.dtype281,'mag');assert.equal(ctx.kitHit111({},100,{sourceClass:0}).dtype281,'phy')});
Object.assign(ctx,{resourceCombat258:noop,cons:()=>0,hasClassPassive:()=>false,critChance:()=>0,pCritDmg281:()=>0,mobDefVal296:()=>200,pPenVal296:()=>0,curDType281:'phy',identityHitDamage:(e,d)=>d,passiveDamage263:(e,d)=>d,passive297:(e,d)=>d,titleHitBonus:()=>0,expeditionDamage:(e,d)=>d});ctx.player.stealth=0;load('hurtEnemy');
test('defense can negate damage without minimum-one leak',()=>{const e={hp:100,maxhp:100,stun:0};assert.equal(ctx.hurtEnemy(e,100,0,0,{fromPlayer:true}),0);assert.equal(e.hp,100)});
test('friendly targets and invalid damage are rejected',()=>{assert.equal(ctx.hurtEnemy({ally:true},100,0,0),0);assert.equal(ctx.hurtEnemy({},NaN,0,0),0)});
// Load the real v316 ability extension with a deterministic combat adapter.
const hits=[];Object.assign(ctx,{enemies:[],newRun:noop,useSkill:()=>true,skillEffect102:noop,skillHasDamage:()=>true,runSkill:s=>{ctx.legacyCast=s},skillDamage:()=>100,skillAnim155:noop,fxRing:noop,sfx:noop,los:()=>true,freeAt:()=>true,martialState260:()=>({vigor:100,fury:50}),furyMaxR260:()=>100,resourceWait263:()=>6,resourceCost260:()=>10,waveFwd:noop,learnedSkills:()=>[],hurtEnemy:(e,d,x,z,o={})=>{hits.push({d,o});e.hp-=d;if(e.hp<=0)e.dead=true;return d},paused:false});ctx.CLASSES.forEach(c=>c.sk=[{col:1},{},{}]);ctx.player={x:0,z:0,face:0,hp:100,maxhp:100,mp:0,maxmp:100,dmg:100,skills:[]};ctx.window=ctx;code(fs.readFileSync('tools/classes316.js','utf8'));
test('each new class has ten skills and unique stable IDs',()=>{for(const c of [21,22,23,24]){assert.equal(ctx.CLASSES[c].sk.length,10);assert.equal(new Set(ctx.CLASSES[c].sk.slice(3).map(x=>x.skillId)).size,7)}});
test('alternate mark uses actual physical/magic damage, not main class',()=>{const e={hp:1000,maxhp:1000,alternate316:{until:30,last:'phy'}};ctx.hurtEnemy(e,100,0,0,{fromPlayer:true,basicClass:0,dtype281:'mag'});assert.equal(hits.at(-1).d,135);assert.equal(e.alternate316.last,'mag')});
test('scar also empowers original Berserker attack',()=>{ctx.player.class316={scar:{until:30,hp:140}};ctx.runSkill({sourceClass:24,pow:2});assert.equal(ctx.legacyCast.pow,6);assert.equal(ctx.player.class316.scar,null)});
test('new melee spells carry explicit magical damage',()=>{ctx.enemies=[{x:1,z:0,hp:1000,maxhp:1000,r:.5}];ctx.runSkill(ctx.CLASSES[22].sk[3]);assert.equal(hits.at(-1).o.dtype281,'mag')});
test('three basic hits trigger Dízimo mana restoration and consume mark',()=>{const e={x:1,z:0,hp:1000,maxhp:1000,tithe316:{until:30,hits:0}};ctx.player.mp=0;for(let i=0;i<3;i++)ctx.hurtEnemy(e,10,0,0,{fromPlayer:true,basicClass:0,dtype281:'phy'});assert.equal(ctx.player.mp,12);assert.equal(e.tithe316,null)});
// Actual elemental rule module, independent of the main-class selection.
Object.assign(ctx,{UNLOCK:[],mktView:noop,extraActions:noop,bestStats293:()=>'',mobAttr281:()=>({prof:'Equilibrado'}),biomeAt:()=> 'neve',floater:noop,BIO_N:{neve:'Neve'}});code(fs.readFileSync('tools/elem300.js','utf8'));
test('fire weakness +30%; ice resistance -30%; level gate respected',()=>{const e={kind:'test',x:0,z:0};assert.equal(ctx.elemMul300(e,100,{fromPlayer:true,elem300:'fogo',skillHit:true}),130);assert.equal(ctx.elemMul300(e,100,{fromPlayer:true,elem300:'gelo',skillHit:true}),70);ctx.run.level=1;assert.equal(ctx.elemMul300(e,100,{fromPlayer:true,elem300:'fogo'}),100);ctx.run.level=55});

load('passive297');ctx.profile.cls=0;ctx.player.hp=ctx.player.maxhp=100;ctx.player.mp=0;
test('learned Arcane Blade passive works after class change, only in melee',()=>{ctx.hasClassPassive=i=>i===22;ctx.passive297({hp:100},20,{fromPlayer:true,basicClass:0});assert.equal(ctx.player.mp,2);ctx.passive297({hp:100},20,{fromPlayer:true,basicClass:4,ptype300:'arrow'});assert.equal(ctx.player.mp,2)});
test('learned Berserker and Lancer damage passives remain active',()=>{ctx.hasClassPassive=i=>i===23||i===24;ctx.player.hp=50;const e={hp:100};assert.equal(ctx.passive297(e,100,{fromPlayer:true}),144);assert.equal(ctx.passive297(e,100,{fromPlayer:true}),120)});
test('Monk chain expires between isolated attacks',()=>{ctx.hasClassPassive=i=>i===21;ctx.enemies=[];ctx.player.combo297=0;for(let t=1;t<=5;t++){ctx.time=t*2;ctx.passive297({hp:100},10,{fromPlayer:true,basicClass:0})}assert.equal(ctx.player.combo297,1)});
console.log(JSON.stringify({passed:checks}));
