const fs=require('fs'),vm=require('vm'),assert=require('assert');const src=fs.readFileSync(__dirname+'/../game.html','utf8');
function extract(n){const m=new RegExp('function\\s+'+n+'\\s*\\([^)]*\\)').exec(src);assert(m,n);let b=src.indexOf('{',m.index),d=0,q=null,e=false;for(let i=b;i<src.length;i++){let c=src[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;if(c==='}'&&!--d)return src.slice(m.index,i+1)}}
const city={id:'aster'},c={Math,Number,TOPR:8,profile:{},run:{gold:100000,res:{core:[50,50,0,0,0,0,0,0,0]},level:40},player:{x:0,z:0},L:{mode:'world'},inCity:()=>true,nearestCity:()=>({c:city}),cityL:()=>5,cityFallen:()=>false,store:{set(){}},saveRun(){},toast(){},rankOf:()=>4,clamp:(n,a,b)=>Math.max(a,Math.min(b,n))};vm.createContext(c);for(const n of ['defenseLevel','defenseCost','defenseGuards','defenseRange','upgradeDefense','spawnCityDefenders'])vm.runInContext(extract(n),c);let passed=0;function test(n,fn){fn();console.log('PASS '+n);passed++}
test('old saves retain base defense',()=>{assert.equal(c.defenseGuards(city),3);assert.equal(c.defenseRange(city),60)});
test('upgrade consumes exact gold and low-rank cores first',()=>{assert(c.upgradeDefense('guards'));assert.equal(c.run.gold,98500);assert.equal(c.run.res.core[0],42);assert.equal(c.run.res.core[1],50);assert.equal(c.defenseGuards(city),4)});
test('independent cities, persistence and level cap',()=>{c.profile=JSON.parse(JSON.stringify(c.profile));assert.equal(c.defenseLevel(city,'guards'),1);assert.equal(c.defenseLevel({id:'other'},'guards'),0);assert(c.upgradeDefense('guards'));assert(c.upgradeDefense('guards'));const g=c.run.gold;assert(!c.upgradeDefense('guards'));assert.equal(c.run.gold,g);assert.equal(c.defenseGuards(city),6)});
test('invalid, insufficient, siege and outside-city attempts spend nothing',()=>{const g=c.run.gold;c.L.siege={};assert(!c.upgradeDefense('watch'));c.L.siege=null;c.L.mode='dungeon';assert(!c.upgradeDefense('watch'));c.L.mode='world';assert(!c.upgradeDefense('bad'));c.run.gold=0;assert(!c.upgradeDefense('watch'));c.run.gold=g;c.cityL=()=>1;assert(!c.upgradeDefense('watch'));c.cityL=()=>5;assert.equal(c.run.gold,g)});
test('watch extends real turret range and defenders match purchased count',()=>{assert(c.upgradeDefense('watch'));assert.equal(c.defenseRange(city),68);const spawned=[];c.makeHunterAlly=(...args)=>spawned.push(args);assert.equal(c.spawnCityDefenders(city,10,10),6);assert.equal(spawned.length,6);assert(spawned.every(x=>x[3]===true));assert(src.includes('n.d<defenseRange(n.c)'));assert(src.includes('spawnCityDefenders(c,c.x+Math.cos(a)*38'))});
test('equipment remains one merchant and services have no floating labels',()=>{assert(src.includes("s.id==='arm'?'defense':s.id"));assert(src.includes("s.id===(id==='arm'?'wep':id)"));assert(src.includes("kind:'vendor',noLabel:true"));assert(src.includes("btn('Armaduras','equipshop','arm'"));assert(src.includes('function makeCitySign(){return new THREE.Group()}'))});
console.log(passed+' scenarios passed');
