const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8'),base=fs.readFileSync(__dirname+'/verify-v95.cjs','utf8');eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')));
let random=.99,saved=0,vestiges=0;
const obj=()=>({position:{set(){},y:0},rotation:{},add(){},remove(){},visible:true});
const c={Math:Object.assign(Object.create(Math),{random:()=>random}),profile:{cls:0,rank:0,progress80:1,rankTalents:[]},run:{items:[],equip:{},gold:0,level:1,pots:0,res:{core:Array(10).fill(0)}},player:{x:0,z:0,hp:100,maxhp:100},L:{mode:'world',gate:{rank:0},inter:[],group:obj()},enemies:[],EQUIP_SLOTS:['w','a','h','g','b'],EQUIP_LABEL:{w:'Arma',a:'Armadura',h:'Elmo',g:'Luvas',b:'Botas'},CLASSES:[{wep:'sword'}],RARW:[60,28,10,2,.45,.09,.012],RARWB:[0,50,38,12,3.5,.7,.1],RAR:Array.from({length:7},(_,i)=>({n:String(i),c:'#fff'})),TIERN:Array.from({length:10},(_,i)=>'T'+i),RANKS:Array.from({length:10},(_,i)=>({id:String(i)})),GR:Array.from({length:10},()=>({gold:1,hp:1,dmg:1,xp:1})),PRICE:[150,700,2400,7000,18000,50000,140000,400000,700000,1200000],WATK:[10,20,30,40,50,60,70,80,90,100],SHV:[20,40,60,80,100,120,140,160,180,200],priceMul:()=>1,rankOf:()=>c.profile.rank,rollAff2:()=>[],pick:a=>a[0],wpick:()=>({i:0}),unl:()=>false,toast(){},fmt:String,store:{set(){}},saveRun(){saved++},refreshStats(){},affTxt:()=>'',gearRuneText:()=>'',inCity:()=>true,addOrderRep:n=>c.rep=(c.rep||0)+n,rnd:a=>a,floater(){},fxBurst(){},beep(){},hasT:()=>false,ENV:{ok:false},THREE:{Group:class{constructor(){Object.assign(this,obj())}},Mesh:class{constructor(){Object.assign(this,obj())}}},mesh:obj,geo:()=>({}),toonS:()=>({}),glowS:()=>({}),setTimeout(){},storyEv(){},finishTowerStory:()=>false,towerCap:()=>1e9,makeSign:obj,bigText(){},sfx(){},rememberVestige103(){vestiges++},dropLoot(){},hasClassPassive:()=>false,gainXp(){},dprog(){},shadowXp(){},bestKill(){},npcEv(){},canArise:()=>false,guildBonus:()=>0,titleB:()=>({}),qev(){},demandKill(){},npcHas:()=>false,weaponXp(){}};
c.narratorEvent105=()=>{};vm.createContext(c);
for(const n of ['gearQ','itemAtk','itemSh','equipFactor','equipmentShopPrice','makeItem','rollItem','statTxt','addItem','equipmentBagRoom','buyEquipment','equipBagItem','dropEquipment','dungeonFloorAt','dungeonEquipmentChance','dropDungeonEquipment','openChest','addChest','finishFirstEquipment','ensureRankProgress','towerMilestones','rankPoints','towerClear','killEnemy'])vm.runInContext(extract(n),c);
// Every slot/tier: prices match 10x old purchase prices; low rank can buy and equip.
for(const slot of c.EQUIP_SLOTS)for(let t=0;t<10;t++){
 const expected=c.PRICE[t]*c.equipFactor(slot)*10;c.run.items=[];c.run.equip={};c.run.gold=expected-1;
 assert.equal(c.equipmentShopPrice(slot,t),expected);assert(!c.buyEquipment(slot,t));assert.equal(c.run.gold,expected-1);
 c.run.gold++;assert(c.buyEquipment(slot,t));assert.equal(c.run.gold,0);const it=c.run.items[0];assert.equal(it.value,Math.round(c.PRICE[t]*c.equipFactor(slot)*.4));assert(c.dropEquipment(it.uid,slot));assert.equal(c.run.equip[slot].tier,t);
}
c.priceMul=()=>.8;assert.equal(c.equipmentShopPrice('w',0),1200);c.priceMul=()=>1;
for(const t of [-1,10,1.5])assert(!c.buyEquipment('w',t));assert(!c.buyEquipment('x',0));c.run.items=Array(24).fill({});c.run.gold=1e8;assert(!c.buyEquipment('w',9));assert.equal(c.run.gold,1e8);c.run.items=[];
// Drops retain source rank even for rank F; depth raises minimum rarity and real stats.
c.L={mode:'dungeon',gate:{rank:6},floors:{current:0},grid:{oz:0,CS:1}};
const loot=[0,1,2].map(d=>c.rollItem(6,false,d));assert(loot.every(it=>it.tier===6));assert.deepEqual(loot.map(it=>it.rar),[0,1,2]);assert(c.itemAtk(loot[2])>c.itemAtk(loot[1])&&c.itemAtk(loot[1])>c.itemAtk(loot[0]));
const plain={slot:'w',tier:6,rar:0};assert.equal(c.itemAtk({...plain,depth105:2}),105);assert.equal(c.itemSh({slot:'a',tier:6,rar:0,depth105:2}),210);
const restored=JSON.parse(JSON.stringify(loot[2]));assert.equal(c.itemAtk(restored),c.itemAtk(loot[2]));assert(c.statTxt(restored).includes('50%'));
for(let d=0;d<3;d++)for(const elite of [false,true]){
 const e={z:d*40+10,gr:6,elite},chance=elite?.35+.1*d:.08+.04*d;assert.equal(c.dungeonEquipmentChance(e),chance);
 random=chance;const count=c.run.items.length;assert(!c.dropDungeonEquipment(e));assert.equal(c.run.items.length,count);random=chance-.00001;assert(c.dropDungeonEquipment(e));assert.equal(c.run.items.at(-1).depth105||0,d);
}
for(const e of [{isBoss:true},{noExpLoot:true},{rival:true}])assert.equal(c.dungeonEquipmentChance({...e,z:0}),0);
c.L.special={kind:'tower'};assert.equal(c.dungeonEquipmentChance({z:0}),0);c.L.special={kind:'job'};assert.equal(c.dungeonEquipmentChance({z:0}),0);delete c.L.special;c.L.mode='world';assert.equal(c.dungeonEquipmentChance({z:0}),0);c.L.mode='dungeon';
// Guaranteed floor treasures: no mimic, minimum Rare/Epic/Legendary and source depth.
random=.99;c.run.items=[];for(let d=0;d<3;d++){c.openChest(0,d*40+10,6,d===2,d<2?{depth:d}:null);const it=c.run.items.at(-1);assert.equal(it.rar,d+1);assert.equal(it.depth105||0,d)}assert.equal(c.run.items.length,3);
delete c.L.floors;c.L.special={kind:'tower'};random=0;c.openChest(0,0,6,false);assert.equal(c.run.items.length,3);random=.99;c.openChest(0,0,6,true);assert.equal(c.run.items.length,4);delete c.L.special;
c.L.group=obj();c.L.inter=[];c.enemies=[{room:3}];const chest=c.addChest(0,0,6,false,{room:3,depth:1});const count=c.run.items.length;chest.use();assert(!chest.opened);assert.equal(c.run.items.length,count);c.enemies[0].dead=true;chest.use();assert(chest.opened);assert.equal(c.run.items.length,count+1);chest.use();assert.equal(c.run.items.length,count+1);
// Actual kill flow awards once and excludes no-loot copies, tower and world.
c.L.mode='dungeon';c.run.kills=0;c.enemies=[];random=0;const mob={gr:6,z:0,x:0,xp:1};const before=c.run.items.length;c.killEnemy(mob);assert(mob.dead);assert.equal(c.run.items.length,before+1);c.killEnemy(mob);assert.equal(c.run.items.length,before+1);const calls=vestiges;c.killEnemy({noExpLoot:true});assert.equal(c.run.items.length,before+1);assert.equal(vestiges,calls+1);
// Tower uses high-water mark: retroactive bonus, no passive points or nonboss chests.
c.profile.rank=1;c.profile.towerBest=29;c.profile.rankTalents=['flow'];assert.equal(c.towerMilestones(),2);assert.equal(c.rankPoints(),0);c.L={mode:'dungeon',group:obj(),inter:[],exits:[],gate:{x:0,z:0}};c.enemies=[];
const stage={floor:30,gr:0,boss:true};c.towerClear(stage);assert.equal(c.profile.towerBest,30);assert.equal(c.rankPoints(),0);assert.equal(c.L.inter.filter(i=>i.type==='chest').length,0);const gold=c.run.gold;c.towerClear(stage);assert.equal(c.run.gold,gold);c.towerClear({floor:30,gr:0,boss:true});assert.equal(c.rankPoints(),0);c.towerClear({floor:35,gr:0,boss:false});assert.equal(c.rankPoints(),0);assert.equal(c.L.inter.filter(i=>i.type==='chest').length,0);c.profile=JSON.parse(JSON.stringify(c.profile));assert.equal(c.towerMilestones(),3);
// Real bonus pool includes legacy in world and dungeon without granting talent points.
Object.assign(c,{curseB:()=>({}),foodB:()=>({}),setB:()=>({}),affB:()=>({dmg:0,hp:0}),tierOf:()=>0,innB:()=>0,rkN:String,effB:t=>t<=0?t:3*t/(3+t)});vm.runInContext(extract('bonusPool'),c);
for(const mode of ['world','dungeon']){c.L.mode=mode;const bonus=c.bonusPool(),legacy=bonus.src.find(r=>r[0].startsWith('Legado da Torre'));assert.equal(legacy[1],.03);assert.equal(legacy[2],.03);assert(bonus.edmg>0);assert.equal(c.rankPoints(),0)}
// Tutorial accepts loot, rewards only on equip, once; old completion preserved.
c.profile.firstEquipment92={done:false};c.run.equip={};c.run.items=[c.makeItem('w',9,3)];c.run.trackObj='firstEquipment';assert(!c.finishFirstEquipment());assert(c.equipBagItem(c.run.items[0].uid));assert(c.profile.firstEquipment92.done);assert.equal(c.rep,10);assert(!c.finishFirstEquipment());assert.equal(c.rep,10);
assert(src.includes("if(variant==='floors'){for(const r of rooms.filter(r=>r.floorEnd&&r.floor<2))addChest"));assert(src.includes('L.closeT=60'));assert(!extract('bestInBag').includes('pr>=it.tier'));assert(!extract('gearPicker').includes('rankOf()>=it.tier'));assert(!extract('bagItems').includes('pr<it.tier'));
console.log('PASS 50 purchase/equip combinations, exact prices/discounts, unchanged resale, invalid/full-bag rejection, unrestricted source rank, persisted depth stats, drop boundaries/exclusions, guaranteed/guarded/idempotent treasures, real kill flow, tower own bonus without talent points, record/repeat protections, loot tutorial and 60s escape retained');
