const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8');
function extract(n){const m=new RegExp('function\\s+'+n+'\\s*\\([^)]*\\)').exec(src);assert(m,n);let b=src.indexOf('{',m.index),d=0,q=null,e=false;for(let i=b;i<src.length;i++){let c=src[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;if(c==='}'&&!--d)return src.slice(m.index,i+1)}}
const notices=[],c={run:{},toast:t=>notices.push(t),fmt:String,beep(){}};vm.createContext(c);for(const n of ['lootTotal','sellMonsterLoot','mktView'])vm.runInContext(extract(n),c);
c.run={gold:123,loot:{Garra:{n:7,v:3},Reliquia:{n:2,v:30,b:true}},res:{cry:Array.from({length:10},(_,i)=>i*11+3),core:Array.from({length:10},(_,i)=>i*7+2)},items:[{uid:1}],equip:{w:{uid:2}}};const original=JSON.stringify(c.run.res),gear=JSON.stringify([c.run.items,c.run.equip]);assert.equal(c.lootTotal(),81);assert(c.sellMonsterLoot());assert.equal(c.run.gold,204);assert.equal(c.lootTotal(),0);assert.equal(JSON.stringify(c.run.res),original);assert.equal(JSON.stringify([c.run.items,c.run.equip]),gear);assert(!c.sellMonsterLoot());assert.equal(c.run.gold,204);assert.equal(notices.length,1);c.run=JSON.parse(JSON.stringify(c.run));assert.equal(JSON.stringify(c.run.res),original);assert(!c.sellMonsterLoot());delete c.run.loot;assert(!c.sellMonsterLoot());assert.equal(c.run.gold,204);
Object.assign(c,{view:null,CORE_P:[],CRY_P:[],GR:Array.from({length:10},(_,i)=>({id:i})),RANKS:Array.from({length:10},(_,i)=>({c:'white',id:i})),sellP:()=>100,arrow:()=>'',rankOf:()=>0,row:(...a)=>a.join(' '),btn:(label,action)=>'['+action+':'+label+']',petRows:()=>'',affRow:()=>'',unl:()=>false,lockMsg:()=>'',L:{},openModal:(title,body)=>{c.html=body}});
c.mktView();assert(!c.html.includes('[sellall:'));assert(c.html.includes('Vender estes'));c.run.loot={Garra:{n:7,v:3}};c.mktView();assert(c.html.includes('[sellall:VENDER ESPÓLIOS · 21 ouro]'));assert(!c.html.includes('VENDER TUDO'));assert(c.html.includes('Cristais de mana e núcleos mágicos ficam guardados'));
assert(src.includes("if(a==='sellall'){if(!sellMonsterLoot())return}"));assert(!extract('sellMonsterLoot').includes('run.res'));
console.log('PASS bulk sale includes monster loot only; exact gold; all 10 ranks of crystals and cores preserved; equipment preserved; repeat/empty sale no-op; save roundtrip; displayed price excludes resources; resource-only inventory has no bulk-sale button; legacy sellall action routes to safe function.');
