const fs=require('fs'),vm=require('vm'),assert=require('assert');const src=fs.readFileSync(__dirname+'/../game.html','utf8');
function extract(n){const m=new RegExp('function\\s+'+n+'\\s*\\([^)]*\\)').exec(src);assert(m,n);let b=src.indexOf('{',m.index),d=0,q=null,e=false;for(let i=b;i<src.length;i++){let c=src[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;if(c==='}'&&!--d)return src.slice(m.index,i+1)}}
const c={Math,Number,console,time:10,profile:{},player:{maxmp:180,maxhp:100,hp:50,x:0,z:0,mp:100},run:{shadows:[]},allies:[],hasClassPassive:()=>false,scene:{remove(){}},fxBurst(){},toast(){},saveRun(){},floater(){},fxRing(){},hasAff:()=>false,L:{},clamp:(x,a,b)=>Math.max(a,Math.min(b,x))};vm.createContext(c);for(const n of ['summonCap','minionAllies','hurtAlly','shadowXp','savedSummons','restoreSummons','resolveEnemyStun','echoAttackMul','applyBasicAttackEffect','useSkill'])vm.runInContext(extract(n),c);let n=0;function test(label,fn){fn();console.log('PASS '+label);n++}
test('mana maximum controls capacity, summoner doubles extra slots',()=>{assert.equal(c.summonCap(),5);c.hasClassPassive=()=>true;assert.equal(c.summonCap(),8);c.player.maxmp=30;assert.equal(c.summonCap(),3);c.player.maxmp=180});
test('full army consumes no mana or cooldown',()=>{c.allies=Array.from({length:8},()=>({hp:1,life:1e9}));c.paused=false;c.player.dead=false;const sk={t:'summon',mp:20,cdT:0};c.useSkill(sk);assert.equal(c.player.mp,100);assert.equal(sk.cdT,0)});
test('dead eco remains owned, level and XP reset, can be recalled',()=>{const rec={n:'Guardião',lvl:12,xp:400,on:true};const a={hp:5,shadow:true,rec,m:{root:{}},x:0,z:0};c.run.shadows=[rec];c.hurtAlly(a,10);assert(a.dead);assert.equal(c.run.shadows.length,1);assert.equal(rec.lvl,0);assert.equal(rec.xp,0);assert.equal(rec.on,false)});
test('dead eco gains no XP; living level zero has nonzero threshold',()=>{const rec=c.run.shadows[0];c.allies=[{shadow:true,dead:true,rec}];c.shadowXp(1000);assert.equal(rec.lvl,0);rec.on=true;const a={shadow:true,dead:false,rec,x:0,z:0,maxhp:100,hp:100,dmg:10};c.allies=[a];c.shadowXp(100);assert.equal(rec.lvl,0);assert.equal(rec.xp,35);c.shadowXp(200);assert.equal(rec.lvl,1);assert.equal(rec.xp,25)});
test('summon save restores health, damage and giant without healing',()=>{c.allies=[{permanentSummon:true,summonKind:'skel',hp:23,maxhp:80,dmg:15,giant:true,buffT:2},{permanentSummon:true,dead:true,hp:0}];c.run.summons=JSON.parse(JSON.stringify(c.savedSummons()));assert.equal(c.run.summons.length,1);const restored=[];c.spawnSummon=(kind,x,z,life)=>{const a={maxhp:80,dmg:10,m:{body:{scale:{setScalar(){}}}}};restored.push(a);return a};c.restoreSummons();assert.equal(restored[0].hp,23);assert.equal(restored[0].dmg,15);assert(restored[0].giant)});
test('stun capped and cannot chain within three seconds',()=>{const e={stun:.9};c.resolveEnemyStun(e,0);assert.equal(e.stun,.3);assert.equal(e.stunResistUntil,13);c.time=11;e.stun=.9;c.resolveEnemyStun(e,0);assert.equal(e.stun,0);c.time=13;e.stun=.8;c.resolveEnemyStun(e,0);assert.equal(e.stun,.3);const boss={isBoss:true,stun:1};c.resolveEnemyStun(boss,0);assert.equal(boss.stun,0)});
test('necromancer only strengthens ecos on the marked target and expires',()=>{c.time=20;const e={hp:100};c.applyBasicAttackEffect(e,7,100);assert.equal(c.player.hp,50);assert.equal(c.echoAttackMul({shadow:true},e),1.2);assert.equal(c.echoAttackMul({shadow:false},e),1);c.time=24;assert.equal(c.echoAttackMul({shadow:true},e),1)});
test('summon cast fills vacancies without replacing or renewing living allies',()=>{Object.assign(c,{player:{...c.player,dmg:10,face:0,buff:0,maxmp:30},profile:{},run:{skl:{}},isMagic:()=>false,wxSkillMul:()=>1,statsBonus:()=>({skill:1}),setB:()=>({}),faceTarget:()=>null,skillFx(){},sfx(){},rnd:()=>0,TAU:Math.PI*2,freeAt:()=>true,saveRun(){}});const old=[{hp:10,maxhp:80,life:1e9},{hp:20,maxhp:80,life:1e9}];c.allies=[...old];c.spawnSummon=()=>{const a={hp:80,life:1e9};c.allies.push(a);return a};vm.runInContext(extract('runSkill'),c);c.runSkill({t:'summon',n:'Lobo',pow:2,col:0});assert.equal(c.allies.length,3);assert.equal(old[0].hp,10);assert.equal(old[1].hp,20);assert(!old[0].dead);assert(src.includes('if(!a.permanentSummon)a.life-=dt'));assert(src.includes('restoreSummons();'))});console.log(n+' scenarios passed');
