const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8'),base=fs.readFileSync(__dirname+'/verify-v95.cjs','utf8');eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')));
const obj=()=>({position:{set(x,y,z){Object.assign(this,{x,y,z})}},rotation:{},add(){}}),c={Uint8Array,Math,THREE:{Group:class{constructor(){Object.assign(this,obj())}},Mesh:class{constructor(){Object.assign(this,obj())}}},geo:()=>({}),mesh:obj,toonS:()=>({}),glowS:()=>({}),makeSign:obj,enemies:[],toast(){},fxRing(){},spawnKind(kind,x,z,rank,extra){const e={kind,x,z,rank,...extra,hp:100,maxhp:100,speed:2,gold:10};c.enemies.push(e);return e}};vm.createContext(c);for(const n of ['variantLayout103','coreDefenseLayout111','coreWaveSize111','setupCoreDefense','coreWave'])vm.runInContext(extract(n),c);
for(const flip of [.1,.9])for(let rank=0;rank<10;rank++){
 const map=c.variantLayout103('core',()=>flip),grid={...map,CS:2,ox:-map.W,oz:-map.H};const rooms=map.rooms.map((r,i)=>({...r,i,wx:grid.ox+(Math.floor(r.x+r.w/2)+.5)*2,wz:grid.oz+(Math.floor(r.y+r.h/2)+.5)*2}));
 c.L={grid,rooms,bossRoom:map.bi,G:{dmg:2},gate:{rank,red:true,aff:['armor','frenzy']},group:obj(),inter:[]};c.enemies=[];c.setupCoreDefense();const d=c.L.defense,r=rooms[map.bi];assert(d.core.z<r.wz-10);assert(d.front.z>r.wz+10);assert.equal(d.grp.position.z,d.core.z);assert.equal(c.L.inter[0].z,d.core.z);assert.equal(d.duration,60);assert.equal(d.core.hp,1200);
 const free=(x,z)=>{const gx=Math.floor((x-grid.ox)/2),gz=Math.floor((z-grid.oz)/2);return grid.cells[gz*grid.W+gx]===1};
 let total=0;for(let wave=1;wave<=4;wave++){const before=c.enemies.length;c.coreWave();const spawned=c.enemies.slice(before),expected=8+Math.floor(rank/2)+2*(wave-1);assert.equal(spawned.length,expected);total+=expected;for(const e of spawned){assert(e.z>d.core.z+20,'all invaders in front');assert(e.z>r.wz,'same side of arena');assert.equal(e.room,map.bi);assert(e.coreRaider&&e.aggro);assert.equal(e.hp,195);assert.equal(e.speed,3.25);assert(free(e.x,e.z));for(let t=0;t<=20;t++){const x=e.x+(d.core.x-e.x)*t/20,z=e.z+(d.core.z-e.z)*t/20;assert(free(x,z),'clear path to core')}for(const other of spawned)if(other!==e)assert(Math.hypot(e.x-other.x,e.z-other.z)>=2)}assert.equal(c.enemies.length,total)}assert.equal(c.enemies.length,44+4*Math.floor(rank/2));
}
assert.equal(c.coreWaveSize111(0,1),8);assert.equal(c.coreWaveSize111(0,4),14);assert.equal(c.coreWaveSize111(9,4),18);
console.log('PASS both arena orientations/all 10 ranks: core at rear, matching visual/interaction, 4 growing waves, 44–60 total invaders, front-only distinct walkable spawns, direct paths, red/affix scaling, 60s and core health preserved');
