const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8');
function extract(n){const m=new RegExp('function\\s+'+n+'\\s*\\([^)]*\\)').exec(src);assert(m,n);let b=src.indexOf('{',m.index),d=0,q=null,e=false;for(let i=b;i<src.length;i++){let c=src[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;if(c==='}'&&!--d)return src.slice(m.index,i+1)}}
const c={profile:{progress80:1,rank:0,cls:0,jobs:[0]},run:{level:15,gold:500},L:{mode:'world'},player:{x:0,z:0},inCity:()=>true,store:{set(){}},saveRun(){},styleTutorial(){},CLASSES:[{},{},{}],TOPR:8,GR:Array.from({length:10},(_,i)=>({lvl:i*10})),enemies:[]};vm.createContext(c);vm.runInContext(src.slice(src.indexOf('const RANK_TALENTS='),src.indexOf('function rankTalent(')),c);for(const n of ['ensureRankProgress','classSlotCount','rankTalent','rankPoints','chooseRankTalent','bounceBasic','classTraining','classTrainingReady','rankTrialReady','jobsOf','canLearnClass','learnClass'])vm.runInContext(extract(n),c);
assert.equal(c.classSlotCount(),1);c.profile.rank=1;assert.equal(c.classSlotCount(),2);c.profile.rank=5;assert.equal(c.classSlotCount(),6);c.profile={rank:0,cls:0,jobs:[0]};assert.equal(c.classSlotCount(),6);assert.equal(c.profile.progress80,1);
c.profile={progress80:1,rank:1,cls:0,jobs:[0]};assert(c.chooseRankTalent('bounce'));assert.equal(c.rankPoints(),0);assert(!c.chooseRankTalent('sweep'));c.profile.rank=3;assert(c.chooseRankTalent('bounce'));assert(c.chooseRankTalent('bounce'));c.profile.rank=4;assert(!c.chooseRankTalent('bounce'));assert(!c.chooseRankTalent('flow'));c.profile.rank=6;assert(c.chooseRankTalent('flow'));c.L.mode='dungeon';assert(!c.chooseRankTalent('volley'));c.L.mode='world';assert(!c.chooseRankTalent('bogus'));
c.profile=JSON.parse(JSON.stringify(c.profile));assert.equal(c.rankTalent('bounce'),3);assert.equal(c.rankTalent('flow'),1);
const a={x:0,z:0},b={x:2,z:0},d={x:4,z:0};c.enemies=[a,b,d];const shot={x:0,z:0,vx:0,vz:22,bounces:2,dmg:100,hit:new Set([a]),mesh:{rotation:{}},life:.1};assert(c.bounceBasic(shot));assert.equal(shot.dmg,70);assert.equal(shot.bounces,1);assert.equal(shot.vx,22);shot.hit.add(b);assert(c.bounceBasic(shot));assert.equal(shot.dmg,49);assert(!c.bounceBasic(shot));shot.bounces=2;shot.hit.add(d);assert(!c.bounceBasic(shot));
c.profile={progress80:1,rank:0,cls:0,jobs:[0],bossKills:1};assert(!c.learnClass(1));assert.equal(c.run.gold,500);c.profile.bossKills=2;assert(c.learnClass(1));assert.equal(c.run.gold,0);assert.deepEqual(Array.from(c.profile.jobs),[0,1]);assert(!c.learnClass(1));assert(!c.learnClass(2));assert.equal(c.classTraining().level,25);assert.equal(c.classTraining().gold,2000);
c.profile={rank:0,bossKills:1,guildClaims:1};assert(!c.rankTrialReady(1));c.profile.guildClaims=2;assert(c.rankTrialReady(1));assert(!c.rankTrialReady(2));c.run.level=1;assert(!c.rankTrialReady(1));
Object.assign(c,{paused:false,basicAttackId:()=>4,CLASSES:{4:{ranged:true,wep:'bow',sk:[{col:1}]}},MAGIC_CLS:[],basicIsMagic:()=>false,basicDmgMul:()=>1,statsBonus:()=>({atk:1}),FX2:{counter:false},dprog(){},faceTarget(){},beep(){}});vm.runInContext(extract('attack'),c);const fired=[];c.shoot=(...a)=>fired.push(a);c.profile={rankTalents:['volley','volley','bounce']};c.player={dead:false,atkCd:0,dodgeT:0,combo:0,comboT:0,face:0,x:0,z:0,dmg:100,buff:0};c.attack();assert.equal(fired.length,3);assert.equal(fired[0][4],100);assert.equal(fired[1][4],40);assert.equal(fired[2][4],40);assert.equal(fired[0][8].bounces,1);c.profile.rankTalents=[];c.player.atkCd=0;fired.length=0;c.attack();assert.equal(fired.length,1);
console.log('PASS new/legacy slots, rank choice budget/caps/requirements/persistence, actual ricochet, actual projectile damage, class effort/cost, rank trial prerequisites');
