const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8');
function extract(n){const m=new RegExp('function\\s+'+n+'\\s*\\([^)]*\\)').exec(src);assert(m,n);let b=src.indexOf('{',m.index),d=0,q=null,e=false;for(let i=b;i<src.length;i++){let c=src[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;if(c==='}'&&!--d)return src.slice(m.index,i+1)}}
const c={run:{items:[],equip:{w:{uid:'old',slot:'w',tier:0}},gold:1000},RAR:[{c:'#fff',n:'Comum'}],PRICE:[100,300,900],rankOf:()=>2,priceMul:()=>1,makeItem:(slot,tier)=>({uid:'new',slot,tier,rar:0,name:'Teste',value:40}),refreshStats(){},toast(){},fmt:String};vm.createContext(c);for(const n of ['addItem','equipmentBagRoom','buyEquipment','equipBagItem'])vm.runInContext(extract(n),c);
const old=c.run.equip.w;assert(c.buyEquipment('w',2));assert.strictEqual(c.run.equip.w,old);assert.equal(c.run.gold,100);assert.equal(c.run.items.length,1);assert(c.equipBagItem('new'));assert.equal(c.run.equip.w.uid,'new');assert.strictEqual(c.run.items[0],old);
c.run.equip.a=null;assert(c.addItem({uid:'armor',slot:'a',tier:1,rar:0,name:'Armor',value:20}));assert.equal(c.run.equip.a,null);assert(c.equipBagItem('armor'));assert.equal(c.run.equip.a.uid,'armor');
c.run.items=Array.from({length:24},(_,i)=>({uid:String(i),slot:'w',tier:0}));c.run.gold=10000;assert(!c.buyEquipment('w',1));assert.equal(c.run.gold,10000);assert.equal(c.run.items.length,24);assert(c.equipBagItem('0'));assert.equal(c.run.items.length,24);assert(!c.buyEquipment('w',3));assert(!c.buyEquipment('x',1));assert.equal(c.run.gold,10000);c.run.items[0].tier=9;assert(!c.equipBagItem(c.run.items[0].uid));
const eq=c.run.equip.w;assert(!c.addItem({slot:'w',tier:2,value:40,name:'Drop'}));assert.strictEqual(c.run.equip.w,eq);assert.equal(c.run.gold,10040);
console.log('PASS purchase and loot stay unequipped; explicit swap; rank validation; full-bag purchase spends nothing; overflow loot preserves equipment');
