const fs=require('fs'),vm=require('vm'),assert=require('assert');const src=fs.readFileSync(__dirname+'/../game.html','utf8'),base=fs.readFileSync(__dirname+'/verify-v95.cjs','utf8');eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')).replace("src.indexOf('{',m.index)","src.indexOf('{',m.index+m[0].length)"));
for(const file of ['game.html','index.html'])for(const m of fs.readFileSync(__dirname+'/../'+file,'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))if(m[1].trim())new vm.Script(m[1]);
const hits=[],shots=[],c={profile:{cls:5,jobs:[5]},run:{level:1,skl:{},classLoadout:['5:0','5:1','5:2',null,null,null]},player:{x:0,z:0,hp:10,maxhp:100,mp:500,face:0,slowT:2,bleedT:3},allies:[],enemies:[],time:10,store:{set(){}},S:(n,t,cd,mp,pow,col)=>({n,t,cd,mp,pow,col}),narratorEvent105(){},hasAff:()=>false,fmt:Math.round,floater(){},fxRing(){},sfx(){},skillDamage:()=>100,faceTarget(){},physicalEvolution:()=>false,magicEvolution:()=>false,skillFx(){},hitstop(){},shake(){},skillGroundPoint:()=>({x:0,z:6}),freeAt:()=>true,los:()=>true,shoot:(...args)=>shots.push(args),hurtEnemy(e,d,x,z,o){e.hp-=d;hits.push(o);return d},classSlotCount:()=>6,ELEM:{}};
vm.createContext(c);vm.runInContext(src.slice(src.indexOf('const CLASSES='),src.indexOf('/* Segundo Despertar')),c);c.CLASSES=vm.runInContext('CLASSES',c);
for(const n of ['healerLevel','healingFraction','healingShieldCap','healingShield','absorbHealingShield','applyHealingLight','blessAllies','judgmentRadius','runSkill','paladinSkillUnlocked109','learnedSkills','jobsOf','classSkill','classLoadout'])vm.runInContext(extract(n),c);
assert.equal(c.CLASSES[5].n,'Paladino');assert.equal(c.CLASSES[5].sk.length,8);assert.equal(c.learnedSkills().length,3);const kit=c.CLASSES[5].sk;const unit=(z=0)=>({x:0,z,hp:10,maxhp:100,life:10,slowT:2,slow:2,stun:1,bleedT:3,bleedD:5});
c.player=unit();c.allies=[unit(8),unit(8.1),{...unit(),dead:true}];c.runSkill(kit[0]);assert.equal(c.player.hp,60);assert.equal(c.allies[0].hp,60);assert.equal(c.allies[1].hp,10);assert.equal(c.allies[2].hp,10);assert.equal(c.player.bleedT,3);assert.equal(c.player.slowT,2);assert.equal(c.healingShield(c.player),0);c.runSkill(kit[0]);assert.equal(c.player.hp,100);assert.equal(c.healingShield(c.player),0);
c.player.hp=10;c.enemies=[{x:0,z:2,hp:500,r:.5}];c.runSkill(kit[1]);assert.equal(c.enemies[0].hp,400);assert.equal(c.player.hp,10);assert.equal(hits[0].kb,0);assert.equal(hits[0].stun,0);
c.runSkill(kit[3]);assert.equal(c.player.hp,10);assert.equal(c.player.bleedT,0);assert.equal(c.player.slowT,0);assert.equal(c.allies[0].stun,0);assert.equal(c.allies[1].stun,1);assert.equal(c.healingShield(c.player),0);
c.hasAff=()=>true;c.runSkill(kit[4]);assert.equal(c.healingShield(c.player),20);assert.equal(c.player.hp,10);c.runSkill(kit[4]);assert.equal(c.healingShield(c.player),20);assert.equal(c.absorbHealingShield(c.player,25),5);c.run.skl['Égide Sagrada']=10;c.runSkill(kit[4]);assert.equal(c.healingShield(c.player),40);c.time+=6;assert.equal(c.healingShield(c.player),0);c.runSkill(kit[0]);assert.equal(c.player.hp,10);c.hasAff=()=>false;c.run.skl['Luz Curativa']=10;c.runSkill(kit[0]);assert.equal(c.player.hp,80);
c.freeAt=()=>false;c.runSkill(kit[6]);assert.equal(c.player.z,0);c.freeAt=()=>true;c.los=()=>false;c.runSkill(kit[6]);assert.equal(c.player.z,0);c.los=()=>true;c.runSkill(kit[6]);assert.equal(c.player.z,6);assert(!c.player.iT);assert(!c.player.dashDmg);
c.enemies=[{x:0,z:6,hp:500,slow:0},{x:0,z:6,hp:500,slow:0,isBoss:true},{x:0,z:11,hp:500,slow:0}];c.runSkill(kit[7]);assert.equal(c.enemies[0].slow,3);assert.equal(c.enemies[0].hp,500);assert.equal(c.enemies[1].slow,0);assert.equal(c.enemies[2].slow,0);
for(const [lv,count] of [[29,3],[30,4],[44,4],[45,5],[60,5],[80,6],[100,7]]){c.run.level=lv;assert.equal(c.learnedSkills().length,count)}c.run.adv=true;assert.equal(c.learnedSkills().length,8);assert.equal(kit[5].n,'Sol Nascente');const saved=JSON.stringify(c.profile);c.profile=JSON.parse(saved);c.run.level=1;c.run.adv=false;assert.equal(c.learnedSkills().length,8);assert.equal(c.classLoadout().length,6);assert.equal(c.classLoadout()[0],'5:0');assert.equal(c.run.skl['Luz Curativa'],10);
assert(!src.includes('Curandeiro'));assert(src.includes("n:'Paladino Solar'"));assert(!extract('runSkill').includes('judgmentRelief'));assert(!extract('applyHealingLight').includes('healShieldUntil'));
console.log('PASS Paladin eight skills: isolated healing/damage/cleansing/shield/movement/control, no-cure behavior, range/dead/boss/wall checks, level thresholds, permanent unlock roundtrip/rebirth, original IDs/investment/six slots retained; source/generated parse.');

vm.runInContext(src.slice(src.indexOf('const ADV='),src.indexOf('const JOB_LVL=')),c);c.CLASS_SLOTS=[0,1,2,4,5,6];vm.runInContext(extract('pSkills'),c);c.run.adv=true;c.run.classLoadout=['5:0','5:1','5:2','5:3','5:4','5:5'];c.player.skills=c.pSkills();assert.equal(c.player.skills.filter(s=>!s.empty).length,6);assert(c.player.skills[3].empty);assert(c.player.skills.some(s=>s.n==='Sol Nascente'));
Object.assign(c,{paused:false,toast(){},narratorSkill105(){},skillCooldown:s=>s.cd,magicEvolution:()=>true});vm.runInContext(extract('useSkill'),c);const solar=c.player.skills.find(s=>s.n==='Sol Nascente');c.player.mp=100;c.useSkill({...solar,cdT:0});assert.equal(c.player.mp,65);assert.equal(solar.cdT,14);c.useSkill({...solar,cdT:0});assert.equal(c.player.mp,65);c.player.skills=c.player.skills.filter(s=>s!==solar);c.useSkill({...solar,cdT:0});assert.equal(c.player.mp,65);
console.log('PASS evolved Paladin has six equipped skills, no extra G ability; legacy library routes Solar to equipped cooldown and cannot bypass it.');
