const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8'),base=fs.readFileSync(__dirname+'/verify-v95.cjs','utf8');eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')));
let opened='';const c={trialJournal113:()=>"",profile:{rank:0,cls:0},run:{level:1,spts:0,shadows:[]},player:{skills:[],x:0,z:0},L:{mode:'world'},RARE103:[],MAIN_ACTS:[null],DAILY:[],CLASSES:[{n:'Guerreiro',sk:[]}],PASSIVES:[],GR:Array.from({length:10},()=>({lvl:1})),RANKS:Array.from({length:10},(_,i)=>({id:String(i)})),row:(...x)=>x.join(' '),btn:(...x)=>x.join(' '),fmt:String,rkN:String,characterTabs:()=>'',basicAttackId:()=>0,basicAttackDesc:()=>'',classSlotCount:()=>1,learnedSkills:()=>[],powLib:()=>[],jobsOf:()=>[0],classTraining:()=>({level:1,bosses:0,gold:0}),classTrainingReady:()=>false,orderRep:()=>0,orderRepNeed:()=>100,orderRepReward:()=>10,rankTrialReady:()=>false,rankPoints:()=>0,journeyObjectives:()=>[],trackedObjective:()=>null,openModal:(title,h)=>{opened=title+' '+h},toast(){},store:{set(){}},narratorEvent105(){}};c.kitProgress111=()=>"";c.kitFilter111=()=>"";c.kitVisible111=()=>true;c.RARE_IDS111=[7,12,13,14,15,16,17,18,19,20];vm.createContext(c);
for(const n of ['characterTabs','characterView','awakeningDiscovered109','awakening103','isTwiceAwakened103','rareOnPortal103','awakeningView103','skillsView','journeyView','jobsTab','rankTab'])vm.runInContext(extract(n),c);
const screens=()=>[c.rankTab(),c.jobsTab(),(c.skillsView(),opened),(c.journeyView(),opened)];
for(const rank of [0,8,9]){c.profile={rank,cls:0};assert(screens().every(h=>!/segundo despertar|awakening|afinidade principal/i.test(h)));opened='unchanged';const before=JSON.stringify(c.profile);c.awakeningView103();assert.equal(opened,'unchanged');assert.equal(JSON.stringify(c.profile),before)}
c.profile={rank:0,cls:0};c.run.level=29;c.rareOnPortal103({id:1,rank:0,x:0,z:0});assert(!c.awakeningDiscovered109());assert(screens().every(h=>!/segundo despertar/i.test(h)));
c.run.level=30;c.rareOnPortal103({id:2,rank:0,x:0,z:0});assert(c.awakeningDiscovered109());assert(!/segundo despertar/i.test(c.rankTab()+c.jobsTab()));c.journeyView();assert(!/segundo despertar|awakening/i.test(opened));assert(c.characterTabs('skills').includes('A Fissura'));c.characterView('awakening');assert(opened.includes('A FISSURA'));assert(!/Segundo Despertar|dez classes raras|afinidade principal/i.test(opened));assert(opened.includes('Ainda não sabe'));c.profile.awakening103.total=3;assert(c.characterTabs('skills').includes('Despertar'));c.characterView('awakening');assert(opened.includes('Segundo Despertar concluído'));c.profile=JSON.parse(JSON.stringify(c.profile));assert(c.awakeningDiscovered109());
for(const a of [{total:3},{unlocked:[7]},{pending:{id:1}},{discovered:true}]){c.profile.awakening103=a;assert(c.awakeningDiscovered109())}c.profile.awakening103={energy:2,total:0,unlocked:[]};assert(!c.awakeningDiscovered109());
console.log('PASS secret absent from rank, skills, diary and classes before discovery (F/SS+/star); direct view cannot leak or mutate save; level alone insufficient; real story discovery reveals only the character tab, with mystery text until completion; persisted and progressed saves keep access');
