'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8');
function extract(n){const m=new RegExp('function\\s+'+n+'\\s*\\([^)]*\\)').exec(src);assert(m,n);let b=src.indexOf('{',m.index),d=0,q=null,e=false;for(let i=b;i<src.length;i++){let c=src[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;if(c==='}'&&!--d)return src.slice(m.index,i+1)}}
const c={console,Math:Object.create(Math),Map,Set,Number,Array,profile:{cls:0,rank:0},run:{skl:{},adv:false,stats:{}},L:{mode:'world'},player:{x:0,z:0,skills:[]},inCity:()=>true,store:{set(){}},saveRun(){},styleTutorial(){},showG(){},MAGIC_CLS:[3,5,6,7,8,9,10,11],isMagic:()=>false,cons:()=>0,clamp:(x,a,b)=>Math.max(a,Math.min(b,x)),summonCap:()=>3,minionAllies:()=>[],hasAff:()=>false};vm.createContext(c);
vm.runInContext(src.slice(src.indexOf('const S='),src.indexOf('const BOSSES='))+';globalThis.CLASSES=CLASSES;',c);
vm.runInContext(src.slice(src.indexOf('const ELEM='),src.indexOf('const SOV_SK=')),c);
vm.runInContext(src.slice(src.indexOf('const PASSIVES='),src.indexOf('function passiveClasses'))+';globalThis.PASSIVES=PASSIVES;',c);
vm.runInContext('const CLASS_SLOTS=[0,1,2,4,5,6];const ADV=CLASSES.map((x,i)=>({sk:{n:"Evolução "+i,t:"nova",cd:10,mp:10,pow:2}}));',c);
for(const n of ['jobSlots','jobsOf','ownsRare','canLearnClass','learnClass','classSkill','learnedSkills','classLoadout','pSkills','rememberClassCooldowns','equipClassSkill','passiveClasses','hasClassPassive','passiveOf','applyPassive','eqTitles','titleB','runSkill','skillCooldown','skillCooldownText','skillDesc'])vm.runInContext(extract(n),c);
let count=0;function test(n,fn){try{fn();console.log('PASS '+n);count++}catch(e){console.error('FAIL '+n+' '+e.stack);process.exitCode=1}}
test('ten common initial classes, rare excluded',()=>{assert.equal(c.CLASSES.filter(x=>x.w>0).length,10);assert(c.CLASSES[7].rare);assert.equal(c.jobSlots(),10)});
test('learn every common class without rank slot cap',()=>{c.profile={cls:0,rank:0};for(let i=0;i<c.CLASSES.length;i++)if(i!==0&&!c.CLASSES[i].rare&&!c.CLASSES[i].legacy)assert(c.learnClass(i));assert.equal(c.jobsOf().length,10);assert(!c.canLearnClass(7));assert(!c.learnClass(99))});
test('one rare choice and old necromancer migration',()=>{c.profile.rank=8;assert(!c.learnClass(7));c.CLASSES.push({n:'Future rare',rare:true,sk:[]});assert(!c.canLearnClass(12));c.CLASSES.pop();c.profile={cls:7,rank:0};assert(c.jobsOf().includes(7));assert.equal(c.profile.rareClass,7)});
test('old save gets original three slots and empty extras',()=>{c.profile={cls:0,rank:0};c.run={skl:{},adv:false};const a=c.pSkills();assert.equal(a.length,7);assert.equal(a[0].n,'Corte Giratório');assert(a[3].empty&&a[4].empty&&a[6].empty)});
test('six mixed slots, duplicate swap, cooldown and persistence',()=>{c.profile={cls:0,rank:0,jobs:[0,8,9,10,11,5,6]};c.run={skl:{},adv:true};c.player.skills=c.pSkills();c.player.skills[0].cdT=5;assert(c.equipClassSkill(3,'9:0'));assert.equal(c.player.skills[4].sourceClass,9);assert.equal(c.player.skills[3].n,'Evolução 0');assert.equal(c.player.skills[0].cdT,5);assert(c.equipClassSkill(0,'9:0'));assert.equal(c.player.skills[0].sourceClass,9);assert.equal(c.player.skills[4].n,'Corte Giratório');assert.equal(c.player.skills[4].cdT,5);const saved=JSON.parse(JSON.stringify(c.run));c.profile.cls=8;c.run=saved;assert.equal(c.pSkills()[0].sourceClass,9);assert(!c.equipClassSkill(8,'9:0'));assert(!c.equipClassSkill(1,'7:0'));c.L.mode='dungeon';assert(!c.equipClassSkill(1,'5:0'));c.L.mode='world';});
test('unequip and re-equip preserve cooldown after save round trip',()=>{c.profile={cls:0,jobs:[0,9]};c.run={skl:{},adv:false};c.player.skills=c.pSkills();c.player.skills[0].cdT=9;c.player.skills[0].cdMax=12;assert(c.equipClassSkill(0,'9:0'));c.run=JSON.parse(JSON.stringify(c.run));assert(c.equipClassSkill(0,'0:0'));assert.equal(c.player.skills[0].cdT,9);assert.equal(c.player.skills[0].cdMax,12);c.rememberClassCooldowns();assert.equal(c.pSkills()[0].cdT,9)});
test('invalid and duplicate save skills sanitized',()=>{c.profile={cls:0,jobs:[0,9,10]};c.run.classLoadout=['9:0','9:0','99:0','7:0',null,'10:0'];const x=c.classLoadout();assert.equal(x.filter(Boolean).length,2)});
test('all learned passives stack, with no-cure respected',()=>{c.profile={cls:0,rank:0,jobs:[0,5,8,9,10]};c.Math.random=()=>0;c.player={x:0,z:0,hp:10,maxhp:100,skills:[]};Object.assign(c,{floater(){},fxRing(){},enemies:[]});const e={x:2,z:0,stun:0,slow:0,kb:{x:0,z:0}};c.applyPassive(e,100,false,{third:true});assert.equal(c.player.hp,14.5);assert.equal(e.dotT,3);assert.equal(e.dotD,20);assert.equal(e.slow,2);assert(e.stun>=.8);c.hasAff=()=>true;c.applyPassive(e,100,false,{third:true});assert.equal(c.player.hp,14.5);c.hasAff=()=>false});
test('more than three titles equipped, no duplicates or invalid titles',()=>{c.TITLES=Array.from({length:12},(_,i)=>({id:'t'+i,b:{dmg:.01}}));c.profile={ach:c.TITLES.map(x=>x.id),titles:[...c.TITLES.map(x=>x.id),'t1','unknown']};assert.equal(c.eqTitles().length,12);assert(Math.abs(c.titleB().dmg-.12)<.00001)});
Object.assign(c,{player:{x:0,z:0,face:0,dmg:40,buff:0,maxhp:100,hp:50},run:{skl:{}},profile:{cls:0},atkOf:k=>k==='mag'?100:40,wxSkillMul:()=>1,statsBonus:()=>({skill:1}),setB:()=>({}),faceTarget:()=>({x:0,z:4}),skillFx(){},sfx(){},hitstop(){},shake(){},spikes(){},cracks(){},zig(){},enemies:[],rnd:()=>0});
test('mixed caster damage uses magic attribute and ice projectile pierces/slows',()=>{let got;c.shoot=(...args)=>got=args;c.runSkill(c.classSkill(9,0));assert.equal(got[4],260);assert.equal(got[7],'ice');assert(got[8].pierce&&got[8].slow===3);c.runSkill(c.classSkill(8,0));assert.equal(got[7],'fire');assert(got[8].burn>0)});
test('earth lance is directional, not circular damage',()=>{const a={x:0,z:5,r:.5},b={x:4,z:2,r:.5},d={x:0,z:-2,r:.5};c.enemies=[a,b,d];let hits=[];c.hurtEnemy=e=>hits.push(e);c.runSkill(c.classSkill(10,0));assert.deepEqual(hits,[a])});
test('lightning storm targets at most five marked enemy positions',()=>{c.enemies=Array.from({length:8},(_,i)=>({x:i*.2,z:4,r:.5}));let hits=[];c.hazard=(...args)=>{const h={args};hits.push(h);return h};c.runSkill(c.classSkill(11,2));assert.equal(hits.length,5);assert(hits.every(h=>h.lightning&&h.args[2]===.85&&h.args[3]>=.5))});
test('load old save preserves progress and evolution power, creates one backup',()=>{let data={pds2_profile:{cls:0},pds3_run:{level:135,gold:8765,stats:{for:800},pts:37,stolen:['Evolução 0'],lib:[{n:'Evolução 0',t:'nova',cd:10,mp:10}],items:[{up:8}],res:{core:Array(9).fill(3),cry:Array(9).fill(4)}}};c.store={get:k=>data[k],set:(k,v)=>data[k]=JSON.parse(JSON.stringify(v))};c.ALLBOSS=()=>[];vm.runInContext(extract('newRun')+';'+extract('loadRun'),c);assert(c.loadRun());assert.equal(c.run.stats.for,800);assert.equal(c.run.pts,37);assert.equal(c.run.gold,8765);assert.equal(c.run.items[0].up,8);assert.equal(c.run.stolen[0].n,'Evolução 0');assert.equal(data.pds3_backup_v70.run.level,135);data.pds3_run={...c.run,level:136};assert(c.loadRun());assert.equal(data.pds3_backup_v70.run.level,135)});
test('physical starter learns magic, toggles with X, fires magic basic attack',()=>{for(const n of ['canUseMagicStyle','styleOff','basicIsMagic','basicAttackClass','basicDmgMul','toggleStyle','attack'])vm.runInContext(extract(n),c);Object.assign(c,{started:true,paused:false,bigText(){},toast(){},hud(){},saveRun(){},sfx(){},dprog(){},beep(){},FX2:{counter:false},isMagic:()=>c.MAGIC_CLS.includes(c.profile.cls),statsBonus:()=>({atk:1}),atkOf:k=>k==='mag'?100:40});c.profile={cls:0,jobs:[0]};c.run={style:'nat',skl:{}};assert(!c.canUseMagicStyle());c.toggleStyle();assert(!c.basicIsMagic());c.profile.jobs.push(9);c.toggleStyle();assert(c.basicIsMagic());assert.equal(c.run.style,'arc');c.player={dead:false,atkCd:0,dodgeT:0,comboT:0,dmg:40,buff:0,x:0,z:0,face:0};let fired;c.shoot=(...a)=>fired=a;c.attack();assert.equal(fired[7],'ice');assert.equal(fired[4],100);c.toggleStyle();assert(!c.basicIsMagic());assert.equal(c.run.style,'nat')});
console.log(count+' scenarios passed');

