const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8');
const base=fs.readFileSync(__dirname+'/verify-v95.cjs','utf8');
eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')));
const hits=[],c={run:{skl:{}},time:20,allies:[],enemies:[],player:{x:0,z:0,hp:10,maxhp:100},skillDamage:()=>20,faceTarget(){},physicalEvolution:()=>false,magicEvolution:()=>false,skillFx(){},hurtEnemy:e=>hits.push(e),hitstop(){},shake(){},floater(){},fmt:Math.round,toast(){},sfx(){},npcHas:()=>false,hasT:()=>false};
vm.createContext(c);for(const n of ['healerLevel','judgmentRadius','healingFraction','blessAllies','allyProtection','runSkill','potionHealFraction'])vm.runInContext(extract(n),c);
const j={n:'Julgamento',t:'nova',pow:1.8};assert.equal(c.judgmentRadius(j),6);c.enemies=[{x:8,z:0,r:.4}];c.runSkill(j);assert.equal(hits.length,0);c.run.skl.Julgamento=10;assert.equal(c.judgmentRadius(j),10);c.runSkill(j);assert.equal(hits.length,1);
const h={n:'Luz Curativa',t:'heal',pow:.35};c.allies=[{x:1,z:0,hp:20,maxhp:200,life:10},{x:2,z:0,hp:0,maxhp:100,life:10,dead:true}];c.runSkill(h);assert.equal(c.player.hp,45);assert.equal(c.allies[0].hp,90);assert.equal(c.allies[1].hp,0);c.run.skl[h.n]=10;c.runSkill(h);assert.equal(c.player.hp,95);assert.equal(c.allies[0].hp,190);c.runSkill(h);assert.equal(c.player.hp,100);assert.equal(c.allies[0].hp,200);
c.allies.push({x:9,z:0,life:10});c.runSkill({n:'Bênção',t:'guard',pow:.4});assert.equal(c.player.guardVal,.4);assert.equal(c.allies[0].blessingUntil,25);assert.equal(c.allies[1].blessingUntil,undefined);assert.equal(c.allies[2].blessingUntil,undefined);assert.equal(c.allyProtection(c.allies[0]),.7);c.allies[0].fortressUntil=25;assert.equal(c.allyProtection(c.allies[0]),.5);c.time=25;assert.equal(c.allyProtection(c.allies[0]),1);
assert.equal(c.potionHealFraction(),.5);c.npcHas=()=>true;assert.equal(c.potionHealFraction(),.75);c.hasT=()=>true;assert.equal(c.potionHealFraction(),.9375);
console.log('PASS Judgment actual radius 6→10, group healing 35→50%, dead exclusion/cap, Blessing range/duration/strongest protection, potion bonuses');
