const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8'),base=fs.readFileSync(__dirname+'/verify-v95.cjs','utf8');eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')).replace("src.indexOf('{',m.index)","src.indexOf('{',m.index+m[0].length)"));
for(const f of ['game.html','index.html'])for(const m of fs.readFileSync(__dirname+'/../'+f,'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))if(m[1].trim())new vm.Script(m[1]);
const logs=[],c={profile:{rank:0},player:{x:0,z:0,hp:100,maxhp:100,dead:false},started:true,paused:false,modalOpen:false,CFG:{},L:{mode:'world'},AR103:{},nearestEnemy:()=>null,inCity:()=>false,nearestCity:()=>({c:{id:'Aster'}}),logNews:(s,k)=>logs.push({s,k}),applyCfg(){}};vm.createContext(c);vm.runInContext(src.slice(src.indexOf('const NR_LINES105='),src.indexOf('const RARE103=')),c);for(const n of ['narratorMemory105','narratorTone105','narratorEvent105','narratorChoose105','narratorSkill105','narratorPortal105','narratorEnter105','narratorDeath105','narratorContext105','narratorUpdate105','setNarrator105'])vm.runInContext(extract(n),c);
const bank=vm.runInContext('NR_LINES105',c),state=()=>vm.runInContext('NR105',c),tick=n=>{for(let i=0;i<n;i++)c.narratorUpdate105(1)},reset=()=>{c.profile={rank:0};c.L={mode:'world'};c.player.hp=100;c.CFG={};c.nearestEnemy=()=>null;c.inCity=()=>false;c.paused=false;c.modalOpen=false;vm.runInContext('NR105={queue:[],quietFor:0,tick:0,city:null}',c);logs.length=0;return c.narratorMemory105()};
assert.equal(Object.keys(bank).length,60);assert.equal(Object.values(bank).flat().length,2000);assert.equal(new Set(Object.values(bank).flat()).size,2000);for(const a of Object.values(bank).slice(0,20))assert.equal(a.length,20);assert(!Object.values(bank).flat().some(x=>/[<>]/.test(x)));
let m=reset();assert.equal(m.recent.length,0);c.narratorEvent105('victory');c.nearestEnemy=()=>({});tick(10);assert.equal(logs.length,0);c.nearestEnemy=()=>null;c.modalOpen=true;tick(5);assert.equal(logs.length,0);c.modalOpen=false;tick(1);assert.equal(logs.length,1);assert.equal(logs[0].k,'narratorPersonal105');assert.equal(Object.keys(m.seen).length,1);c.narratorEvent105('rank',{rank:1});tick(89);assert.equal(logs.length,1);tick(1);assert.equal(logs.length,2);
m=reset();c.setNarrator105('off');c.narratorEvent105('death');tick(200);assert.equal(logs.length,0);assert.equal(m.counts.death,1);assert.equal(state().queue.length,0);c.setNarrator105('normal');tick(100);assert.equal(logs.length,0);c.narratorEvent105('rank',{rank:1});tick(6);assert.equal(logs.length,1);
m=reset();for(let i=0;i<15;i++){m.sequence++;const x=c.narratorChoose105({kind:'victory'},m);assert(x);assert.notEqual(x.tone,'playful');assert(!Object.keys(m.seen).includes(x.id));m.seen[x.id]=m.clock;}assert.equal(c.narratorChoose105({kind:'victory'},m),null);m.clock=3600;assert(c.narratorChoose105({kind:'victory'},m));c.CFG.narratorTease105=true;m.recent=Array(20).fill('victory');assert.equal(c.narratorTone105(m),'playful');assert.equal(c.narratorChoose105({kind:'victory'},m).tone,'playful');m.recent=Array(3).fill('death');assert.equal(c.narratorTone105(m),'careful');m.recent=Array(3).fill('support');assert.equal(c.narratorTone105(m),'warm');m.recent=Array(64).fill('city');c.CFG.narratorTease105=false;assert.equal(c.narratorTone105(m),'calm');
m=reset();c.narratorEvent105('awakening');tick(6);assert.equal(logs.length,1);m.clock+=10000;c.narratorEvent105('awakening');assert.equal(state().queue.length,0);assert.equal(Object.keys(m.seen).length,1);
m=reset();let g={id:1,seed:3,rank:0};c.L={mode:'dungeon',gate:g};c.narratorDeath105();assert.equal(m.failed[0],1);c.L={mode:'world'};c.narratorPortal105(g,true);assert.equal(m.counts.returnwin,1);assert.equal(m.failed[0],undefined);assert.equal(m.clears,1);c.narratorPortal105(g,true);assert.equal(m.clears,1);g={id:2,rank:0};c.narratorPortal105(g,false);assert.equal(m.counts.retreat,1);assert.equal(m.clears,1);c.narratorPortal105({id:3,rank:0,coreFailed103:true},false);assert.equal(m.counts.retreat,1);
m=reset();g={id:4,seed:1,rank:3,red:true};c.L={mode:'dungeon',gate:g};c.narratorEnter105(g);assert.equal(m.counts.red,1);c.narratorEnter105(g);assert.equal(m.counts.red,1);c.L={mode:'world'};tick(10);assert.equal(logs.length,0);assert.equal(state().queue.length,0);
m=reset();c.nearestEnemy=()=>({});for(let i=0;i<24;i++)c.narratorSkill105({sourceClass:5});assert.equal(m.dominant,5);assert(!m.counts.shift);for(let i=0;i<24;i++)c.narratorSkill105({sourceClass:7});assert.equal(m.counts.shift,1);assert.equal(m.dominant,7);c.nearestEnemy=()=>null;for(let i=0;i<24;i++)c.narratorSkill105({sourceClass:2});assert.equal(m.dominant,7);assert.equal(m.skills.length,24);
m=reset();for(let i=0;i<1000;i++)c.narratorEvent105('victory');assert.equal(m.recent.length,64);assert.equal(m.facts.length,24);assert(state().queue.length<=4);let saved=JSON.stringify(c.profile);c.profile=JSON.parse(saved);assert.equal(JSON.stringify(c.narratorMemory105()),JSON.stringify(m));assert(saved.length<10000);
m=reset();c.narratorEvent105('support');c.narratorEvent105('support');assert.equal(m.counts.support,1);m.clock+=20;c.narratorEvent105('support');assert.equal(m.counts.support,2);state().quietFor=20;tick(19);assert.equal(logs.length,0);tick(1);assert.equal(logs.length,1);
m=reset();c.narratorEvent105('victory');c.nearestEnemy=()=>({});tick(61);c.nearestEnemy=()=>null;tick(10);assert.equal(logs.length,0);assert.equal(state().queue.length,0);
// Hooks reais: cura própria, alvo cheio e Sem cura não criam lembrança de ajudar aliado.
Object.assign(c,{hasAff:()=>false,healingFraction:()=>.5,healingShieldCap:()=>.2,healingShield:()=>0,time:0,floater(){},fxRing(){},fmt:Math.round});vm.runInContext(extract('applyHealingLight'),c);m=reset();c.player.hp=10;c.applyHealingLight(c.player,{n:'Teste'});assert(!m.counts.support);let ally={hp:100,maxhp:100};c.applyHealingLight(ally,{n:'Teste'});assert(!m.counts.support);ally.hp=10;c.hasAff=()=>true;c.applyHealingLight(ally,{n:'Teste'});assert(!m.counts.support);c.hasAff=()=>false;c.applyHealingLight(ally,{n:'Teste'});assert.equal(m.counts.support,1);assert.equal(ally.hp,60);
console.log('PASS expanded catalog / original 400 lines and 20 contexts preserved; safe moments, intervals, quiet notices, expiry, off mode; unseen first, repeat cooldown, opt-in humor, evolving tone; once-only awakening; factual deaths/return wins/retreats; gate context and duplicates; combat-only gradual style; bounded save roundtrip; actual group-heal event guards; source/build parse');
