const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8'),base=fs.readFileSync(__dirname+'/verify-v95.cjs','utf8');eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')));
let saves=0;const c={run:{level:24,stats:{for:20,int:30,agi:2,per:3,vit:4},equip:{w:null},skl:{},pts:7},player:{dmg:100,maxhp:200,maxmp:100,maxsh:50},profile:{cls:0,rankTalents:['x']},L:{mode:'world'},MAGIC_CLS:[3,5,6,7,8,9,10,11],itemAtk:()=>0,atkPer:L=>2+Math.floor(L/25),isMagic:()=>false,wxSkillMul:()=>1,statsBonus:()=>({skill:1}),setB:()=>({}),cons:()=>0,hasAff:()=>false,hasT:()=>false,fmt:Math.round,minionAllies:()=>[],summonCap:()=>5,SKD:{},STATN:{for:1,int:1,agi:1,per:1,vit:1},inCity:()=>true,refreshStats(){},saveRun(){saves++}};vm.createContext(c);
for(const n of ['atkOf','skillDamage','preciseNumber','skillHasDamage','skillDamagePart','skillEffect102','skillCooldown','skillCooldownText','skillDesc','skillUpgradeText','skillButtonTip','healerLevel','judgmentRadius','judgmentHealing','healingFraction','healingShieldCap','naturalRegen','canRedistribute','redistributeAttributes','resetRankTalents'])vm.runInContext(extract(n),c);
for(const magic of [false,true])for(const boundary of [25,50,100]){c.isMagic=()=>magic;const kind=magic?'mag':'phy',sk={n:'Test',pow:2,t:'nova',sourceClass:magic?5:0};c.run.skl.Test=10;c.run.level=boundary-1;c.player.dmg=c.atkOf(kind);const before=c.skillDamage(sk);c.run.level=boundary;c.player.dmg=c.atkOf(kind);assert(c.skillDamage(sk)>before);assert.equal(c.skillDamage(sk),c.atkOf(kind)*5);const old=c.skillDamage(sk);c.run.stats[magic?'int':'for']++;c.player.dmg=c.atkOf(kind);assert.equal(c.skillDamage(sk)-old,c.atkPer(boundary)*5)}
c.isMagic=()=>false;c.player.dmg=c.atkOf('phy');assert(Math.abs(c.skillDamage({n:'Test',pow:2,sourceClass:5})-c.atkOf('mag')*5)<1e-8);
const skillCalls=[...src.matchAll(/\bS(?:2)?\('([^']+)','([^']+)',([\d.]+),([\d.]+),([\d.]+),(0x[\da-f]+|[\d.]+)\)/gi)];assert(skillCalls.length>35);for(const m of skillCalls){const sk={n:m[1],t:m[2],cd:+m[3],mp:+m[4],pow:+m[5]};for(const lv of [0,10]){c.run.skl[sk.n]=lv;const text=c.skillDesc(sk);assert(!/NaN|undefined/.test(text),sk.n);assert(text.includes('Custo:'));if(lv===10){assert.equal(c.skillUpgradeText(sk),'');assert(!c.skillButtonTip(sk).includes('Melhore'))}else assert(c.skillUpgradeText(sk).includes('Recarga'))}}
c.run.skl.Julgamento=0;assert.equal(c.judgmentHealing({n:'Julgamento'}),.08);c.run.skl.Julgamento=10;assert.equal(c.judgmentHealing({n:'Julgamento'}),.18);
assert.equal(c.naturalRegen().hp,0);assert.equal(c.naturalRegen().mp,6);assert.equal(c.naturalRegen().shield,10);assert.equal(c.naturalRegen(c.player,true).mp,16);assert.equal(c.naturalRegen(c.player,true).hp,16);c.hasT=()=>true;assert.equal(c.naturalRegen().hp,2);assert.equal(c.naturalRegen().shield,13);
const points=c.run.pts+Object.values(c.run.stats).reduce((a,b)=>a+b,0);assert(c.redistributeAttributes());assert.equal(c.run.pts,points);assert.equal(Object.values(c.run.stats).reduce((a,b)=>a+b,0),0);assert(!c.redistributeAttributes());assert(c.resetRankTalents());assert.equal(c.profile.rankTalents.length,0);c.run.stats.int=5;c.L.mode='dungeon';assert(!c.redistributeAttributes());assert(!c.resetRankTalents());assert.equal(c.run.stats.int,5);assert.equal(saves,2);
console.log('PASS damage scaling physical/magic/hybrid at 25,50,100 and max skill; '+skillCalls.length+' descriptions at 0/10; upgrade visibility; Judgment 8-18%; regen rates; safe point refunds and rank reset');

