const fs=require('fs'),vm=require('vm'),assert=require('assert');const src=fs.readFileSync('game.html','utf8'),base=fs.readFileSync('tools/verify-v95.cjs','utf8');eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')));
for(const file of ['game.html','index.html'])for(const m of fs.readFileSync(file,'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))if(m[1].trim())new vm.Script(m[1]);
const A={id:'A',name:'Aster',x:0,z:0},B={id:'B',name:'Lume',x:1000,z:0},noop=()=>{};let logs=[];
const c={console,Math,Number,profile:{karma:4,abandon:{A:1}},run:{gold:10000,res:{cry:[40,0]},pots:0},player:{x:0,z:0},L:{mode:'world'},enemies:[],clamp:(n,a,b)=>Math.max(a,Math.min(b,n)),store:{set:noop},logNews:x=>logs.push(x),saveRun:noop,toast:noop,bigText:noop,pick:a=>a[0],safeText:String,fmt:String,row:(...x)=>x.join(' '),btn:(...x)=>x.join(' '),todayKey:()=> 'day1',inCity:()=>true,cityFallen:()=>false,nearestCity:(x,z)=>({c:x<500?A:B}),openModal:(t,h)=>c.html=h};vm.createContext(c);vm.runInContext(fs.readFileSync('tools/regions116.js','utf8'),c);vm.runInContext(extract('updInvasion'),c);
assert.equal(c.regionState116(A).damage,20);assert.equal(c.regionState116(A).trust,0);assert.equal(c.regionState116(B).damage,0);assert.equal(c.profile.karma,4);
let g={id:1,x:1000,z:0};assert(c.regionPortal116(g));assert(!c.regionPortal116(g));assert.equal(c.regionState116(B).trust,2);assert.equal(c.regionState116(A).trust,0);
c.regionEvent116(A,19,0,'test');assert.equal(c.regionDiscount116(c.regionState116(A)),0);c.regionEvent116(A,1,0,'test');assert.equal(c.regionDiscount116(c.regionState116(A)),5);c.regionEvent116(A,30,0,'test');assert.equal(c.regionDiscount116(c.regionState116(A)),10);c.regionEvent116(A,500,0,'test');assert.equal(c.regionState116(A).trust,100);assert.equal(c.regionDiscount116(c.regionState116(A)),15);
c.L.inv={c:A,t:.1,targets116:[{dead:false}]};c.updInvasion(1);assert.equal(c.regionState116(A).trust,100);assert.equal(c.regionState116(A).damage,20);assert.equal(c.regionState116(B).trust,2);
const beforeGold=c.run.gold;assert(c.regionAid116());assert.equal(c.run.gold,beforeGold-500);assert.equal(c.run.res.cry[0],32);assert.equal(c.regionState116(A).damage,15);assert(!c.regionSupply116());c.L.mode='dungeon';assert(!c.regionAid116());c.L.mode='world';c.inCity=()=>false;assert(!c.regionAid116());c.inCity=()=>true;c.player.dead=true;assert(!c.regionAid116());c.player.dead=false;c.run.gold=0;assert(!c.regionAid116());c.run.gold=10000;
for(let i=0;i<3;i++)assert(c.regionAid116());assert.equal(c.regionState116(A).damage,0);assert(!c.regionAid116());assert(!c.profile.abandon.A);assert(c.regionSupply116());assert.equal(c.run.pots,2);assert(!c.regionSupply116());c.profile=JSON.parse(JSON.stringify(c.profile));assert(!c.regionSupply116());c.todayKey=()=> 'day2';assert(c.regionSupply116());assert.equal(c.run.pots,4);c.L.siege={};assert(!c.regionSupply116());c.L.siege=null;
c.L.inv={c:B,t:10,targets116:[{dead:true}],helped116:true};c.updInvasion(1);assert.equal(c.regionState116(B).trust,14);c.updInvasion(1);assert.equal(c.regionState116(B).trust,14);c.L.inv={c:B,t:10,targets116:[{dead:true}]};c.updInvasion(1);assert.equal(c.regionState116(B).trust,14);assert.equal(c.profile.karma,4);
assert(c.regionLine116(A));c.regionView116();assert(c.html.includes('Duas poções por dia'));assert(c.html.includes('MEMÓRIA DA REGIÃO'));assert(c.regionState116(A).history.length<=8);
// Exercise actual completion hooks, retaining existing one-time gates.
Object.assign(c,{ensureOrderRep:noop,addOrderRep:noop,orderRepReward:()=>1,rankPortalCount:()=>0,RANKS:Array.from({length:10},(_,i)=>({id:i}))});vm.runInContext(extract('recordRankPortal'),c);vm.runInContext(extract('recordSpecialOrderRep'),c);
c.L={mode:'dungeon',bossDead:true,gate:{id:3,rank:0,x:1000,z:0}};const before=c.regionState116(B).trust;assert(c.recordRankPortal(0));assert(!c.recordRankPortal(0));assert.equal(c.regionState116(B).trust,before+2);c.L={special:{done:true},gate:{rank:0,ref:{id:4,x:1000,z:0}}};assert(c.recordSpecialOrderRep());assert(!c.recordSpecialOrderRep());assert.equal(c.regionState116(B).trust,before+4);assert(!c.regionPortal116({x:NaN,z:0}));
console.log('PASS local isolation, legacy migration, price tiers/caps, no blame for failed invasion, one-time portal/special hooks, participant-only defense reward, recovery costs/location/death/shortage guards, supply/day/reload locks, histories and rendered region view.');
