const fs=require('fs'),vm=require('vm'),assert=require('assert');
// v117 adds this runtime hook; the legacy harness does not exercise it.
const src=fs.readFileSync(__dirname+'/../game.html','utf8'),base=fs.readFileSync(__dirname+'/verify-v95.cjs','utf8');eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')));
let left=0,saved=0,chests=0;const obj=()=>({position:{set(){},y:0},rotation:{},add(){},remove(){},visible:true});
const c={Uint8Array,Math,THREE:{Group:class{constructor(){Object.assign(this,obj())}},Mesh:class{constructor(){Object.assign(this,obj())}},MeshBasicMaterial:class{},DoubleSide:2},geo:()=>({}),glowS:()=>({}),makeSign:obj,hex:String,mesh:obj,toonS:()=>({}),player:{x:0,z:0,dead:false,stealth:0},allies:[],enemies:[],projs:[],hazards:[],cam:{},bossLight:{},run:{spts:2,res:{core:Array(10).fill(0)}},profile:{},scene:{remove(){}},$:()=>({hidden:false}),toast(){},bigText(){},sfx(){},showSys(){},shake(){},fxRing(){},saveRun(){saved++},addChest(){chests++},addVein(){},placeAllies(){},leaveDungeon(){left++},fmtT:String,GR:Array.from({length:10},()=>({dmg:1})),spawnKind(k,x,z,rank,extra){const e={...extra,x,z,hp:100,maxhp:100,speed:2,gold:10,m:{root:obj()}};c.enemies.push(e);return e}};
Object.assign(c,{time:0,FX2:{inv:0},AR103:{},narratorEvent105(){},narratorSkill105(){},narratorDeath105(){},narratorPortal105(){}});vm.createContext(c);for(const n of ['variantLayout103','exitPortal','unlockDungeonExit','beginDungeonEscape','dungeonFloorAt','floorMapCenter','setupDungeonFloors','useDungeonStairs','coreLabel','startCoreDefense','hurtDefenseCore','coreWaveSize111','coreWave','completeCoreDefense','updateCoreDefense','coreObjective','pickTarget','tryExit','startBreak'])vm.runInContext(extract(n),c);
for(const flip of [.1,.9]){const m=c.variantLayout103('floors',()=>flip);assert.equal(m.rooms.length,12);assert.equal(m.rooms.filter(r=>r.entry).length,3);assert.equal(m.rooms.filter(r=>r.floorEnd).length,3);for(let f=0;f<3;f++){const rooms=m.rooms.filter(r=>r.floor===f),r=rooms[0],start=Math.floor(r.y+r.h/2)*m.W+Math.floor(r.x+r.w/2),seen=new Set([start]),q=[start];for(let i=0;i<q.length;i++){const at=q[i],x=at%m.W,y=Math.floor(at/m.W);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,n=ny*m.W+nx;if(nx>=0&&nx<m.W&&ny>=0&&ny<m.H&&m.cells[n]===1&&!seen.has(n)){seen.add(n);q.push(n)}}}for(const room of rooms)assert(seen.has(Math.floor(room.y+room.h/2)*m.W+Math.floor(room.x+room.w/2)));assert([...seen].every(i=>Math.floor(i/m.W)>=f*40&&Math.floor(i/m.W)<f*40+36),'floors disconnected except stairs')}}
function level(red=true){c.L={mode:'dungeon',group:obj(),exits:[],inter:[],gate:{rank:1,red,aff:[]},G:{dmg:1},rooms:[],bossRoom:1};c.enemies=[];c.player={x:0,z:0,dead:false,stealth:0};c.run.spts=2;c.run.res.core.fill(0)}
level();const exit=c.exitPortal(1,1,true);assert.strictEqual(c.exitPortal(50,50,false),exit);assert.equal(c.L.exits.length,1);c.tryExit(exit);assert.equal(left,0);c.L.bossDead=true;c.beginDungeonEscape();assert.equal(c.L.closeT,60);assert(!exit.locked);c.tryExit(exit);assert.equal(left,1);
level();const m=c.variantLayout103('floors',()=>.1);c.L.grid={...m,CS:2,ox:-m.W,oz:-m.H};c.L.rooms=m.rooms.map((r,i)=>({...r,i,wx:-m.W+(Math.floor(r.x+r.w/2)+.5)*2,wz:-m.H+(Math.floor(r.y+r.h/2)+.5)*2}));c.setupDungeonFloors();assert.equal(c.L.inter.length,4);assert.equal(c.L.exits.length,0);const stairs=c.L.inter[0];c.player.x=stairs.x;c.player.z=stairs.z;const guard={room:stairs.room,dead:false,z:stairs.z,m:{root:obj()}};c.enemies=[guard];assert(!c.useDungeonStairs(stairs));guard.dead=true;const originalEnemies=c.enemies;assert(c.useDungeonStairs(stairs));assert.equal(c.L.floors.current,1);assert.strictEqual(c.enemies,originalEnemies);assert(guard.dead);assert.equal(c.dungeonFloorAt(c.player.z),1);const back=c.L.inter[1];c.player.x=back.x;c.player.z=back.z;assert(c.useDungeonStairs(back));assert.equal(c.L.floors.current,0);assert(guard.dead);c.player.x+=20;assert(!c.useDungeonStairs(stairs));
function defense(){level();c.exitPortal(1,1,true);c.L.defense={front:{x:0,z:28},core:{x:0,z:0,hp:600,maxhp:600,defenseCore:true},crystal:obj(),inter:{},started:false,failed:false,done:false,t:0,wave:0,duration:60}}
defense();assert(c.startCoreDefense());assert(!c.startCoreDefense());c.updateCoreDefense(.1);assert.equal(c.L.defense.wave,1);assert.equal(c.enemies.length,8);const e=c.enemies[0];c.player.x=50;assert.strictEqual(c.pickTarget(e).t,c.L.defense.core);c.player.x=e.x;c.player.z=e.z;assert.strictEqual(c.pickTarget(e).t,c.player);c.player.stealth=1;assert.strictEqual(c.pickTarget(e).t,c.L.defense.core);c.updateCoreDefense(60);assert.equal(c.L.defense.wave,4);assert.equal(c.enemies.length,44);assert(!c.L.bossDead);assert.equal(c.run.spts,2);for(const e of c.enemies)e.dead=true;c.updateCoreDefense(.1);assert(c.L.bossDead);assert.equal(c.run.spts,3);assert.equal(c.run.res.core[1],3);assert.equal(c.L.closeT,60);assert.equal(chests,1);assert.equal(saved,1);assert(!c.completeCoreDefense());assert.equal(c.run.spts,3);
defense();c.startCoreDefense();c.hurtDefenseCore(600);assert(c.L.defense.failed);assert(c.L.brk);assert(c.L.gate.dead);assert(!c.L.bossDead);assert(!c.completeCoreDefense());assert.equal(c.run.spts,2);assert.equal(c.run.res.core[1],0);const before=left;c.tryExit(c.L.exits[0]);assert.equal(left,before+1,'red failure permits escape');c.updateCoreDefense(100);assert.equal(c.L.defense.wave,0);
assert(!extract('onBossDeath').includes('exitPortal('));assert(extract('onBossDeath').includes('beginDungeonEscape()'));
console.log('PASS 3 connected floor maps with no cross-floor corridor; stairs guard/proximity/return/enemy preservation; single exit/red lock/60s; core waves, targeting, survival+cleanup, one reward, failure/escape/no completion reward');
level();Object.assign(c,{expBossReward(){},unlockLore(){},npcEv(){},storyEv(){},hitstop(){},floater(){},fmt:String,killEnemy(){}});c.bossLight.color={setHex(){}};c.L.gate.owned=true;c.run.gold=0;const entrance=c.exitPortal(10,10,true);vm.runInContext(extract('onBossDeath'),c);c.onBossDeath({x:0,z:0,gold:10});assert.equal(c.L.exits.length,1);assert.strictEqual(c.L.exits[0],entrance);assert(!entrance.locked);assert.equal(c.L.closeT,60);assert(c.L.bossDead);
Object.assign(c,{updSpecial(){},expeditionUpdate(){},updateCoreDefense(){},updateCombat117(){},updBreak(){}});c.L.markT=999;entrance.ring.rotation={z:0};vm.runInContext(extract('updDungeon'),c);c.updDungeon(30);assert.equal(c.L.closeT,30);assert(!c.L.brk);c.updDungeon(30);assert(c.L.brk);console.log('PASS real boss death keeps original exit; actual dungeon update starts break after 60 seconds');
let persisted;Object.assign(c,{store:{set(k,v){persisted=JSON.parse(JSON.stringify(v))}},ECON:Array(10).fill(1),kindsFor:()=>[],wpick:()=>({k:'warrior'}),rnd:(a,b)=>(a+b)/2});for(const n of ['failRedPortalOnDeath','releaseRedPortalBreaks','dungeonBreak'])vm.runInContext(extract(n),c);
level();c.L.gate={id:18,seed:34,rank:2,x:100,z:150,red:true};const red=c.L.gate;c.L.bossDead=true;assert(c.failRedPortalOnDeath());assert(red.dead&&!red.cleared&&c.L.failed103);assert.equal(persisted.pendingRedBreaks103.length,1);assert(c.failRedPortalOnDeath());assert.equal(c.profile.pendingRedBreaks103.length,1);c.releaseRedPortalBreaks();assert.equal(c.enemies.length,0,'no world monsters inside dungeon');c.profile=JSON.parse(JSON.stringify(persisted));c.L={mode:'world'};c.releaseRedPortalBreaks();assert.equal(c.enemies.length,6);assert(c.enemies.every(e=>e.breaker&&e.wild));assert.equal(persisted.pendingRedBreaks103.length,0);c.releaseRedPortalBreaks();assert.equal(c.enemies.length,6);
level(false);assert(!c.failRedPortalOnDeath());c.L.special={kind:'tower'};c.L.gate={id:-1,red:true};assert(!c.failRedPortalOnDeath());c.L.gate.ref={id:22,seed:3,red:true,rank:1,x:12,z:22};assert(c.failRedPortalOnDeath());assert(c.L.gate.ref.dead);
Object.assign(c,{cons:()=>10,npcHas:()=>false,recordNemesis(){},expAbandon(){},setTimeout(){},RANKS:[{id:'F',c:'#fff'}],rkN:()=> 'F'});vm.runInContext(extract('die'),c);level();c.profile={rank:0};c.L.gate={id:30,seed:1,rank:0,x:1,z:1,red:true};c.player.hp=c.player.maxhp=100;c.run.gold=100;c.run.xp=100;c.die();assert(!c.player.dead);assert(!c.L.gate.dead);assert(!c.profile.pendingRedBreaks103);c.die();assert(c.player.dead&&c.L.gate.dead);assert.equal(c.run.gold,80);assert.equal(c.run.xp,50);assert.equal(persisted.pendingRedBreaks103.length,1);assert(src.includes('cleared=L.bossDead&&!L.failed103'));console.log('PASS red death removes entrance and queues one world outbreak across reload; no premature spawn, no duplicate, no blue/tower false positive; class revival is not death; normal death penalties retained; failed clears excluded');
