const fs=require('fs'),vm=require('vm'),assert=require('assert'),src=fs.readFileSync(__dirname+'/../game.html','utf8'),base=fs.readFileSync(__dirname+'/verify-v95.cjs','utf8');eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')).replace("src.indexOf('{',m.index)","src.indexOf('{',m.index+m[0].length)"));
const events=[],c={profile:{rank:0},CFG:{},player:{x:0,z:0,hp:30,maxhp:100},run:{gold:1000,quests:[]},L:{mode:'world'},WX:{type:'clear'},isNight:()=>false,inCity:()=>false,NR105:{queue:[]},toast(){},saveRun(){},store:{set(){}},fmt:String,affL:()=>0,ensureOrderRep(){},questOrderRep:()=>5,genQuest:t=>({t,n:5,got:0}),addOrderRep(){},beep(){},refreshStats(){},fxRing(){},sfx(){},statTxt:()=>'',floater(){},FX2:{perfCd:0},bigText(){},Math:Object.create(Math),scene:{remove(){}},projs:[],hazards:[],enemies:[],placeAllies(){},cam:{},bossLight:{},$:()=>({}),dungeonFloorAt:()=>0,allies:[],expReward(){},expCargoWeight:s=>s.cargo.length,bossE:null};vm.createContext(c);vm.runInContext(src.slice(src.indexOf('const NR_LINES105='),src.indexOf('const RARE103=')),c);for(const n of ['narratorMemory105','narratorTone105','narratorChoose105','narratorContext105'])vm.runInContext(extract(n),c);c.narratorEvent105=(kind,data)=>events.push({kind,data});const bank=vm.runInContext('NR_LINES105',c),meta=vm.runInContext('NR_META107',c);assert.equal(Object.keys(bank).length,60);assert.equal(Object.keys(meta).length,40);const lines=Object.values(bank).flat();assert.equal(lines.length,2000);assert.equal(new Set(lines).size,2000);assert(lines.every(l=>typeof l==='string'&&l.length>15&&!/[<>\[\]{}]/.test(l)));
for(const k of Object.keys(meta)){assert.equal(bank[k].length,40);assert(meta[k].name);c.profile={rank:0};const m=c.narratorMemory105();m.recent=Array(12).fill('victory');c.CFG.narratorTease105=false;for(let i=0;i<30;i++){m.sequence++;let l=c.narratorChoose105({kind:k},m);assert(l,k);assert.notEqual(l.tone,'playful');assert(!Object.hasOwn(m.seen,l.id));m.seen[l.id]=0}assert.equal(c.narratorChoose105({kind:k},m),null);c.CFG.narratorTease105=true;for(let i=0;i<10;i++){m.sequence++;let l=c.narratorChoose105({kind:k},m);assert(l,k);assert.equal(l.tone,'playful');m.seen[l.id]=0}assert.equal(c.narratorChoose105({kind:k},m),null)}
for(const n of ['claimOrderQuest','finishEquipmentUpgrade','perfectDodge','useDungeonStairs','expFinishChallenge'])vm.runInContext(extract(n),c);
for(const [t,k] of [['kill','order_kill'],['clear','order_clear'],['pvp','order_pvp']]){events.length=0;c.run.quests=[{t,n:2,got:1,rw:10}];assert(!c.claimOrderQuest(0));assert.equal(events.length,0);c.run.quests[0].got=2;assert(c.claimOrderQuest(0));assert.equal(events[0].kind,k);assert(!c.claimOrderQuest(0));assert.equal(events.length,1)}
events.length=0;c.Math.random=()=>0;let eq={up:10,name:'Lâmina',value:100};assert(!c.finishEquipmentUpgrade(eq));assert.equal(eq.up,10);assert.equal(events.at(-1).kind,'upgrade_fail');assert(c.finishEquipmentUpgrade(eq,true));assert.equal(eq.up,11);assert.equal(events.at(-1).kind,'upgrade_win');
events.length=0;c.FX2.perfCd=1;c.perfectDodge();assert.equal(events.length,0);c.FX2.perfCd=0;c.perfectDodge();assert.equal(events[0].kind,'dodge');c.perfectDodge();assert.equal(events.length,1);
events.length=0;const it={x:0,z:0,r:3,room:0,to:1,forward:true,landing:{wx:0,wz:80}};c.L={mode:'dungeon',gate:{id:1,seed:3},floors:{current:0},inter:[it]};c.enemies=[{room:0,dead:false}];assert(!c.useDungeonStairs(it));assert.equal(events.length,0);c.enemies=[];assert(c.useDungeonStairs(it));assert.equal(events[0].kind,'stairs_up');assert(c.narratorContext105(events[0]));c.L.gate={id:2,seed:4};assert(!c.narratorContext105(events[0]));c.L.gate={id:1,seed:3};c.L.floors.current=0;assert(!c.narratorContext105(events[0]));
for(const [kind,k] of [['purify','purify'],['destroy','destroyfocus']]){events.length=0;c.L={expedition:{s:{foci:[{kind:0,status:'active'}]},challenge:{kind,node:{index:0,grp:{}}}}};c.EXP_FOCI=[{id:'x',n:'Foco'}];c.expFinishChallenge();assert.equal(events[0].kind,k);c.expFinishChallenge();assert.equal(events.length,1)}
events.length=0;c.L={expedition:{s:{sent:0,cargo:['ore']},challenge:{kind:'send'}}};c.expFinishChallenge();assert.equal(events[0].kind,'sendcargo');assert.equal(c.L.expedition.s.sent,1);c.expFinishChallenge();assert.equal(events.length,1);
c.L={mode:'world'};c.WX.type='rain';assert(c.narratorContext105({kind:'rain'}));assert(!c.narratorContext105({kind:'snow'}));c.L.mode='dungeon';assert(!c.narratorContext105({kind:'rain'}));c.L={mode:'world'};assert(c.narratorContext105({kind:'dawn'}));assert(!c.narratorContext105({kind:'night'}));c.isNight=()=>true;assert(c.narratorContext105({kind:'night'}));assert(!c.narratorContext105({kind:'dawn'}));c.L={mode:'dungeon',defense:{failed:true}};assert(c.narratorContext105({kind:'core_fail'}));c.L={mode:'world'};assert(!c.narratorContext105({kind:'core_fail'}));
c.profile={rank:0};let m=c.narratorMemory105();m.seen['victory:0']=15;m.counts.victory=3;m.facts=[{kind:'victory',rank:0,at:15}];let saved=JSON.stringify(c.profile);c.profile=JSON.parse(saved);assert.equal(c.narratorMemory105().seen['victory:0'],15);assert.equal(c.narratorMemory105().counts.victory,3);assert.equal(bank.victory[0],'A passagem fechou. Você ficou deste lado.');
console.log('PASS 2000 unique complete texts / 60 contexts; 40 new context labels; every new pool exhausts 30 non-teasing + 10 opt-in lines before repeat; real quest/forge/dodge/stairs/extraction success and failure hooks; no failed-action narratives; weather/region/floor validity; original save memory and line IDs preserved');
// A abertura do Mímico nunca deve narrar um tesouro recebido.
Object.assign(c,{mkEnemy:()=>({}),makeElite(){},GR:[{hp:1,dmg:1,xp:1,gold:1}],rnd:()=>50,fxBurst(){},hasT:()=>false,rollItem:()=>({}),addItem(){}});vm.runInContext(extract('openChest'),c);c.L={mode:'dungeon'};events.length=0;c.Math.random=()=>0;c.openChest(0,0,0,false);assert.deepEqual(events.map(e=>e.kind),['mimic']);events.length=0;c.Math.random=()=>1;c.openChest(0,0,0,false);assert.deepEqual(events.map(e=>e.kind),['treasure']);console.log('PASS actual mimic-versus-treasure mutually exclusive narration');
