const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8'),base=fs.readFileSync(__dirname+'/verify-v95.cjs','utf8');
eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')).replace("src.indexOf('{',m.index)","src.indexOf('{',m.index+m[0].length)"));
for(const file of ['game.html','index.html'])for(const m of fs.readFileSync(__dirname+'/../'+file,'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))if(m[1].trim())new vm.Script(m[1]);
const log=[],noop=()=>{},model=()=>({root:{position:{set:noop},scale:{setScalar:noop}},body:{scale:{setScalar:noop}},mats:[]});
const c={console,Math,Set,Map,profile:{cls:0,rank:8,jobs:[0]},run:{level:100,skl:{},adv:true,lib:[],stolen:[]},AR103:{},L:{mode:'world',inter:[]},time:10,player:null,enemies:[],allies:[],gates:[],paused:false,store:{set:noop},scene:{remove:noop},MAGIC_CLS:[5,6,7,8,9,10,11,12,13,16,18,19,20],RANKS:Array.from({length:10},(_,i)=>({id:i})),GR:Array.from({length:10},(_,i)=>({id:i})),CLASSES:Array.from({length:15},(_,i)=>({n:'C'+i,sk:[{col:123}]})),RARE103:Array.from({length:6},(_,i)=>({id:i+15,n:'R'+i})),ELEM:{},CLASS_SLOTS:[0,1,2,4,5,6],ADV:Array.from({length:21},()=>({sk:{}})),S:(n,t,cd,mp,pow,col)=>({n,t,cd,mp,pow,col}),hasAff:()=>false,healerLevel:s=>Math.min(10,c.run.skl[s.n]||0),preciseNumber:String,fmt:Math.round,skillCooldown:s=>s.cd,skillCooldownText:s=>String(s.cd),skillDamage:s=>100*s.pow,toast:x=>log.push(x),floater:noop,fxRing:noop,fxSlash:noop,fxBurst:noop,zig:noop,waveFwd:noop,sfx:noop,narratorSkill105:noop,narratorEvent105:noop,dprog:noop,saveRun:noop,freeAt:()=>true,los:()=>true,skillGroundPoint:(max=12,fallback=6)=>({x:0,z:Math.min(max,fallback)}),faceTarget:noop,canRedistribute:()=>true,inCity:()=>false,showG:noop,closeModal:noop,skillsView:noop,playerModel:()=>({m:model(),aura:{}}),statsFor:()=>({maxhp:100,maxmp:500,dmg:100}),gearLook:noop,row:(a,b,d)=>a+' '+b+' '+d,btn:()=>'',shoot:(...a)=>log.push(['shot',...a]),setStealth:noop,minionAllies:()=>c.allies.filter(a=>a.permanentSummon&&!a.dead),summonCap:()=>8,spawnSummon:(kind,x,z,life)=>{const a={x,z,life,maxhp:100,hp:50,dmg:20,r:.5,cd:0,m:model(),permanentSummon:true,summonKind:kind};c.allies.push(a);return a},hurtEnemy:(e,d,x,z,o)=>{assert.equal(o.stun,0);assert.equal(o.kb,0);e.hp-=d;log.push(['hit',d]);return d},moveEnt:(e,x,z)=>{e.x+=x;e.z+=z},pushOut:noop,rareSkillRun103:s=>log.push(['rare',s.t]),rareCastCheck103:()=>'',rareGateView103:noop,animChibi:noop,nearestEnemy:(x,z,r)=>c.enemies.find(e=>!e.dead&&Math.hypot(e.x-x,e.z-z)<=r),jobsOf:()=>c.profile.jobs,classSlotCount:()=>6};
vm.createContext(c);vm.runInContext(src.slice(src.indexOf('// BEGIN CATALOG111'),src.indexOf('// END CATALOG111')),c);c.KIT_DEFS111=vm.runInContext('KIT_DEFS111',c);vm.runInContext(fs.readFileSync(__dirname+'/kit111-runtime.js','utf8'),c);
for(const n of ['awakening103','rareActive103','affinity103','healingShield','guardianState108','guardianAim108','guardianLanding108','guardianPoint108','guardianReach108','guardianDamage108','guardianAbsorb108','guardianCharge108','guardianWard108','classSkill','learnedSkills','classLoadout','pSkills','useSkill','rareEligible103','kitMigrate111'])vm.runInContext(extract(n),c);
c.kitDeviceLook111=()=>{};
function reset(){c.profile={cls:0,rank:8,jobs:Object.keys(c.KIT_DEFS111).map(Number),awakening103:{unlocked:[7,12,13,14,15,16,17,18,19,20],points:Object.fromEntries([7,12,13,14,15,16,17,18,19,20].map(i=>[i,9])),total:90,discovered:true,energy:50,essences:[]},forms111:['feral','alada','blindada','agil']};c.run={level:100,skl:{},adv:true,lib:[],stolen:[],jobData:Object.fromEntries(Object.keys(c.KIT_DEFS111).map(i=>[i,{adv:true}]))};c.player={x:0,z:0,r:.5,face:0,hp:40,maxhp:100,mp:500,maxmp:500,dmg:100,iT:0,m:model(),skills:Object.values(c.KIT_DEFS111).flat().map(s=>({...s,cdT:0}))};c.L={mode:'world',inter:[]};c.AR103={region:c.L,reserve:3};c.enemies=[{x:0,z:3,r:.5,hp:10000,maxhp:10000,cd:0,act:{wind:1,t:0},m:model()}];c.allies=[{x:0,z:3,r:.5,hp:40,maxhp:100,life:99,permanentSummon:true,shadow:true,summonKind:'skel',m:model(),dmg:20,cd:0}];c.time=10;c.freeAt=()=>true;c.los=()=>true;c.hasAff=()=>false;log.length=0;}
reset();const catalog=Object.values(c.KIT_DEFS111).flat();assert.equal(catalog.length,160);assert.equal(new Set(catalog.map(s=>s.n)).size,160);assert.equal(new Set(catalog.map(s=>s.skillId)).size,160);for(const list of Object.values(c.KIT_DEFS111))assert.equal(list.length,8);assert(c.RARE103.every(r=>r.ready));
// Exercise every actual handler and description, including resources, without hidden no-op fallbacks.
for(const original of catalog){reset();const s={...original};c.profile.awakening103.affinity=s.sourceClass;const k=c.kitState111();k.energy=6;k.counters=2;k.captured=1;k.lastAttack=c.KIT_DEFS111[0][0];k.history=[{t:8,hp:100}];const g=c.guardianState108();g.links=[{target:c.allies[0],until:30}];if(['repair','dismantle','detonate','relocate'].includes(s.effect)){c.allies[0].kitDevice111='turret';}if(s.effect==='gate'){assert.equal(c.kitCheck111(s),'');continue}assert(c.kitDescription111(s).length>40,s.n);assert(!c.kitDescription111(s).includes('undefined'),s.n);try{c.kitRun111(s);c.kitUpdate111(.1)}catch(e){throw new Error(s.n+': '+e.stack)}}
reset();c.profile.jobs=[5];c.profile.cls=5;c.run.adv=false;c.run.jobData={};c.run.level=1;assert.equal(c.learnedSkills().length,3);c.run.level=45;assert.equal(c.learnedSkills().length,5);c.run.level=1;assert.equal(c.learnedSkills().length,5);c.run.lib=[{n:'Sol Nascente'}];assert(c.learnedSkills().some(s=>s.n==='Sol Nascente'));c.run.classLoadout=['5:0','5:1','5:2','5:3','5:4','5:5'];assert.equal(c.pSkills().filter(s=>!s.empty).length,6);assert(c.pSkills()[3].empty);
reset();c.profile.jobs=[15];c.profile.awakening103.points[15]=1;assert.equal(c.learnedSkills().length,3);c.profile.awakening103.points[15]=6;assert.equal(c.learnedSkills().length,8);c.profile.awakening103.points[15]=0;assert.equal(c.learnedSkills().length,8);
reset();c.profile.jobs=[0];c.run.level=1;c.run.adv=true;c.run.classLoadout=['0:0','0:1','0:2','0:3',null,null];c.player.skills=c.pSkills();assert(c.player.skills[3].empty);const evo=c.player.skills.find(s=>s.n==='Lâmina Rúnica');c.useSkill({n:'Lâmina Rúnica'});assert(evo.cdT>0);const mana=c.player.mp;c.useSkill({n:'Lâmina Rúnica'});assert.equal(c.player.mp,mana);
reset();let s=c.KIT_DEFS111[0][1];const hp=c.enemies[0].hp;c.kitRun111(s);assert.equal(c.enemies[0].hp,hp);assert.equal(c.player.iT,0);assert(c.player.z>0);
reset();c.kitRun111(c.KIT_DEFS111[5][0]);assert.equal(c.player.hp,90);assert.equal(c.player.healShield,undefined);c.kitRun111(c.KIT_DEFS111[5][4]);assert.equal(c.player.hp,90);assert.equal(c.player.healShield,20);c.kitRun111(c.KIT_DEFS111[5][1]);assert.equal(c.player.hp,90);
reset();c.hasAff=()=>true;assert(c.kitCheck111(c.KIT_DEFS111[5][0]));c.kitRun111(c.KIT_DEFS111[5][0]);assert.equal(c.player.hp,40);c.hasAff=()=>false;c.freeAt=()=>false;assert(c.kitCheck111(c.KIT_DEFS111[0][1]));
reset();s=c.KIT_DEFS111[12][0];c.kitCast111(s={...s});assert.equal(c.player.mp,480);c.player.z=6;c.player.hp=10;c.kitCast111(s);assert.equal(c.player.z,0);assert.equal(c.player.hp,10);assert.equal(c.player.mp,480);
reset();c.kitRun111(c.KIT_DEFS111[14][0]);const g=c.guardianState108();assert.equal(g.links.length,1);c.kitRun111(c.KIT_DEFS111[14][1]);assert.equal(c.player.healShield,undefined);c.kitRun111(c.KIT_DEFS111[14][2]);assert.equal(g.oath,null);assert.equal(c.player.kitGuard111.amount,.4);
reset();c.kitWalk111(3.9);assert.equal(c.kitState111().energy,0);c.kitWalk111(.1);assert.equal(c.kitState111().energy,1);c.kitWalk111(100);assert.equal(c.kitState111().energy,3);c.profile.awakening103.affinity=18;c.kitWalk111(24);assert.equal(c.kitState111().energy,6);const mp=c.player.mp;c.kitCast111({...c.KIT_DEFS111[18][0],cdT:0});assert.equal(c.player.mp,mp);assert.equal(c.kitState111().energy,5);
reset();c.kitRun111(c.KIT_DEFS111[17][0]);assert.equal(c.kitIncoming111(c.player,100,false),100);assert.equal(c.kitState111().counters,0);assert.equal(c.kitIncoming111(c.player,100,true),0);assert.equal(c.kitState111().counters,1);assert.equal(c.kitIncoming111(c.player,100,true),100);
reset();c.kitRun111(c.KIT_DEFS111[20][0]);const p={team:'enemy',x:0,z:0,vx:0,vz:30};assert(!c.kitCapture111({...p,fromBoss111:true},.1));assert(c.kitCapture111(p,.1));assert(!c.kitCapture111(p,.1));c.kitRun111(c.KIT_DEFS111[20][1]);assert.equal(c.kitState111().captured,0);
reset();c.kitRun111(c.KIT_DEFS111[16][0]);c.kitRun111(c.KIT_DEFS111[16][1]);assert.equal(c.kitDevices111().length,2);assert(c.kitCheck111(c.KIT_DEFS111[16][2]));c.profile.awakening103.affinity=16;assert.equal(c.kitCheck111(c.KIT_DEFS111[16][2]),'');c.kitRun111(c.KIT_DEFS111[16][2]);assert.equal(c.kitDevices111().length,3);
reset();c.kitRun111(c.KIT_DEFS111[15][0]);assert(c.kitFormAttack111());c.kitRun111(c.KIT_DEFS111[15][0]);assert(!c.kitFormAttack111());assert.equal(c.kitForms111().length,2);c.profile.awakening103.affinity=15;assert.equal(c.kitForms111().length,4);
reset();c.kitRun111(c.KIT_DEFS111[10][4]);const zone=c.kitState111().zones[0];const e=c.enemies[0];e.x=zone.x;e.z=zone.z-3;assert(c.kitBlocked111(e,zone.x,zone.z));assert(!c.kitBlocked111(c.player,zone.x,zone.z));e.isBoss=true;assert(!c.kitBlocked111(e,zone.x,zone.z));
reset();c.profile.cls=3;c.profile.jobs=[3];c.run.elem='gelo';c.run.classLoadout=['3:0','3:1','3:2'];c.kitMigrate111();assert.equal(c.profile.cls,9);assert.equal(c.run.classLoadout.join(','),'9:0,9:1,9:2');assert.equal(c.player.hp,40);
reset();c.kitState111().energy=3;c.L={mode:'world'};assert.equal(c.kitState111().energy,0);c.player.dead=true;c.kitUpdate111(.1);assert.equal(c.AR103.kit111,null);
reset();c.profile.rank=0;c.profile.awakening103.total=3;c.profile.awakening103.unlocked=[];for(const ci of [7,12,13,14,15,16,17,18,19,20])assert(c.rareEligible103(ci),'F can learn '+ci);c.profile.awakening103.total=2;assert(!c.rareEligible103(20));
reset();c.ADV[9]={sk:{n:'Era do Gelo',t:'nova',pow:3}};assert(c.kitCanonical111({n:'Era do Gelo',t:'nova',pow:3}));assert.equal(c.kitCanonical111({n:'Era do Gelo',t:'nova',pow:6}),null,'absorbed sovereign power remains independent');c.run.stolen=[{n:'Era do Gelo',t:'nova',pow:3},{n:'Era do Gelo',t:'nova',pow:6}];c.kitArchive111();assert.equal(c.run.stolen.length,1);assert.equal(c.run.stolen[0].pow,6);
reset();c.kitWard111(c.player,.4,6);c.time++;c.kitWard111(c.player,.1,20);assert.equal(c.player.healShield,40);assert.equal(c.player.healShieldUntil,16,'weak shield cannot extend strong one');
reset();c.ADV[9]={sk:{n:'Era do Gelo',t:'nova',pow:3}};c.run.lib=[{n:'Era do Gelo',t:'nova',pow:3}];c.run.stolen=[{n:'Era do Gelo',t:'nova',pow:6}];vm.runInContext(extract('powLib'),c);assert.equal(c.powLib()[0].pow,6);assert.equal(c.loadedPower111('Era do Gelo',c.run.lib).pow,6);assert.equal(c.loadedPower111('Era do Gelo',[c.run.lib[0]]).pow,3);
// Real damage entry points, not mocked hit amounts.
Object.assign(c,{curAtk:null,pb:()=>0,gearRuneCount:()=>0,hasT:()=>false,shake:noop,flashMats:noop,$:()=>({style:{}}),setTimeout:noop,perfectDodge:noop,die:()=>{c.player.dead=true}});
for(const n of ['absorbHealingShield','allyProtection','hurtPlayer','hurtAlly'])vm.runInContext(extract(n),c);
reset();Object.assign(c.player,{def:0,iT:0,shield:0,guard:0,hp:100});c.kitRun111(c.KIT_DEFS111[17][0]);c.hurtPlayer(100,true);assert.equal(c.player.hp,100);assert.equal(c.kitState111().counters,1);c.kitRun111(c.KIT_DEFS111[5][2]);c.hurtPlayer(100,false);assert.equal(c.player.hp,60,'60% self reduction');
reset();Object.assign(c.player,{def:0,iT:0,shield:0,guard:0,hp:100});c.allies[0].hp=100;c.guardianState108().links=[{target:c.allies[0],until:30}];c.hurtAlly(c.allies[0],100);assert.equal(c.allies[0].hp,30);assert.equal(c.player.hp,85,'only half transferred damage');
console.log('PASS: 160 handlers/descriptions, 20x8 catalogue, all rare paths at rank F, persistent progression, six slots/evolution cooldown, isolated healing/ward/movement, no-cure/walls, temporal return, real damage/guardian transfer, energy, parry, capture, constructs, forms, barriers, legacy migration, absorbed-power name collision, weak-shield refresh protection, death/region cleanup.');
