const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8');
function extract(n){const m=new RegExp('function\\s+'+n+'\\s*\\([^)]*\\)').exec(src);assert(m,n);let b=src.indexOf('{',m.index),d=0,q=null,e=false;for(let i=b;i<src.length;i++){let c=src[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;if(c==='}'&&!--d)return src.slice(m.index,i+1)}}





const c={player:{x:0,z:0,maxhp:100,hp:0,dmg:100},allies:[],enemies:[],hazards:[],time:10,run:{level:30,summons:[]},RANKS:[{mult:1}],rankOf:()=>0,skillGroundPoint:()=>({x:5,z:5}),hasAff:()=>false,freeAt:()=>true,summonCap:()=>4,minionAllies:()=>c.allies.filter(a=>!a.dead),saveRun(){},fxRing(){},pillar(){},circle(){},spikes(){},fallFx(){},hurtEnemy(e,d){e.damage=d},toon(){},scene:{add(){},remove(){}},makeChibi(){return {root:{position:{set(){}}},body:{scale:{setScalar(){}}},mats:[]}},makeStoneColossus(){return c.makeChibi()},makeSpiritWolf(){return c.makeChibi()},hazard(x,z,r,dur,dmg,team,col){const h={x,z,r,dur,dmg,team,col,t:0,fill:{scale:{setScalar(){}}},g:{traverse(){}}};c.hazards.push(h);return h}};c.AR103={};Object.assign(c,{narratorEvent105(){},narratorSkill105(){},narratorDeath105(){},narratorPortal105(){}});vm.createContext(c);for(const n of ['magicEvolution','solarHeal','spawnSummon','savedSummons','restoreSummons'])vm.runInContext(extract(n),c);
for(const [name,count] of [['Meteoro',1],['Sol Negro',5],['Era do Gelo',4],['Fúria dos Céus',3]]){c.hazards=[];assert(c.magicEvolution({n:name,col:1},600));assert.equal(c.hazards.length,count);assert.equal(c.hazards.reduce((s,h)=>s+h.dmg,0),600);assert(c.hazards.every(h=>h.x===5&&h.z===5&&h.stun===0));if(name==='Era do Gelo')assert(c.hazards.every(h=>h.slow===2));}
c.hazards=[];c.allies=[{x:2,z:0,maxhp:100,hp:0},{x:8,z:0,maxhp:100,hp:0},{x:1,z:0,maxhp:100,hp:0,dead:true}];c.magicEvolution({n:'Sol Nascente',pow:.7,col:1},0);assert.equal(c.player.hp,35);assert.equal(c.allies[0].hp,35);assert.equal(c.allies[1].hp,0);assert.equal(c.allies[2].hp,0);for(const h of c.hazards)c.solarHeal(h.x,h.z,h.r,h.healFraction);assert(Math.abs(c.player.hp-70)<1e-8);c.hasAff=()=>true;c.solarHeal(0,0,6,1);assert(Math.abs(c.player.hp-70)<1e-8);
c.enemies=[{x:2,z:0,r:1},{x:20,z:0,r:1}];c.magicEvolution({n:'Domínio dos Ecos',col:1},600);assert.equal(c.enemies[0].echoMarkUntil,18);assert.equal(c.enemies[0].damage,600);assert.equal(c.enemies[1].damage,undefined);
c.allies=[];c.magicEvolution({n:'Colosso de Pedra',col:1},0);assert.equal(c.allies.length,1);const g=c.allies[0];assert.equal(g.summonKind,'golem');assert.equal(g.maxhp,80*(1+30*.04)*3);assert.equal(g.dmg,140);g.hp=123;c.run.summons=JSON.parse(JSON.stringify(c.savedSummons()));c.allies=[];c.restoreSummons();assert.equal(c.allies[0].hp,123);assert.equal(c.allies[0].summonKind,'golem');assert.equal(c.allies[0].speed,3.8);
c.magicEvolution({n:'Matilha Espiritual',col:1},0);assert.equal(c.allies.length,4);assert.equal(c.allies.filter(a=>a.summonKind==='wolf'&&a.buffT===8).length,3);c.allies[1].hp=10;c.magicEvolution({n:'Matilha Espiritual',col:1},0);assert.equal(c.allies.length,4);assert.equal(c.allies[1].hp,10);
console.log('PASS ground spell patterns and total damage, slow without stun, solar healing radius/dead/no-cure, eco mark, golem stats/save, pack cap and refresh without healing');

Object.assign(c,{paused:false,floater(){},nearestEnemy:()=>null,skillCooldown:()=>8,runSkill(){c.casts=(c.casts||0)+1}});c.player.mp=100;c.hasAff=()=>false;vm.runInContext(extract('useSkill'),c);let sk={n:'Fúria dos Céus',t:'chain',mp:30,cdT:0};c.useSkill(sk);assert.equal(c.player.mp,70);assert.equal(c.casts,1);sk={n:'Corrente de Raios',t:'chain',mp:20,cdT:0};c.useSkill(sk);assert.equal(c.player.mp,70);c.allies=Array.from({length:4},()=>({summonKind:'golem'}));sk={n:'Matilha Espiritual',t:'summon',mp:40,cdT:0};c.useSkill(sk);assert.equal(c.player.mp,70);c.allies[0].summonKind='wolf';c.useSkill(sk);assert.equal(c.player.mp,30);assert.equal(c.casts,2);
console.log('PASS actual cast validation: advanced lightning without target, basic chain unchanged, full pack buff only when wolves exist');
