const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8');
function extract(n){const m=new RegExp('function\\s+'+n+'\\s*\\([^)]*\\)').exec(src);assert(m,n);let b=src.indexOf('{',m.index),d=0,q=null,e=false;for(let i=b;i<src.length;i++){let c=src[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;if(c==='}'&&!--d)return src.slice(m.index,i+1)}}

let saves=0,bosses=0,waves=0;
const c={profile:{rank:0,guildClaims:2},run:{level:8},L:{},player:{},enemies:[],TOPR:8,GR:[1,8,20,35,55,80,120,180,220,260].map(lvl=>({lvl})),RANKS:'F E D C B A S SS SS+ â˜…'.split(' ').map(id=>({id})),store:{set(){saves++}},S2(){return {}},spawnBoss(x,z,rank,B){bosses++;assert.equal(B.n,'Examinador do Rank E');return {}},spawnWave(){waves++},bossAggro(){},toast(){},npcEv(){},storyEv(){}};
vm.createContext(c);
for(const n of ['rankPortalCount','qualifyingRankPortals', 'recordRankPortal','rankTrialReady','updateRankExaminer','updSpecial','qev'])vm.runInContext(extract(n),c);
c.profile.closedPortalsByRank={0:10,1:2};assert(!c.rankTrialReady(1));c.profile.closedPortalsByRank[2]=1;assert(c.rankTrialReady(1));c.run.level=7;assert(!c.rankTrialReady(1));c.run.level=8;c.profile.guildClaims=1;assert(!c.rankTrialReady(1));c.profile.guildClaims=2;assert(!c.rankTrialReady(2));
c.profile.rank=1;c.profile.guildClaims=4;c.run.level=20;c.profile.closedPortalsByRank={1:100,2:2};assert(!c.rankTrialReady(2));c.profile.closedPortalsByRank[3]=1;assert(c.rankTrialReady(2));c.profile.rank=8;c.run.level=999;c.profile.guildClaims=99;c.profile.closedPortalsByRank[9]=10;assert(!c.rankTrialReady(9));
c.profile.closedPortalsByRank={};c.L={gate:{rank:1},bossDead:false};assert(!c.recordRankPortal(1));c.L.bossDead=true;assert(!c.recordRankPortal(0));c.L.special={};assert(!c.recordRankPortal(1));delete c.L.special;c.qev('clear',1);assert.equal(c.rankPortalCount(1),1);c.qev('clear',1);assert.equal(c.rankPortalCount(1),1);assert.equal(saves,1);c.profile=JSON.parse(JSON.stringify(c.profile));assert.equal(c.rankPortalCount(1),1);
c.L={rankTrial:1,special:{kind:'job',stage:0,t:0,gr:1}};c.updSpecial(2);assert.equal(bosses,0);c.updSpecial(1);assert.equal(bosses,1);assert.equal(waves,0);c.updSpecial(1);assert.equal(bosses,1);assert.equal(waves,0);assert.equal(c.L.special.msg,'Derrote o Examinador do Rank E');c.L={special:{kind:'job',stage:0,t:0,gr:1}};c.updSpecial(3);assert.equal(waves,1);
Object.assign(c,{rememberClassCooldowns(){},pSkills:()=>[],showG(){},refreshStats(){},bigText(){},sfx(){},setTimeout(){},saveRun(){}});c.player={maxhp:100,aura:{material:{color:{set(){}}}}};c.profile.rank=0;c.L={rankTrial:1};vm.runInContext(extract('completeJob'),c);c.completeJob();assert.equal(c.profile.rank,1);assert.equal(c.L.rankTrial,0);assert.equal(c.player.hp,100);
console.log('PASS target rank portals E onward, level/tasks, exact completed portal, duplicate/special exclusion, save, direct single examiner, normal class waves preserved, promotion');
