const fs=require('fs'),vm=require('vm'),assert=require('assert');const src=fs.readFileSync('game.html','utf8'),base=fs.readFileSync('tools/verify-v95.cjs','utf8');eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')));
for(const file of ['game.html','index.html','goblin-preview.html'])for(const m of fs.readFileSync(file,'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))if(m[1].trim())new vm.Script(m[1]);
const calls=[],c={shoot:(...a)=>calls.push(a),L:{mode:'world'},player:{x:0,z:0,dead:false},profile:{rank:0},gateSeq:0,inCity:()=>true,closeModal(){},buildDungeon:g=>calls.push(g)};vm.createContext(c);for(const n of ['goblinShot118','enterGoblin118'])vm.runInContext(extract(n),c);
c.goblinShot118({kind:'gobArcher118',x:1,z:2,face:0,dmg:8});assert.equal(calls[0][7],'arrow');assert.equal(calls[0][3],18);assert.equal(calls[0][5],'enemy');assert.equal(calls[0][4],8);
c.goblinShot118({kind:'gobShaman118',x:1,z:2,face:0,dmg:10});assert.equal(calls[1][7],'orb');c.goblinShot118({kind:'mage',x:1,z:2,face:0,dmg:10});assert.equal(calls[2][7],'orb');
for(let rank=0;rank<10;rank++){c.profile.rank=rank;assert(c.enterGoblin118());const g=calls.at(-1);assert.equal(g.rank,rank);assert(g.goblin118);assert.equal(g.expType,'standard');assert(!g.red);assert(!g.double)}
c.L.mode='dungeon';assert(!c.enterGoblin118());c.L.mode='world';c.player.dead=true;assert(!c.enterGoblin118());c.player.dead=false;c.inCity=()=>false;assert(!c.enterGoblin118());
assert(src.includes("else goblinShot118(e)"));assert(src.includes("if(o.goblin118)return makeGoblin118(o)"));assert(src.includes("if(B.goblin118)e.mech='costas'"));assert(src.includes('!goblinDungeon118(L.gate)'));assert(src.includes('goblinIndex118<5'));assert(src.includes("g.hostile=!goblinDungeon118(g)"));assert(src.includes("g.friends=!goblinDungeon118(g)"));
console.log('PASS source/generated/gallery parse; archers fire physical arrows with preserved damage/team; shamans/legacy casters keep orbs; prototype ranks F–star and city/alive guards; custom model route, five-type roster, no mixed hunters/mimics/boss fragments.');
