const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8');
const base=fs.readFileSync(__dirname+'/verify-v95.cjs','utf8');eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')));
const c={narratorEvent105(){},player:{},time:10,run:{skl:{}},hasAff:()=>false,fmt:Math.round,floater(){},fxRing(){},sfx(){},shake(){},gearRuneCount:()=>0,pb:()=>0,hasT:()=>false,curAtk:null,flashMats(){},setTimeout(){},$:()=>({style:{}}),die(){throw Error('Unexpected death')}};c.guardianDamage108=(a,n)=>n;vm.createContext(c);
for(const n of ['healerLevel','healingFraction','healingShieldCap','healingShield','absorbHealingShield','applyHealingLight','allyProtection','hurtAlly','hurtPlayer'])vm.runInContext(extract(n),c);
const sk={n:'Luz Curativa',pow:.35},unit=()=>({hp:100,maxhp:100,x:0,z:0,def:0,shield:30,maxsh:30,slowT:2,bleedT:3,bleedD:8});
let a=unit();a.hp=10;c.applyHealingLight(a,sk);assert.equal(a.hp,60);assert.equal(c.healingShield(a),0);assert.equal(a.slowT,2);assert.equal(a.bleedT,3);
a.hp=90;c.applyHealingLight(a,sk);assert.equal(a.hp,100);assert.equal(c.healingShield(a),0);assert.equal(a.shield,30);
c.hasAff=()=>true;a.hp=20;c.applyHealingLight(a,sk);assert.equal(a.hp,20);c.hasAff=()=>false;a.dead=true;c.applyHealingLight(a,sk);assert.equal(a.hp,20);
const ward=a=>{a.healShield=40;a.healShieldCap=.4;a.healShieldUntil=c.time+6};c.player=unit();ward(c.player);c.hurtPlayer(25);assert.equal(c.player.hp,100);assert.equal(c.player.shield,30);assert.equal(c.healingShield(c.player),15);c.hurtPlayer(30);assert.equal(c.player.shield,15);c.hurtPlayer(20);assert.equal(c.player.hp,95);
a=unit();ward(a);a.blessingUntil=30;c.hurtAlly(a,100);assert.equal(a.hp,70);assert.equal(c.healingShield(a),0);ward(a);c.time+=6;assert.equal(c.healingShield(a),0);
assert(!extract('saveRun').includes('healShield'));console.log('PASS revised healing-only behavior; shield engine separate from healing/equipment, real player/ally absorption, no-cure/dead exclusions and expiry; independent Aegis covered by v109');
