const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8'),base=fs.readFileSync(__dirname+'/verify-v95.cjs','utf8');
eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')).replace("src.indexOf('{',m.index)","src.indexOf('{',m.index+m[0].length)"));
for(const file of ['game.html','index.html'])for(const m of fs.readFileSync(__dirname+'/../'+file,'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))if(m[1].trim())new vm.Script(m[1]);
const c={time:10,profile:{rank:0,cls:5,jobs:[5],awakening103:{discovered:true,total:3,points:{14:1},unlocked:[14]}},run:{level:30,skl:{}},L:{mode:'world',inter:[]},AR103:{},allies:[],enemies:[],player:{x:0,z:0,r:.5,hp:1000,maxhp:1000,mp:1000,shield:0,def:0,stealth:0,skills:[]},paused:false,CLASSES:Array.from({length:12},(_,i)=>({n:'Class '+i,sk:[]})),S:(n,t,cd,mp,pow,col)=>({n,t,cd,mp,pow,col}),store:{set(){}},saveRun(){},canRedistribute:()=>true,toast(){},closeModal(){},scene:{remove(){}},sfx(){},fxRing(){},fxBurst(){},floater(){},fmt:Math.round,preciseNumber:String,gearRuneCount:()=>0,pb:()=>0,hasT:()=>false,hasAff:()=>false,shake(){},$:()=>({style:{}}),setTimeout(){},flashMats(){},curAtk:null,die(){c.player.dead=true},los:()=>true,freeAt:()=>true,skillGroundPoint:()=>c.aim,aim:{x:0,z:5},skillDamage:()=>0,skillCooldown:s=>s.cd,inspectFissure103(){},narratorEvent105(){},narratorSkill105(){},nearestEnemy:()=>null,document:{getElementById:()=>null},kindsFor:()=>[{k:'slime'}],spawnKind(k,x,z){const e={x,z,dmg:5,m:{root:{}}};c.enemies.push(e);return e},spawnShadow(b,x,z){const a={x,z,hp:100,maxhp:100,m:{root:{}}};c.allies.push(a);return a}};
vm.createContext(c);vm.runInContext(src.slice(src.indexOf('const RARE103='),src.indexOf('const BOSSES=')),c);
for(const n of [...src.matchAll(/function (guardian\w+108)\(/g)].map(m=>m[1]).concat(['awakening103','rareActive103','affinity103','rareEligible103','rareLearn103','rareAttune103','jobsOf','classSkill','rareCastCheck103','rareSkillRun103','rareMana103','useSkill','hurtPlayer','hurtAlly','allyProtection','absorbHealingShield','healingShield','startTrial103','finishTrial103','rareUpdate103','rareHud103','specialEcos103','pickTarget']))vm.runInContext(extract(n),c);
c.AR103.region=c.L;c.player.skills=c.CLASSES[14].sk.map((s,i)=>({...s,sourceClass:14,sourceSkill:i}));
const [link,interpose,oath]=c.player.skills;
const cast=sk=>{sk.cdT=0;c.useSkill(sk)};
const ally=(x=0,z=5)=>{const a={x,z,hp:1000,maxhp:1000,r:.5,m:{root:{}}};c.allies.push(a);return a};
let a=ally();cast(link);assert.equal(c.AR103.guardian108.links[0].target,a);c.hurtAlly(a,100);assert.equal(a.hp,930);assert.equal(c.player.hp,985);
// Shared damage cannot be evaded or reduced again, and can kill the protector.
c.player.iT=10;c.player.def=.9;c.hurtAlly(a,100);assert.equal(c.player.hp,970);c.player.iT=0;c.player.def=0;
let b=ally(2,5);c.aim=b;cast(link);assert.equal(c.AR103.guardian108.links.length,1);assert.equal(c.AR103.guardian108.links[0].target,b);
c.awakening103().affinity=14;c.aim=a;cast(link);assert.equal(c.AR103.guardian108.links.length,2);c.awakening103().affinity=12;assert.equal(c.guardianState108().links.length,1);
// Range and walls invalidate transfer immediately, before the next frame.
c.los=()=>false;let old=c.player.hp;c.hurtAlly(a,100);assert.equal(c.player.hp,old);c.los=()=>true;a.z=13;c.hurtAlly(a,100);assert.equal(c.player.hp,old);a.z=5;
// Solo anchor has a finite budget and does not multiply protection at affinity two.
c.allies=[];c.aim={x:0,z:5};cast(link);c.player.hp=1000;c.hurtPlayer(100);assert.equal(c.player.hp,930);assert.equal(c.AR103.guardian108.links[0].pool,270);
c.awakening103().affinity=14;cast(link);c.hurtPlayer(100);assert.equal(c.player.hp,860);assert.equal(c.AR103.guardian108.links.reduce((n,l)=>n+l.pool,0),540);
cast(oath);c.hurtPlayer(100);assert.equal(c.player.hp,810);assert.equal(c.AR103.guardian108.oath.charge,50);c.time+=6;c.guardianUpdate108();assert.equal(c.AR103.guardian108.oath,null);assert.equal(c.AR103.guardian108.wards[0].amount,150);c.guardianUpdate108();assert.equal(c.AR103.guardian108.wards[0].amount,150);
c.hurtPlayer(100);assert.equal(c.player.hp,810);assert.equal(c.AR103.guardian108.wards[0].amount,50);c.time+=7;c.guardianState108();assert.equal(c.AR103.guardian108.wards.length,0);
// Interposition validates its landing before spending mana, then shields allies.
cast(link);c.freeAt=()=>false;old=c.player.mp;cast(interpose);assert.equal(c.player.mp,old);assert(!interpose.cdT);c.freeAt=()=>true;a=ally();cast(interpose);assert.equal(c.player.z,5);assert.equal(c.AR103.guardian108.wards.find(w=>w.target===a).amount,200);cast(interpose);assert.equal(c.AR103.guardian108.wards.find(w=>w.target===a).amount,200);
// Oath cannot be recast while active; charge bounded, per-recipient shield capped.
cast(oath);old=c.player.mp;cast(oath);assert.equal(c.player.mp,old);c.guardianCharge108(c.AR103.guardian108,10000);a.maxhp=100;c.time+=6;c.guardianUpdate108();assert.equal(c.AR103.guardian108.wards.find(w=>w.target===a).amount,40);
// Unequip, region change, death, expiry and save have no stale defenses.
const skills=c.player.skills;c.player.skills=[];assert.equal(c.guardianDamage108(c.player,100),100);assert.equal(c.AR103.guardian108,null);c.player.skills=skills;cast(link);c.L={mode:'world',inter:[]};assert.equal(c.guardianDamage108(c.player,100),100);assert.equal(c.AR103.guardian108,null);c.AR103.region=c.L;c.player.dead=true;assert.equal(c.guardianState108(),null);c.player.dead=false;c.player.x=0;c.player.z=0;c.aim=a;cast(link);c.time+=21;assert.equal(c.guardianState108().links.length,0);
a.maxhp=a.hp=1000;c.aim=a;cast(link);c.player.hp=1;c.hurtAlly(a,100);assert(c.player.dead);assert.equal(a.hp,930);c.player.dead=false;c.player.hp=1000;c.AR103.guardian108=null;
// Protective investigation fails without reward if helper dies, then can be retried.
c.awakening103().pending={x:0,z:0,rank:0};assert(c.startTrial103(14));let t=c.AR103.trial;assert(t.helper.guardianTrial108);assert.equal(c.pickTarget({...t.targets[0],aw103:true,x:0,z:6}).t,t.helper);t.helper.dead=true;c.rareUpdate103(.1);assert.equal(c.AR103.trial,null);assert(c.awakening103().pending);assert.equal(c.awakening103().total,3);assert(c.startTrial103(14));t=c.AR103.trial;t.targets.forEach(e=>e.dead=true);c.rareUpdate103(12);assert.equal(c.awakening103().total,4);assert.equal(c.awakening103().points[14],2);assert.equal(c.awakening103().pending,null);
c.awakening103().unlocked=[];assert(c.rareLearn103(14));assert(c.profile.jobs.includes(14));const saved=JSON.stringify(c.profile);assert(!saved.includes('guardian108'));c.profile=JSON.parse(saved);assert(c.awakening103().unlocked.includes(14));assert.equal(c.profile.rank,0);
console.log('PASS Guardian: real damage transfer, lethal cost, evade/armor bypass, range/walls, affinity slots, finite solo absorption, no doubled mitigation, oath single wave/charge/caps, safe landing/no-spend, wards expiry/nonstacking, death/region/unequip cleanup, protective investigation failure/retry/success, rank-F learning and save migration. Source/generated scripts parse.');
