const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8');
function extract(n){const m=new RegExp('function\\s+'+n+'\\s*\\([^)]*\\)').exec(src);assert(m,n);let b=src.indexOf('{',m.index),d=0,q=null,e=false;for(let i=b;i<src.length;i++){let c=src[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;if(c==='}'&&!--d)return src.slice(m.index,i+1)}}


const shots=[];const c={player:{x:0,z:0,face:0,mp:100},skillDamage:()=>600,faceTarget(){},skillFx(){},sfx(){},shoot:(...a)=>shots.push(a)};vm.createContext(c);for(const n of ['runSkill','skillButtonState'])vm.runInContext(extract(n),c);
assert.equal(c.skillButtonState({empty:true},100).kind,'empty');assert.equal(c.skillButtonState({cdT:2.25,mp:5},0).text,'2.3s');assert.equal(c.skillButtonState({cdT:0,mp:5},0).text,'SEM MANA');assert.equal(c.skillButtonState({cdT:0,mp:5},5).text,'PRONTA');
c.runSkill({n:'Flecha Estelar',t:'bolt',col:1});assert.equal(shots.length,3);assert.equal(shots.reduce((s,x)=>s+x[4],0),600);assert.equal(new Set(shots.map(x=>x[2])).size,3);assert(shots.every(x=>x[8].pierce&&x[8].skillHit));shots.length=0;c.runSkill({n:'Flecha Perfurante',t:'bolt',col:2});assert.equal(shots.length,1);assert.equal(shots[0][4],600);
vm.runInContext(src.slice(src.indexOf('const RANK_TALENTS='),src.indexOf('function rankTalent(')),c);assert.equal(vm.runInContext('RANK_TALENTS.volley.max',c),5);assert.equal(vm.runInContext('RANK_TALENTS.bounce.max',c),8);assert.equal(vm.runInContext('RANK_TALENTS.sweep.max',c),8);
Object.assign(c,{profile:{rankTalents:Array(5).fill('volley').concat(Array(3).fill('reach'))},paused:false,basicAttackId:()=>4,CLASSES:{4:{ranged:true,wep:'bow',sk:[{col:1}]}},MAGIC_CLS:[],basicIsMagic:()=>false,basicDmgMul:()=>1,statsBonus:()=>({atk:1}),FX2:{counter:false},dprog(){},beep(){}});for(const n of ['rankTalent','attackTiming','attack'])vm.runInContext(extract(n),c);c.player={dead:false,atkCd:0,dodgeT:0,atkT:0,combo:0,comboT:0,face:0,x:0,z:0,dmg:100,buff:0};shots.length=0;c.attack();assert.equal(shots.length,6);assert.equal(new Set(shots.map(x=>x[2])).size,6);assert.equal(shots[0][3],22*1.45);c.profile.rankTalents=['piercing','finisher','finisher'];c.player.atkCd=0;c.player.combo=2;c.player.comboT=1;shots.length=0;c.attack();assert.equal(shots[0][4],100*(1.8+.5));assert(shots[0][8].pierce);
console.log('PASS visible skill states, distinct star volley conserving total damage, expanded talent caps, distinct extra trajectories, projectile reach, finisher and piercing');
