const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8');
function extract(n){const m=new RegExp('function\\s+'+n+'\\s*\\([^)]*\\)').exec(src);assert(m,n);let b=src.indexOf('{',m.index),d=0,q=null,e=false;for(let i=b;i<src.length;i++){let c=src[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;if(c==='}'&&!--d)return src.slice(m.index,i+1)}}
const c={CFG:{moveLimit:false,moveCap:100},L:{grid:true},freeAt:(x,z)=>x<1,pushOut(){},statsBonus:()=>({atk:1})};vm.createContext(c);for(const n of ['moveEnt','movementSpeed','attackTiming'])vm.runInContext(extract(n),c);
assert.equal(c.movementSpeed(20),20);c.CFG.moveLimit=true;assert.equal(c.movementSpeed(20),6.4);assert.equal(c.movementSpeed(3),3);c.CFG.moveCap=200;assert.equal(c.movementSpeed(20),12.8);assert.equal(c.movementSpeed(Infinity),0);assert.equal(c.movementSpeed(-2),0);
let e={x:0,z:0,r:.5};c.moveEnt(e,20,4);assert(e.x<1);assert(Math.abs(e.z-4)<1e-10);e={x:0,z:0};let checks=0;c.freeAt=()=>{checks++;return true};c.moveEnt(e,1e12,1e12);assert(Number.isFinite(e.x));assert(Math.hypot(e.x,e.z)<=32.0001);assert(checks<=256);const before=JSON.stringify(e);c.moveEnt(e,Infinity,0);assert.equal(JSON.stringify(e),before);e={x:0,z:0};c.moveEnt(e,.1,.2);assert.equal(e.x,.1);assert.equal(e.z,.2);
for(const agi of [0,100,1000,10000,1000000])for(const third of [false,true]){c.statsBonus=()=>({atk:1/(1+.004*agi)});const t=c.attackTiming(third),desired=(third?.46:.3)/(1+.004*agi);assert(t.interval>=.05);assert(Number.isFinite(t.damage));assert(Math.abs(t.damage/t.interval-1/desired)<1e-7)}
assert(src.includes('if(player.atkT<=0)player.atkT=.001'));assert(src.includes('movementSpeed(P.spd*(run.mounted?1.8:1))'));
console.log('PASS optional movement limit, no speed boost, stats independence, collision substeps, bounded extreme movement, finite values, attack scaling through one million agility, animation continuity');
