const fs=require('fs'),vm=require('vm'),assert=require('assert');const src=fs.readFileSync(__dirname+'/../game.html','utf8');
function extract(n){const m=new RegExp('function\\s+'+n+'\\s*\\([^)]*\\)').exec(src);assert(m,n);let b=src.indexOf('{',m.index),d=0,q=null,e=false;for(let i=b;i<src.length;i++){let c=src[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;if(c==='}'&&!--d)return src.slice(m.index,i+1)}}
const c={rankTalent:()=>0,Math,Number,Map,Set,console,time:10,profile:{cls:0,jobs:[0,1,2,4,5,6,7,8,9,10,11]},run:{style:'nat'},player:{hp:50,maxhp:100,mp:10,maxmp:100,shield:0,maxsh:100},MAGIC_CLS:[3,5,6,7,8,9,10,11],isMagic:()=>c.MAGIC_CLS.includes(c.profile.cls),jobsOf:()=>c.profile.jobs,learnedSkills:()=>[],classLoadout:()=>[],saveRun(){},floater(){},hasAff:()=>false,enemies:[],zig(){},started:true,paused:false,toast(){},bigText(){},sfx(){},hud(){}};c.keyOf=()=> 'KeyX';c.keyLabel=()=> 'X';vm.createContext(c);vm.runInContext(src.slice(src.indexOf('const S='),src.indexOf('const BOSSES=')),c);for(const n of ['canUseMagicStyle','basicIsMagic','basicAttackId','basicAttackClass','basicAttackDesc','selectBasicAttack','toggleStyle','applyBasicAttackEffect','updateBasicDots'])vm.runInContext(extract(n),c);let passed=0;function test(n,fn){fn();console.log('PASS '+n);passed++}
test('choose ice then fire regardless of base and equipped skills',()=>{assert(c.selectBasicAttack(9));assert.equal(c.basicAttackId(),9);assert(c.selectBasicAttack(8));assert.equal(c.basicAttackId(),8);assert(c.basicIsMagic());assert(!c.selectBasicAttack(99));assert(!c.selectBasicAttack(3))});
test('saved choices persist and X recalls physical and magic choices',()=>{c.selectBasicAttack(1);c.selectBasicAttack(8);c.run=JSON.parse(JSON.stringify(c.run));c.toggleStyle();assert.equal(c.basicAttackId(),1);c.toggleStyle();assert.equal(c.basicAttackId(),8);c.profile.cls=9;c.run.style='nat';assert.equal(c.basicAttackId(),8)});
test('bleed and burn differ, refresh without unbounded stacking',()=>{const e={hp:100,slow:0};c.applyBasicAttackEffect(e,1,100);c.applyBasicAttackEffect(e,8,100);assert.equal(e.basicDots.bleed.d,10);assert.equal(e.basicDots.burn.d,25/3);c.applyBasicAttackEffect(e,1,100);assert.equal(e.basicDots.bleed.d,10);let dmg=0;c.hurtEnemy=(_,n)=>dmg+=n;for(let i=0;i<30;i++)c.updateBasicDots(e,.1);assert(Math.abs(dmg-55)<.001);assert.equal(Object.keys(e.basicDots).length,0)});
test('ice slows; earth and warrior do not stun bosses',()=>{const e={hp:100,slow:0,stun:0};c.applyBasicAttackEffect(e,9,10);assert.equal(e.slow,2);c.applyBasicAttackEffect(e,10,10,true);assert.equal(e.stun,.8);c.applyBasicAttackEffect(e,0,10,true);assert.equal(e.stun,.9);const boss={hp:100,isBoss:true,stun:0};c.applyBasicAttackEffect(boss,10,10,true);assert.equal(boss.stun,0)});
test('support effects respect no-cure and resource caps',()=>{const e={hp:100};c.applyBasicAttackEffect(e,2,10,true);assert.equal(c.player.shield,2);c.applyBasicAttackEffect(e,6,10);assert.equal(c.player.mp,10);assert.equal(e.summonFocusUntil,14);c.applyBasicAttackEffect(e,5,10);assert.equal(c.player.hp,50.5);c.applyBasicAttackEffect(e,7,100);assert.equal(c.player.hp,50.5);assert.equal(e.echoMarkUntil,14);c.hasAff=()=>true;c.applyBasicAttackEffect(e,5,10);c.applyBasicAttackEffect(e,7,100);assert.equal(c.player.hp,50.5);assert.equal(e.echoMarkUntil,14)});
test('lightning chains once only on third shot',()=>{const a={hp:100,x:0,z:0},b={hp:100,x:1,z:0};c.enemies=[a,b];let hits=[];c.hurtEnemy=(...a)=>hits.push(a);c.applyBasicAttackEffect(a,11,100,false);assert.equal(hits.length,0);c.applyBasicAttackEffect(a,11,100,true);assert.equal(hits.length,1);assert.equal(hits[0][1],25);assert(hits[0][4].passive);assert.equal(hits[0][4].basicClass,undefined)});
test('projectile remembers attack type fired; archer third shot pierces',()=>{assert(src.includes('basicClass:o.basicClass,skillHit:!!o.skillHit,bounces:o.bounces||0,third:!!o.third'));assert(src.includes('basicClass:p.basicClass,skillHit:p.skillHit,third:p.third'));assert(src.includes('pierce:ci===4&&third'));assert(src.includes('!blocked&&Number.isInteger(o.basicClass)'))});console.log(passed+' scenarios passed');
