const fs=require('fs'),vm=require('vm'),assert=require('assert');const src=fs.readFileSync(__dirname+'/../game.html','utf8');
function extract(n){const m=new RegExp('function\\s+'+n+'\\s*\\([^)]*\\)').exec(src);assert(m,n);let b=src.indexOf('{',m.index),d=0,q=null,e=false;for(let i=b;i<src.length;i++){let c=src[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;if(c==='}'&&!--d)return src.slice(m.index,i+1)}}
for(const file of ['game.html','index.html'])for(const m of fs.readFileSync(__dirname+'/../'+file,'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))if(m[1].trim())new vm.Script(m[1]);
const c={Math:Object.create(Math),Number,Object,PRICE:[100,300,900],run:{},L:{mode:'world'},player:{x:0,z:0},rankOf:()=>2,unl:()=>true,inCity:()=>true,profLv:()=>0,profXp(){},wpick:()=>({i:0}),makeItem:(slot,tier,rar)=>({slot,tier,rar,uid:'new'}),refreshStats(){},sfx(){},toast(){},fxRing(){},statTxt:()=>'',saveRun(){},time:1,GEAR_RUNES:{fang:{n:'Fang'},shell:{n:'Shell'},command:{n:'Command'}}};c.keyOf=a=>a==='style'?'KeyX':'KeyQ';c.keyLabel=k=>k.replace('Key','');vm.createContext(c);vm.runInContext(extract('skillDamage'),c);
for(const n of ['equipmentUpgradeCost','finishEquipmentUpgrade','lootForgeQuote','canLootForge','craftWithLoot','cryUp','spendCry','lootRune','gearRuneCount','gearRuneText','applyGearRuneHit','echoAttackMul','statsBonus'])vm.runInContext(extract(n),c);
let n=0;function reset(){c.L.mode='world';c.run={gold:100000,res:{cry:[100,100,100,0,0,0,0,0,0]},loot:{'Garra de Lobo':{n:50,v:3,b:false},'Relíquia de Guardião':{n:10,v:30,b:true}},equip:{w:{slot:'w',tier:1,rar:0,up:0,name:'Espada',value:50,aff:[{k:'dmg',v:2}]}},items:[],stats:{}};c.Math.random=()=>0}
function test(label,fn){reset();fn();console.log('PASS '+label);n++}
test('legacy loot crafts chosen rank, rare floor, exact spend, no autoequip',()=>{assert(c.craftWithLoot('w','Garra de Lobo','new'));assert.equal(c.run.items[0].rar,1);assert.equal(c.run.items[0].tier,2);assert.equal(c.run.equip.w.name,'Espada');assert.equal(c.run.loot['Garra de Lobo'].n,40);assert.equal(c.run.loot['Relíquia de Guardião'].n,10);assert.equal(c.run.res.cry[2],95);assert.equal(c.run.gold,99730)});
test('boss recipe guarantees epic',()=>{c.craftWithLoot('a','Relíquia de Guardião','new');assert.equal(c.run.items[0].rar,2)});
test('missing materials, full bag, invalid slot and outside city spend nothing',()=>{for(const mode of ['new','up','rune']){const before=JSON.stringify(c.run);assert(!c.craftWithLoot('w','missing',mode));assert.equal(JSON.stringify(c.run),before)}c.run.items=Array(24).fill({});const gold=c.run.gold;assert(!c.craftWithLoot('w','Garra de Lobo','new'));assert(!c.craftWithLoot('x','Garra de Lobo','new'));c.L.mode='dungeon';assert(!c.craftWithLoot('w','Garra de Lobo','up'));assert.equal(c.run.gold,gold)});
test('common reinforcement discounts gold and crystals, preserves item affixes',()=>{const eq=c.run.equip.w;c.craftWithLoot('w','Garra de Lobo','up');assert.equal(eq.up,1);assert.equal(c.run.gold,99943);assert.equal(c.run.res.cry[1],97);assert.equal(eq.aff[0].v,2)});
test('failed upgrade spends once and preserves equipment; relic guarantees beyond ten',()=>{const eq=c.run.equip.w;eq.up=10;assert(c.craftWithLoot('w','Garra de Lobo','up'));assert.equal(eq.up,10);assert.equal(c.run.loot['Garra de Lobo'].n,35);assert(c.craftWithLoot('w','Relíquia de Guardião','up'));assert.equal(eq.up,11);assert.equal(c.run.loot['Relíquia de Guardião'].n,5)});
test('inscription replaces only rune, no double charge for same rune, save roundtrip',()=>{c.craftWithLoot('w','Garra de Lobo','rune');assert.equal(c.run.equip.w.rune,'fang');const before=JSON.stringify(c.run);assert(!c.craftWithLoot('w','Garra de Lobo','rune'));assert.equal(JSON.stringify(c.run),before);c.craftWithLoot('w','Relíquia de Guardião','rune');c.run=JSON.parse(JSON.stringify(c.run));assert.equal(c.run.equip.w.rune,'command');assert.equal(c.run.equip.w.aff.length,1);assert.equal(c.gearRuneCount('fang'),0);assert.equal(c.gearRuneCount('command'),1);c.run.items.push(c.run.equip.w);c.run.equip.w=null;assert.equal(c.gearRuneCount('command'),0)});
test('rune bleeding refreshes without multiplying and skips dead targets',()=>{c.run.equip.w.rune='fang';const e={hp:100};c.applyGearRuneHit(e,30);assert.equal(e.basicDots.rune.d,1);c.applyGearRuneHit(e,30);assert.equal(e.basicDots.rune.d,1);c.run.equip.a={rune:'fang'};c.applyGearRuneHit(e,30);assert.equal(e.basicDots.rune.d,2);const dead={hp:0};c.applyGearRuneHit(dead,30);assert(!dead.basicDots)});
test('summon rune excludes hired hunters and arcane rune changes skill power',()=>{c.run.equip.w.rune='command';assert.equal(c.echoAttackMul({permanentSummon:true},{}),1.08);assert.equal(c.echoAttackMul({party:true},{}),1);assert(Math.abs(c.echoAttackMul({shadow:true},{echoMarkUntil:3})-1.296)<1e-8);c.run.equip.w.rune='arcane';assert.equal(c.statsBonus().skill,1.05)});
test('defensive, mana and movement runes affect actual derived stats',()=>{Object.assign(c,{curseB:()=>({}),foodB:()=>({}),titleB:()=>({}),setB:()=>({}),bonusPool:()=>({edmg:0,ehp:0}),CLS_BAL:{},profile:{cls:6},atkOf:()=>10,isMagic:()=>true,hpPer:()=>1,mpPer:()=>1,itemSh:()=>100,cons:()=>0,innB:()=>0,pb:()=>0,npcHas:()=>false,affB:()=>({mp:0,spd:0})});c.run.level=20;vm.runInContext(extract('statsFor'),c);c.run.equip.w.rune='shell';c.run.equip.a={rune:'vigor'};let st=c.statsFor();assert.equal(st.maxsh,108);assert.equal(st.maxmp,116);c.run.equip.w.rune='stride';st=c.statsFor();assert(Math.abs(st.spd-6.592)<1e-8)});
vm.runInContext(src.slice(src.indexOf('const KEYACT='),src.indexOf('let KEYMAP=')),c);c.KEYMAP={};for(const f of ['keyOf','bindableKey','setKeyBinding','remapCode'])vm.runInContext(extract(f),c);
test('E and former fixed shortcuts can bind and swap without duplicate actions',()=>{for(const code of ['KeyE','KeyB','KeyX','KeyP','KeyN','KeyO','KeyJ','KeyV','Digit1','Digit2','Digit3','Digit4','Tab','Enter','ShiftRight']){c.KEYMAP={};assert(c.setKeyBinding('sk0',code),code);assert.equal(c.remapCode(code),'KeyQ');assert.equal(c.keyOf('sk0'),code);const keys=vm.runInContext('KEYACT.map(([a])=>keyOf(a))',c);assert.equal(new Set(keys).size,keys.length)}for(const k of ['KeyW','KeyA','KeyS','KeyD','Escape','ArrowUp'])assert(!c.setKeyBinding('sk0',k));c.KEYMAP={};c.setKeyBinding('sk0','KeyX');assert.equal(c.keyOf('style'),'KeyQ');const saved=JSON.parse(JSON.stringify(c.KEYMAP));c.KEYMAP={};for(const [a,k] of Object.entries(saved))c.setKeyBinding(a,k);assert.equal(c.remapCode('KeyX'),'KeyQ');assert.equal(c.remapCode('KeyQ'),'KeyX')});
test('empty-ground skills spend mana and cooldown; only chain needs a target',()=>{Object.assign(c,{paused:false,nearestEnemy:()=>null,floater(){},hasAff:()=>false,skillCooldown:()=>4,runSkill(){},player:{x:0,z:0,mp:100},time:1});vm.runInContext(extract('useSkill'),c);for(const t of ['cone','nova','bolt','rain','dot','stone_lance','thunderstorm']){c.player.mp=100;const sk={t,mp:10,cdT:0};c.useSkill(sk);assert.equal(c.player.mp,90,t);assert.equal(sk.cdT,4,t)}c.player.mp=100;const chain={t:'chain',mp:10,cdT:0};c.useSkill(chain);assert.equal(c.player.mp,100);assert.equal(chain.cdT,0)});
test('ground targeting clamps range; persistent area hits enemies arriving later',()=>{Object.assign(c,{player:{x:0,z:0,face:0,dmg:10},aimPoint:()=>({x:0,z:30}),isMagic:()=>false,atkOf:()=>10,wxSkillMul:()=>1,statsBonus:()=>({skill:1}),setB:()=>({}),faceTarget:()=>null,skillFx(){},rnd:(a,b)=>(a+b)/2,fallFx(){},enemies:[],hazards:[],allies:[],AU:{lastBoom:0},scene:{remove(){}},fxRing(){},fxBurst(){},shake(){},pillar(){},sparkUp(){}});c.run.skl={};c.hazard=(x,z,r,dur,dmg,team,col)=>{const h={x,z,r,dur,dmg,team,col,t:0,fill:{scale:{setScalar(){}}},g:{traverse(){}}};c.hazards.push(h);return h};for(const f of ['skillGroundPoint','runSkill','updHazards'])vm.runInContext(extract(f),c);assert.equal(c.skillGroundPoint().z,14);c.runSkill({t:'rain',n:'Chuva de Flechas',pow:1,col:0});assert.equal(c.hazards.length,10);assert.equal(c.hazards[0].z,14);assert(c.hazards[9].dur>2.8);c.hazards=[];c.runSkill({t:'thunderstorm',n:'Tempestade',pow:1,col:0});assert.equal(c.hazards.length,5);c.hazards=[];c.runSkill({t:'dot',n:'Praga',pow:1,col:0});assert.equal(c.hazards.length,5);c.updHazards(.6);assert.equal(c.hazards.length,4);const enemy={x:0,z:11,r:.5,hp:100};c.enemies=[enemy];c.hurtEnemy=(e,d)=>e.hp-=d;c.updHazards(1);assert.equal(enemy.hp,98)});
test('skill marks survive flight time, apply only from skills and consume once on basic',()=>{vm.runInContext(extract('applySkillMark'),c);c.player.skills=[{cdT:3}];c.time=20;const e={};assert.equal(c.applySkillMark(e,10,{fromPlayer:true,skillHit:true}),10);assert.equal(e.mark,26);c.time=22;assert.equal(c.applySkillMark(e,10,{fromPlayer:true,basicClass:4}),15);assert.equal(c.player.skills[0].cdT,2);assert.equal(c.applySkillMark(e,10,{fromPlayer:true,basicClass:4}),10);assert.equal(c.applySkillMark({},10,{fromPlayer:true,basicClass:4}),10)});
test('skill tooltips show shared damage calculation and actual Arcano cooldown',()=>{Object.assign(c,{cons:()=>5,fmt:String,minionAllies:()=>[],summonCap:()=>5,SKD:{rain:'Chuva',blink:'Salto'},MAGIC_CLS:[],player:{...c.player,dmg:100,maxhp:200,buff:0}});c.run.skl={Chuva:2};for(const f of ['skillCooldown','skillCooldownText','skillDesc','skillUpgradeText'])vm.runInContext(extract(f),c);const sk={n:'Chuva',t:'rain',pow:2,mp:20,cd:8};const text=c.skillDesc(sk);assert(text.includes('260 por impacto'));assert(text.includes('6,66s'));assert(!text.includes('Arcano'));assert(!text.includes('poder x'));assert(text.includes('<br>'));assert(c.skillUpgradeText({t:'blink'}).includes('Não altera o efeito'));});
console.log(n+' scenarios passed; both HTML scripts parse');
