const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8'),base=fs.readFileSync(__dirname+'/verify-v95.cjs','utf8');eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')).replace("src.indexOf('{',m.index)","src.indexOf('{',m.index+m[0].length)"));
let html='',skills=[{n:'Cura',sourceClass:5},{n:'Julgamento',sourceClass:5}],allowed=false;
const c={CHAR_UI118:{details:{},filters:{}},profile:{rank:0,cls:5,rankTalents:[],ach:[]},run:{spts:16,skl:{},shadows:[],equip:{},mastery:0},player:{skills:[]},L:{},Math,Set,encodeURIComponent,safeText:String,preciseNumber:String,btn:(n,a,v,ok=true)=>`<button data-a="${a}" ${ok?'':'disabled'}>${n}</button>`,row:(a,b,d)=>`<section>${a}${b}${d}</section>`,openModal:(t,h)=>html=h,learnedSkills:()=>skills,jobsOf:()=>[5],classSlotCount:()=>1,skillUpgradeText:()=>'+dano',skillDesc:s=>s.n+' descrição',kitVisible111:()=>true,kitProgress111:()=>'',powLib:()=>[],transmigratorRow:()=>'<section>Transmigrador</section>',passiveClasses:()=>[5],CLASSES:Array.from({length:6},()=>({n:'Paladino'})),PASSIVES:Array.from({length:6},()=>({n:'Passiva aprendida',d:'Efeito ativo'})),PBOOK:[{k:'book',n:'Tomo de teste',d:()=>'+5%'}],pb:()=>0,CONS:[['fur','Fúria','Crítico','Máximo']],cons:()=>0,unl:()=>allowed,awakeningDiscovered109:()=>false,canRedistribute:()=>true,rankPoints:()=>1,rankTalent:k=>(c.profile.rankTalents||[]).filter(x=>x===k).length,RANKS:Array.from({length:10},(_,i)=>({id:i})),charSheet:()=>'<div>Ataque físico · 100</div>',regenRows:()=>'<div>Regeneração · 5/s</div>',EQUIP_SLOTS:['w','a'],EQUIP_LABEL:{w:'Arma',a:'Armadura'},GEAR_RUNES:{fire:{n:'Fogo',d:'Dano de fogo'}},activeSets:()=>[],titleLevel:()=>1,titleProgress:()=>150,titleGoal:()=>200,titleName:t=>t.n,titleEffect:()=>'+1% dano',eqTitles:()=>[],TITLES:[{id:'kill',track:true,n:'Caçador',unit:'monstros derrotados'}]};vm.createContext(c);
vm.runInContext(src.match(/const RANK_TALENTS=([^\n]+)/)[0],c);
for(const n of ['titleCard118','skillPoints118','characterTabs','masteryReady114','skillUpgradeRow','skillsView','passivesView','buildView','rankTalentRows','rankView114','titleTrackRows'])vm.runInContext(extract(n),c);
c.skillsView();assert(html.includes('Cura'));assert(html.includes('Julgamento'));assert(!html.includes('<details class="skill114" data-skill114="Cura" open'));assert(!/REPERTÓRIO|Bloquead|Maestria|Habilidade fundida|Ecos|Caminho/.test(html));assert(html.includes('data-a="basicview"'));assert(!html.includes('Ataque básico</section>'));
c.CHAR_UI118.details={Cura:true};c.skillsView();assert(html.includes('data-skill114="Cura" open'));c.run.skl={Cura:10,Julgamento:10};assert(c.masteryReady114());c.skillsView();assert(html.includes('Maestria'));skills.push({n:'Nova habilidade',sourceClass:5});assert(!c.masteryReady114());c.run.mastery=2;c.skillsView();assert(html.includes('Maximize as habilidades'));assert(/data-a="mast" disabled/.test(html));assert(extract('extraActions').includes('run.spts<1||!masteryReady114()'));
c.passivesView();assert(html.includes('Passiva aprendida'));assert(!/TOMOS|CONSTELAÇÕES|Maestria|ESCOLHAS|EQUIPAMENTO|TÍTULOS ATIVOS/.test(html));c.pb=()=>2;allowed=true;c.passivesView();assert(html.includes('Tomo de teste'));assert(html.includes('Distribuir'));assert(!html.includes('Fúria'));
assert(!c.characterTabs('skills').includes('>Rank<'));c.profile.rank=1;assert(c.characterTabs('rank').includes('>Rank<'));c.rankView114();assert(html.includes('Disparo dividido'));assert(!html.includes('Disparo penetrante'));assert(!html.includes('Combate em movimento'));assert(extract('extraActions3').includes('chooseRankTalent(v);rankView114()'));
c.buildView();assert(html.includes('Ataque físico'));assert(html.includes('Regeneração'));assert(!/Profissões|PROFISSÕES|Arma viva|Bestiário|Aparência|Reencarnação|Conjuntos|Grupo|Efeitos do equipamento/.test(html));c.run.equip.w={rune:'fire'};c.buildView();assert(html.includes('Efeitos do equipamento'));assert(html.includes('Dano de fogo'));
html=c.titleTrackRows();assert(html.includes('150 / 200'));assert(html.includes('value="75"'));assert.equal((html.match(/<progress /g)||[]).length,1);assert(!/Próximo nível|Progresso total|Neste nível|Próximo bônus/.test(html));
console.log('PASS initial/advanced character screens; collapsed skills and retained expansion; mastery eligibility/action guard; hidden unowned passives; rank visibility and return routing; combat-only Build; one consistent title progress.');

let painted115;const paint115={fillRect(){},strokeRect(){},measureText:t=>({width:t.length*35}),fillText:(...args)=>painted115=args};c.document={createElement:()=>({getContext:()=>paint115})};c.THREE={CanvasTexture:function(){},SpriteMaterial:function(){},Sprite:function(){this.scale={set(){}}}};vm.runInContext(extract('makeSign'),c);c.makeSign('CHEGADA DOS INVASORES','#fff');assert.equal(painted115[0],'CHEGADA DOS INVASORES');assert.equal(painted115[3],472);assert(parseInt(paint115.font.split(' ')[1])<60);c.makeSign('SAÍDA','#fff');assert(paint115.font.includes('60px'));console.log('PASS long sign text fits inside its frame; short signs retain font size.');
