const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8'),base=fs.readFileSync(__dirname+'/verify-v95.cjs','utf8');eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')).replace("src.indexOf('{',m.index)","src.indexOf('{',m.index+m[0].length)"));
const hazards=[],shots=[],c={run:{skl:{}},time:10,player:{x:0,z:0,face:0,hp:50,maxhp:100},allies:[],enemies:[],hasAff:()=>false,fmt:Math.round,floater(){},fxRing(){},skillDamage:()=>100,faceTarget(){},physicalEvolution:()=>false,magicEvolution:()=>false,skillFx(){},hitstop(){},shake(){},sfx(){},skillGroundPoint:()=>({x:0,z:9}),rnd:(a,b)=>(a+b)/2,fallFx(){},hazard(x,z,r,dur,dmg){const h={x,z,r,dur,dmg};hazards.push(h);return h},shoot:(...a)=>shots.push(a),hurtEnemy(e,amt){if(e.invuln)return;e.hp-=amt;return amt}};Object.assign(c,{narratorEvent105(){},narratorSkill105(){},narratorDeath105(){},narratorPortal105(){}});vm.createContext(c);
for(const n of ['identityHitDamage','applyWeaponVenom','judgmentHealing','judgmentRelief','healerLevel','judgmentRadius','runSkill','updateBasicDots'])vm.runInContext(extract(n),c);
let e={hp:35,maxhp:100,x:8,z:0};assert.equal(c.identityHitDamage(e,100,{fromPlayer:true,execute:true}),150);e.hp=36;assert.equal(c.identityHitDamage(e,100,{fromPlayer:true,execute:true}),100);assert.equal(c.identityHitDamage(e,100,{fromPlayer:true,longshot:true,originX:0,originZ:0}),125);e.x=7.99;assert.equal(c.identityHitDamage(e,100,{fromPlayer:true,longshot:true,originX:0,originZ:0}),100);assert.equal(c.identityHitDamage(e,100,{fromPlayer:false,execute:true}),100);assert.equal(c.identityHitDamage(e,100,{fromPlayer:true,skillHit:true}),100);assert.equal(e.mark,undefined);
c.runSkill({n:'Passo Sombrio',t:'dash_strike'});assert(c.player.dashDmg.execute);c.runSkill({n:'Investida',t:'dash_strike'});assert(!c.player.dashDmg.execute);
c.runSkill({n:'Lâmina Envenenada',t:'dot'});assert.equal(hazards.length,0);assert.equal(c.player.venomCharges,3);assert.equal(c.player.venomUntil,18);e={hp:500};c.applyWeaponVenom(e,100);assert.equal(c.player.venomCharges,2);assert.equal(e.basicDots.venom.d,15);c.applyWeaponVenom(e,50);assert.equal(e.basicDots.venom.d,15);c.applyWeaponVenom(e,100);assert.equal(c.player.venomCharges,0);c.applyWeaponVenom(e,1000);assert.equal(e.basicDots.venom.d,15);for(let i=0;i<4;i++)c.updateBasicDots(e,1);assert.equal(e.hp,440);assert.equal(e.basicDots.venom,undefined);c.runSkill({n:'Lâmina Envenenada',t:'dot'});c.time=18;c.applyWeaponVenom(e,100);assert.equal(e.basicDots.venom,undefined);
c.runSkill({n:'Praga',t:'dot'});assert.equal(hazards.length,5);hazards.length=0;c.runSkill({n:'Chuva de Flechas',t:'rain'});assert.equal(hazards.length,10);assert(hazards.every(h=>h.slow===2));hazards.length=0;c.runSkill({n:'Chuva de Meteoros',t:'rain'});assert(hazards.every(h=>!h.slow));c.runSkill({n:'Flecha Perfurante',t:'bolt'});assert(shots.at(-1).at(-1).longshot);c.runSkill({n:'Bola de Fogo',t:'bolt'});assert(!shots.at(-1).at(-1).longshot);
c.player.hp=50;c.allies=[{x:2,z:0,hp:50,maxhp:200,life:10},{x:9,z:0,hp:50,maxhp:100,life:10},{x:1,z:0,hp:0,maxhp:100,life:10,dead:true}];const j={n:'Julgamento',t:'nova'};c.enemies=[];c.runSkill(j);assert.equal(c.player.hp,50);c.enemies=[{x:1,z:0,r:.5,hp:1000,invuln:true}];c.runSkill(j);assert.equal(c.player.hp,50);c.enemies=[{x:1,z:0,r:.5,hp:1000},{x:2,z:0,r:.5,hp:1000}];c.runSkill(j);assert.equal(c.player.hp,58);assert.equal(c.allies[0].hp,66);assert.equal(c.allies[1].hp,50);assert.equal(c.allies[2].hp,0);c.hasAff=()=>true;c.runSkill(j);assert.equal(c.player.hp,58);assert.equal(c.enemies[0].hp,800);
assert(src.includes('longshot:p.longshot,originX:p.originX,originZ:p.originZ'));assert(src.includes('execute:P.dashDmg.execute'));assert(!src.includes('function applySkillMark'));assert(src.includes('echoMarkUntil'));assert(src.includes('summonFocusUntil'));
console.log('PASS execution threshold/dash ownership; ranged origin/threshold/projectile flags; venom charges/expiry/refresh/actual 4 ticks; rain control; Judgment hit gate/group range/dead/no-cure/once-per-cast; summon identity preserved');

Object.assign(c,{hasT:()=>false,hasClassPassive:()=>false,critChance:()=>0,gearRuneCount:()=>0,titleHitBonus:()=>0,trophyB:()=>0,expeditionDamage:(e,d)=>d,affB:()=>({ls:0}),pb:()=>0,FX2:{combo:0},profile:{},applyBasicAttackEffect(){},applyGearRuneHit(){},applyPassive(){},resolveEnemyStun(){},killEnemy:e=>e.dead=true,setStealth(){},toast(){}});vm.runInContext(extract('hurtEnemy'),c);c.hasAff=()=>false;c.player.hp=50;c.player.venomCharges=0;c.player.skills=[{cdT:4}];c.enemies=[{x:1,z:0,r:.5,hp:1000,maxhp:1000,kb:{},stun:0}];c.runSkill(j);assert.equal(c.player.hp,58);assert.equal(c.enemies[0].hp,900);assert.equal(c.player.skills[0].cdT,4);assert.equal(c.enemies[0].mark,undefined);c.runSkill({n:'Lâmina Envenenada',t:'dot'});c.hurtEnemy(c.enemies[0],100,0,0,{fromPlayer:true,basicClass:1});assert.equal(c.player.venomCharges,2);assert.equal(c.enemies[0].basicDots.venom.d,15);const immune={x:1,z:0,hp:1000,maxhp:1000,invuln:true};c.hurtEnemy(immune,100,0,0,{fromPlayer:true,basicClass:1});assert.equal(c.player.venomCharges,2);console.log('PASS real hurtEnemy → Judgment healing and venom hit integration; no universal mark/refund; immunity does not consume venom');
c.run.skl.Julgamento=10;c.player.hp=50;c.runSkill(j);assert.equal(c.player.hp,68);console.log('PASS max-level Judgment heals 18% through actual damage path');
