const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync(__dirname+'/../game.html','utf8');
function extract(n){const m=new RegExp('function\\s+'+n+'\\s*\\([^)]*\\)').exec(src);assert(m,n);let b=src.indexOf('{',m.index),d=0,q=null,e=false;for(let i=b;i<src.length;i++){let c=src[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;if(c==='}'&&!--d)return src.slice(m.index,i+1)}}
const saved=[],notes=[];
const c={profile:{rank:0},run:{level:999,gold:0,quests:[]},L:{},TOPR:8,GR:Array.from({length:10},(_,i)=>({lvl:i*10})),RANKS:'F E D C B A S SS SS+ ★'.split(' ').map(id=>({id})),store:{set(){}},fmt:String,toast:x=>notes.push(x),saveRun(){saved.push(JSON.stringify({p:c.profile,r:c.run}))},rankOf:()=>c.profile.rank,affL:()=>0,beep(){}};
vm.createContext(c);vm.runInContext(src.slice(src.indexOf('const ORDER_REP_NEED='),src.indexOf('function rankPortalCount')),c);
for(const n of ['rankPortalCount','qualifyingRankPortals','rankTrialReady','recordRankPortal','recordSpecialOrderRep','genQuest','completeJob','dprog'])vm.runInContext(extract(n),c);
assert.equal(c.orderRep(),0);
for(let i=0;i<10;i++){c.L={gate:{rank:0},bossDead:true};assert(c.recordRankPortal(0));assert(!c.recordRankPortal(0))}assert.equal(c.orderRep(),100);assert(c.rankTrialReady(1));assert.equal(c.profile.guildClaims,undefined);
c.profile={rank:0,orderRep97:0};c.run.quests=[{t:'kill',n:20,got:20,rw:70,repRank97:0}];assert(c.claimOrderQuest(0));assert.equal(c.orderRep(),6);assert.equal(c.run.gold,70);assert(!c.claimOrderQuest(0));assert(!c.claimOrderQuest(22));assert.equal(c.orderRep(),6);
for(let i=0;i<16;i++){c.run.quests[0].got=c.run.quests[0].n;assert(c.claimOrderQuest(0))}assert.equal(c.orderRep(),102);assert(c.rankTrialReady(1));assert(!c.profile.closedPortalsByRank);c.profile=JSON.parse(JSON.stringify(c.profile));assert.equal(c.orderRep(),102);
c.profile={rank:0,guildClaims:2,closedPortalsByRank:{1:3}};assert.equal(c.orderRep(),100);assert(c.rankTrialReady(1));const legacy=JSON.stringify(c.profile);c.ensureOrderRep();assert.equal(JSON.stringify(c.profile),legacy);
c.profile={rank:4,guildClaims:0};assert.equal(c.orderRep(),1400);c.profile={rank:0,guildClaims:5,closedPortalsByRank:{0:2,2:1}};assert.equal(c.orderRep(),100);
c.profile={rank:0,orderRep97:310};Object.assign(c,{rememberClassCooldowns(){},pSkills:()=>[],showG(){},refreshStats(){},bigText(){},sfx(){},setTimeout(){}});c.player={maxhp:100,aura:{material:{color:{set(){}}}}};c.L={rankTrial:1};assert(c.rankTrialReady(1));assert(!c.rankTrialReady(2));c.completeJob();assert.equal(c.profile.rank,1);assert.equal(c.orderRep(),310);assert(c.rankTrialReady(2));c.L={rankTrial:2};c.completeJob();assert.equal(c.profile.rank,2);assert.equal(c.orderRep(),310);assert(!c.rankTrialReady(3));c.run.level=1;assert(!c.rankTrialReady(3));
c.profile={rank:8,orderRep97:50000};assert(!c.rankTrialReady(9));assert(c.orderRepReward(1)<25);assert.equal(c.orderRepReward(8),750);c.profile.rank=0;assert(c.orderRepReward(2)>c.orderRepReward(1));
c.profile={rank:0,orderRep97:0,karma:-4};for(const L of [{gate:{rank:1},bossDead:false},{gate:{rank:1},bossDead:true,special:{}}]){c.L=L;assert(!c.recordRankPortal(1))}assert.equal(c.orderRep(),0);assert.equal(c.profile.karma,-4);
c.DAILY=[['kill','Abates',1]];c.run.daily={p:{kill:0},done:false};c.run.pts=0;c.dprog('kill',1);assert.equal(c.orderRep(),10);c.dprog('kill',1);assert.equal(c.orderRep(),10);assert(saved.length>0);
c.profile={rank:5,orderRep97:0};assert.equal(c.questOrderRep({t:'kill',n:20}),1);assert.equal(c.questOrderRep({t:'clear',rank:1}),2);assert.equal(c.questOrderRep({t:'pvp'}),1);assert(c.questOrderRep(c.genQuest('kill'))>1);
assert(!src.includes('feche 3 portais'));assert(!src.includes('3 portais rank'));assert(src.includes("if(a==='claim'){if(!claimOrderQuest(+v))return}"));
console.log('PASS portals-only and quests-only eligibility; mixed totals; no duplicate rewards; old saves, earned ranks and eligible next trial preserved; save roundtrip; two consecutive examiners without spending reputation; level and rare-rank gates; reduced easy rewards; no abandoned/special rewards; daily persistence; regional karma independence.');

c.profile={rank:0,orderRep97:0};c.L={gate:{rank:3,ref:{id:12}},special:{done:false}};assert(!c.recordSpecialOrderRep());c.L.special.done=true;assert(c.recordSpecialOrderRep());assert.equal(c.orderRep(),90);assert(!c.recordSpecialOrderRep());c.L={gate:{rank:3},special:{done:true}};assert(!c.recordSpecialOrderRep());console.log('PASS completed special world portals reward once; unfinished portals, tower and arenas excluded');
