const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync('game.html','utf8'),base=fs.readFileSync('tools/verify-v95.cjs','utf8');eval(base.slice(base.indexOf('function extract('),base.indexOf('const notes=')));
const ids=[7,12,13,14,15,16,17,18,19,20],noop=()=>{},messages=[];
const c={Math,console,paused:false,profile:{},player:{x:0,z:0,hp:100,maxhp:100,skills:[]},L:{mode:'world',inter:[]},AR103:{},enemies:[],RARE103:ids.map(id=>({id,ready:true,n:'Classe '+id})),CLASSES:Array.from({length:21},(_,i)=>({n:'Classe '+i})),freeAt:()=>true,los:()=>true,toast:noop,closeModal:noop,fxRing:noop,scene:{remove:noop},kindsFor:()=>[{k:0}],spawnKind:(k,x,z,rank,opts)=>{const e={x,z,hp:100,dmg:5,...opts};c.enemies.push(e);return e},spawnShadow:()=>({hp:100,maxhp:100,m:{root:{}}}),store:{set:noop},saveRun:noop,narratorEvent105:noop,logNews:(x)=>messages.push(x),row:(...x)=>x.join(' '),btn:()=>'',openModal:(t,h)=>c.html=h};
vm.createContext(c);vm.runInContext(extract('awakening103'),c);vm.runInContext(fs.readFileSync('tools/journey113.js','utf8'),c);
function reset(ci){c.profile={rank:0};c.L={mode:'world',inter:[]};c.AR103={};c.player={x:0,z:0,maxhp:100,skills:[]};c.enemies=[];c.freeAt=()=>true;c.los=()=>true;c.paused=false;const a=c.awakening103();a.pending={id:123,x:0,z:0,rank:0};if(ci)assert(c.startTrial103(ci));return c.AR103.trial}
function at(n){c.player.x=n.x;c.player.z=n.z}
function win(t){t.t=0;t.targets.forEach(e=>e.dead=true);const mode=vm.runInContext('TRIALS113',c)[t.ci].mode;if(mode==='pulse'){at(t.nodes[0]);for(const n of [0,4,8]){t.t=n;assert(c.trialInteract113(t,0))}}else if(mode==='adapt'){for(const n of t.nodes){at(n);c.trialUpdate113(t,1.5)}}else if(mode==='route'){for(const n of t.nodes){at(n);c.trialWalk113(4)}}else if(mode==='read'){at(t.nodes[t.safe]);assert(c.trialInteract113(t,t.safe))}else if(mode!=='protect'){for(const n of t.nodes){at(n);assert(c.trialInteract113(t,n.index113));if(mode==='repair'||mode==='seal')c.trialUpdate113(t,2)}}t.t=12;assert(c.trialReady113(t));assert(c.finishTrial103(true));assert.equal(c.awakening103().total,1);assert.equal(c.awakening103().points[t.ci],1);assert.equal(c.awakening103().journal113.length,1);assert.equal(c.L.inter.length,0);assert.equal(c.finishTrial103(true),false);assert.equal(c.awakening103().total,1)}
for(const ci of ids){const t=reset(ci);assert.equal(c.player.skills.length,0);t.t=12;t.targets.forEach(e=>e.dead=true);if(ci!==14){assert(!c.trialReady113(t),'timer alone '+ci);assert(!c.finishTrial103(true))}win(t)}
let t=reset(12);t.t=0;assert(c.trialInteract113(t,0));assert(!c.trialInteract113(t,0));t.t=3;assert(!c.trialInteract113(t,0));t.t=4;assert(c.trialInteract113(t,0));
t=reset(13);at(t.nodes[1]);assert(!c.trialInteract113(t,1));assert.equal(t.step,0);
for(const ci of [16,20]){t=reset(ci);at(t.nodes[0]);c.trialInteract113(t,0);if(ci===16)c.player.x+=3;else Object.assign(t.targets[0],{x:c.player.x,z:c.player.z});c.trialUpdate113(t,2);assert.equal(t.step,0);assert.equal(t.channel,null)}
t=reset(18);for(const n of t.nodes){at(n);c.trialUpdate113(t,.1)}assert.equal(t.walk,0);assert.equal(t.step,0);
t=reset(19);const i=(t.safe+1)%3;at(t.nodes[i]);c.trialInteract113(t,i);c.trialInteract113(t,i);assert.equal(t.targets.length,2);assert.equal(t.step,0);
for(const reason of ['death','region','outside','helper']){t=reset(14);const old=c.L;if(reason==='death')c.player.dead=true;if(reason==='region')c.L={mode:'world',inter:[]};if(reason==='outside')c.player.x=9;if(reason==='helper')t.helper.dead=true;c.trialUpdate113(t,.1);assert.equal(c.AR103.trial,null);assert.equal(old.inter.length,0);assert(c.awakening103().pending);assert.equal(c.awakening103().total,0)}
t=reset(14);t.t=12;t.targets.forEach(e=>e.dead=true);c.awakening103().pending.id=456;assert(!c.finishTrial103(true));assert.equal(c.awakening103().total,0);assert.equal(c.awakening103().pending.id,456);
reset();c.freeAt=()=>false;assert(!c.startTrial103(7));assert.equal(c.enemies.length,0);assert.equal(c.L.inter.length,0);assert(c.awakening103().pending);
reset();c.inspectFissure103();assert(!c.html.includes('Classe'));assert(c.html.includes('Nenhuma habilidade rara'));const a=c.awakening103();a.total=3;c.inspectFissure103();assert(c.html.includes('Classe 20'));
reset();t=reset(7);win(t);assert(!c.trialJournal113().includes('Classe'));c.profile=JSON.parse(JSON.stringify(c.profile));assert(c.trialJournal113().includes('Vozes que permanecem'));c.awakening103().total=3;assert(c.trialJournal113().includes('Classe 7'));assert(c.trialChapter113(3).includes('não sabe'));
assert(src.includes('if(t)trialUpdate113(t,dt)'));assert(src.includes('it.x=a.pending.x;it.z=a.pending.z'));assert(src.includes('function kitWalk111(d){trialWalk113(d);'));
console.log('PASS: all 10 distinct journeys with no rare skills at rank F; objective gates, pulses, sequence, repair/seal interruption, real walk requirement, bounded oracle penalty, death/region/escape/helper cleanup, pending identity, blocked layout, exactly one reward, journal persistence and no early class spoilers.');

